// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MovieWithFilesColumns holds the columns for the "movie_with_files" table.
	MovieWithFilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "tmdb_id", Type: field.TypeInt32, Default: 0},
		{Name: "location", Type: field.TypeString, Default: ""},
		{Name: "metadata_adult", Type: field.TypeBool, Default: false},
		{Name: "metadata_backdrop_path", Type: field.TypeString, Default: ""},
		{Name: "metadata_genres", Type: field.TypeJSON},
		{Name: "metadata_homepage", Type: field.TypeString, Default: ""},
		{Name: "metadata_imdb_id", Type: field.TypeString, Default: ""},
		{Name: "metadata_original_language", Type: field.TypeString, Default: ""},
		{Name: "metadata_original_title", Type: field.TypeString, Default: ""},
		{Name: "metadata_overview", Type: field.TypeString, Default: ""},
		{Name: "metadata_popularity", Type: field.TypeFloat32, Default: 0},
		{Name: "metadata_poster_path", Type: field.TypeString, Default: ""},
		{Name: "metadata_release_date", Type: field.TypeString, Default: ""},
		{Name: "metadata_revenue", Type: field.TypeInt64, Default: 0},
		{Name: "metadata_runtime", Type: field.TypeInt, Default: 0},
		{Name: "metadata_spoken_languages", Type: field.TypeJSON},
		{Name: "metadata_status", Type: field.TypeString, Default: ""},
		{Name: "metadata_tagline", Type: field.TypeString, Default: ""},
		{Name: "metadata_title", Type: field.TypeString, Default: ""},
		{Name: "metadata_video", Type: field.TypeBool, Default: false},
		{Name: "metadata_vote_average", Type: field.TypeFloat32, Default: 0},
		{Name: "metadata_vote_count", Type: field.TypeInt64, Default: 0},
		{Name: "collection_id", Type: field.TypeInt64, Default: 0},
		{Name: "collection_name", Type: field.TypeString, Default: ""},
		{Name: "collection_poster_path", Type: field.TypeString, Default: ""},
		{Name: "collection_backdrop_path", Type: field.TypeString, Default: ""},
	}
	// MovieWithFilesTable holds the schema information for the "movie_with_files" table.
	MovieWithFilesTable = &schema.Table{
		Name:       "movie_with_files",
		Columns:    MovieWithFilesColumns,
		PrimaryKey: []*schema.Column{MovieWithFilesColumns[0]},
	}
	// UserAccountsColumns holds the columns for the "user_accounts" table.
	UserAccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "displayname", Type: field.TypeString, Size: 48},
		{Name: "username", Type: field.TypeString, Size: 16},
		{Name: "email", Type: field.TypeString, Size: 128},
		{Name: "password", Type: field.TypeString},
		{Name: "sex", Type: field.TypeString, Size: 10},
		{Name: "role", Type: field.TypeString, Size: 15},
		{Name: "api_key", Type: field.TypeString, Size: 32},
		{Name: "current_status", Type: field.TypeString, Size: 15, Default: ""},
		{Name: "setting_theme", Type: field.TypeString, Size: 10, Default: "system"},
		{Name: "setting_enabled", Type: field.TypeBool, Default: true},
		{Name: "setting_language", Type: field.TypeString, Size: 10, Default: "en-US"},
		{Name: "setting_resolution", Type: field.TypeString, Size: 10, Default: "direct"},
		{Name: "setting_bitrate", Type: field.TypeInt, Default: 2000},
		{Name: "setting_codec", Type: field.TypeString, Size: 10, Default: "h264"},
		{Name: "last_seen_at", Type: field.TypeTime, Nullable: true},
	}
	// UserAccountsTable holds the schema information for the "user_accounts" table.
	UserAccountsTable = &schema.Table{
		Name:       "user_accounts",
		Columns:    UserAccountsColumns,
		PrimaryKey: []*schema.Column{UserAccountsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "useraccount_username",
				Unique:  true,
				Columns: []*schema.Column{UserAccountsColumns[5]},
			},
			{
				Name:    "useraccount_email",
				Unique:  true,
				Columns: []*schema.Column{UserAccountsColumns[6]},
			},
			{
				Name:    "useraccount_api_key",
				Unique:  true,
				Columns: []*schema.Column{UserAccountsColumns[10]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MovieWithFilesTable,
		UserAccountsTable,
	}
)

func init() {
}
