// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/lunarr-app/lunarr-go/internal/ent/moviewithfile"
	"github.com/lunarr-app/lunarr-go/internal/models"
)

// MovieWithFile is the model entity for the MovieWithFile schema.
type MovieWithFile struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// TmdbID holds the value of the "tmdb_id" field.
	TmdbID int32 `json:"tmdb_id,omitempty"`
	// Location holds the value of the "location" field.
	Location string `json:"location,omitempty"`
	// MetadataAdult holds the value of the "metadata_adult" field.
	MetadataAdult bool `json:"metadata_adult,omitempty"`
	// MetadataBackdropPath holds the value of the "metadata_backdrop_path" field.
	MetadataBackdropPath string `json:"metadata_backdrop_path,omitempty"`
	// MetadataGenres holds the value of the "metadata_genres" field.
	MetadataGenres []models.TMDbGenre `json:"metadata_genres,omitempty"`
	// MetadataHomepage holds the value of the "metadata_homepage" field.
	MetadataHomepage string `json:"metadata_homepage,omitempty"`
	// MetadataImdbID holds the value of the "metadata_imdb_id" field.
	MetadataImdbID string `json:"metadata_imdb_id,omitempty"`
	// MetadataOriginalLanguage holds the value of the "metadata_original_language" field.
	MetadataOriginalLanguage string `json:"metadata_original_language,omitempty"`
	// MetadataOriginalTitle holds the value of the "metadata_original_title" field.
	MetadataOriginalTitle string `json:"metadata_original_title,omitempty"`
	// MetadataOverview holds the value of the "metadata_overview" field.
	MetadataOverview string `json:"metadata_overview,omitempty"`
	// MetadataPopularity holds the value of the "metadata_popularity" field.
	MetadataPopularity float32 `json:"metadata_popularity,omitempty"`
	// MetadataPosterPath holds the value of the "metadata_poster_path" field.
	MetadataPosterPath string `json:"metadata_poster_path,omitempty"`
	// MetadataReleaseDate holds the value of the "metadata_release_date" field.
	MetadataReleaseDate string `json:"metadata_release_date,omitempty"`
	// MetadataRevenue holds the value of the "metadata_revenue" field.
	MetadataRevenue int64 `json:"metadata_revenue,omitempty"`
	// MetadataRuntime holds the value of the "metadata_runtime" field.
	MetadataRuntime int `json:"metadata_runtime,omitempty"`
	// MetadataSpokenLanguages holds the value of the "metadata_spoken_languages" field.
	MetadataSpokenLanguages []models.TMDbSpokenLanguage `json:"metadata_spoken_languages,omitempty"`
	// MetadataStatus holds the value of the "metadata_status" field.
	MetadataStatus string `json:"metadata_status,omitempty"`
	// MetadataTagline holds the value of the "metadata_tagline" field.
	MetadataTagline string `json:"metadata_tagline,omitempty"`
	// MetadataTitle holds the value of the "metadata_title" field.
	MetadataTitle string `json:"metadata_title,omitempty"`
	// MetadataVideo holds the value of the "metadata_video" field.
	MetadataVideo bool `json:"metadata_video,omitempty"`
	// MetadataVoteAverage holds the value of the "metadata_vote_average" field.
	MetadataVoteAverage float32 `json:"metadata_vote_average,omitempty"`
	// MetadataVoteCount holds the value of the "metadata_vote_count" field.
	MetadataVoteCount int64 `json:"metadata_vote_count,omitempty"`
	// CollectionID holds the value of the "collection_id" field.
	CollectionID int64 `json:"collection_id,omitempty"`
	// CollectionName holds the value of the "collection_name" field.
	CollectionName string `json:"collection_name,omitempty"`
	// CollectionPosterPath holds the value of the "collection_poster_path" field.
	CollectionPosterPath string `json:"collection_poster_path,omitempty"`
	// CollectionBackdropPath holds the value of the "collection_backdrop_path" field.
	CollectionBackdropPath string `json:"collection_backdrop_path,omitempty"`
	selectValues           sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MovieWithFile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case moviewithfile.FieldMetadataGenres, moviewithfile.FieldMetadataSpokenLanguages:
			values[i] = new([]byte)
		case moviewithfile.FieldMetadataAdult, moviewithfile.FieldMetadataVideo:
			values[i] = new(sql.NullBool)
		case moviewithfile.FieldMetadataPopularity, moviewithfile.FieldMetadataVoteAverage:
			values[i] = new(sql.NullFloat64)
		case moviewithfile.FieldID, moviewithfile.FieldTmdbID, moviewithfile.FieldMetadataRevenue, moviewithfile.FieldMetadataRuntime, moviewithfile.FieldMetadataVoteCount, moviewithfile.FieldCollectionID:
			values[i] = new(sql.NullInt64)
		case moviewithfile.FieldLocation, moviewithfile.FieldMetadataBackdropPath, moviewithfile.FieldMetadataHomepage, moviewithfile.FieldMetadataImdbID, moviewithfile.FieldMetadataOriginalLanguage, moviewithfile.FieldMetadataOriginalTitle, moviewithfile.FieldMetadataOverview, moviewithfile.FieldMetadataPosterPath, moviewithfile.FieldMetadataReleaseDate, moviewithfile.FieldMetadataStatus, moviewithfile.FieldMetadataTagline, moviewithfile.FieldMetadataTitle, moviewithfile.FieldCollectionName, moviewithfile.FieldCollectionPosterPath, moviewithfile.FieldCollectionBackdropPath:
			values[i] = new(sql.NullString)
		case moviewithfile.FieldCreatedAt, moviewithfile.FieldUpdatedAt, moviewithfile.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MovieWithFile fields.
func (_m *MovieWithFile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case moviewithfile.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case moviewithfile.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case moviewithfile.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case moviewithfile.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case moviewithfile.FieldTmdbID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tmdb_id", values[i])
			} else if value.Valid {
				_m.TmdbID = int32(value.Int64)
			}
		case moviewithfile.FieldLocation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field location", values[i])
			} else if value.Valid {
				_m.Location = value.String
			}
		case moviewithfile.FieldMetadataAdult:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field metadata_adult", values[i])
			} else if value.Valid {
				_m.MetadataAdult = value.Bool
			}
		case moviewithfile.FieldMetadataBackdropPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metadata_backdrop_path", values[i])
			} else if value.Valid {
				_m.MetadataBackdropPath = value.String
			}
		case moviewithfile.FieldMetadataGenres:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata_genres", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.MetadataGenres); err != nil {
					return fmt.Errorf("unmarshal field metadata_genres: %w", err)
				}
			}
		case moviewithfile.FieldMetadataHomepage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metadata_homepage", values[i])
			} else if value.Valid {
				_m.MetadataHomepage = value.String
			}
		case moviewithfile.FieldMetadataImdbID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metadata_imdb_id", values[i])
			} else if value.Valid {
				_m.MetadataImdbID = value.String
			}
		case moviewithfile.FieldMetadataOriginalLanguage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metadata_original_language", values[i])
			} else if value.Valid {
				_m.MetadataOriginalLanguage = value.String
			}
		case moviewithfile.FieldMetadataOriginalTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metadata_original_title", values[i])
			} else if value.Valid {
				_m.MetadataOriginalTitle = value.String
			}
		case moviewithfile.FieldMetadataOverview:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metadata_overview", values[i])
			} else if value.Valid {
				_m.MetadataOverview = value.String
			}
		case moviewithfile.FieldMetadataPopularity:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field metadata_popularity", values[i])
			} else if value.Valid {
				_m.MetadataPopularity = float32(value.Float64)
			}
		case moviewithfile.FieldMetadataPosterPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metadata_poster_path", values[i])
			} else if value.Valid {
				_m.MetadataPosterPath = value.String
			}
		case moviewithfile.FieldMetadataReleaseDate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metadata_release_date", values[i])
			} else if value.Valid {
				_m.MetadataReleaseDate = value.String
			}
		case moviewithfile.FieldMetadataRevenue:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field metadata_revenue", values[i])
			} else if value.Valid {
				_m.MetadataRevenue = value.Int64
			}
		case moviewithfile.FieldMetadataRuntime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field metadata_runtime", values[i])
			} else if value.Valid {
				_m.MetadataRuntime = int(value.Int64)
			}
		case moviewithfile.FieldMetadataSpokenLanguages:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata_spoken_languages", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.MetadataSpokenLanguages); err != nil {
					return fmt.Errorf("unmarshal field metadata_spoken_languages: %w", err)
				}
			}
		case moviewithfile.FieldMetadataStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metadata_status", values[i])
			} else if value.Valid {
				_m.MetadataStatus = value.String
			}
		case moviewithfile.FieldMetadataTagline:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metadata_tagline", values[i])
			} else if value.Valid {
				_m.MetadataTagline = value.String
			}
		case moviewithfile.FieldMetadataTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metadata_title", values[i])
			} else if value.Valid {
				_m.MetadataTitle = value.String
			}
		case moviewithfile.FieldMetadataVideo:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field metadata_video", values[i])
			} else if value.Valid {
				_m.MetadataVideo = value.Bool
			}
		case moviewithfile.FieldMetadataVoteAverage:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field metadata_vote_average", values[i])
			} else if value.Valid {
				_m.MetadataVoteAverage = float32(value.Float64)
			}
		case moviewithfile.FieldMetadataVoteCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field metadata_vote_count", values[i])
			} else if value.Valid {
				_m.MetadataVoteCount = value.Int64
			}
		case moviewithfile.FieldCollectionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field collection_id", values[i])
			} else if value.Valid {
				_m.CollectionID = value.Int64
			}
		case moviewithfile.FieldCollectionName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field collection_name", values[i])
			} else if value.Valid {
				_m.CollectionName = value.String
			}
		case moviewithfile.FieldCollectionPosterPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field collection_poster_path", values[i])
			} else if value.Valid {
				_m.CollectionPosterPath = value.String
			}
		case moviewithfile.FieldCollectionBackdropPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field collection_backdrop_path", values[i])
			} else if value.Valid {
				_m.CollectionBackdropPath = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MovieWithFile.
// This includes values selected through modifiers, order, etc.
func (_m *MovieWithFile) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MovieWithFile.
// Note that you need to call MovieWithFile.Unwrap() before calling this method if this MovieWithFile
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MovieWithFile) Update() *MovieWithFileUpdateOne {
	return NewMovieWithFileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MovieWithFile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MovieWithFile) Unwrap() *MovieWithFile {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MovieWithFile is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MovieWithFile) String() string {
	var builder strings.Builder
	builder.WriteString("MovieWithFile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("tmdb_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TmdbID))
	builder.WriteString(", ")
	builder.WriteString("location=")
	builder.WriteString(_m.Location)
	builder.WriteString(", ")
	builder.WriteString("metadata_adult=")
	builder.WriteString(fmt.Sprintf("%v", _m.MetadataAdult))
	builder.WriteString(", ")
	builder.WriteString("metadata_backdrop_path=")
	builder.WriteString(_m.MetadataBackdropPath)
	builder.WriteString(", ")
	builder.WriteString("metadata_genres=")
	builder.WriteString(fmt.Sprintf("%v", _m.MetadataGenres))
	builder.WriteString(", ")
	builder.WriteString("metadata_homepage=")
	builder.WriteString(_m.MetadataHomepage)
	builder.WriteString(", ")
	builder.WriteString("metadata_imdb_id=")
	builder.WriteString(_m.MetadataImdbID)
	builder.WriteString(", ")
	builder.WriteString("metadata_original_language=")
	builder.WriteString(_m.MetadataOriginalLanguage)
	builder.WriteString(", ")
	builder.WriteString("metadata_original_title=")
	builder.WriteString(_m.MetadataOriginalTitle)
	builder.WriteString(", ")
	builder.WriteString("metadata_overview=")
	builder.WriteString(_m.MetadataOverview)
	builder.WriteString(", ")
	builder.WriteString("metadata_popularity=")
	builder.WriteString(fmt.Sprintf("%v", _m.MetadataPopularity))
	builder.WriteString(", ")
	builder.WriteString("metadata_poster_path=")
	builder.WriteString(_m.MetadataPosterPath)
	builder.WriteString(", ")
	builder.WriteString("metadata_release_date=")
	builder.WriteString(_m.MetadataReleaseDate)
	builder.WriteString(", ")
	builder.WriteString("metadata_revenue=")
	builder.WriteString(fmt.Sprintf("%v", _m.MetadataRevenue))
	builder.WriteString(", ")
	builder.WriteString("metadata_runtime=")
	builder.WriteString(fmt.Sprintf("%v", _m.MetadataRuntime))
	builder.WriteString(", ")
	builder.WriteString("metadata_spoken_languages=")
	builder.WriteString(fmt.Sprintf("%v", _m.MetadataSpokenLanguages))
	builder.WriteString(", ")
	builder.WriteString("metadata_status=")
	builder.WriteString(_m.MetadataStatus)
	builder.WriteString(", ")
	builder.WriteString("metadata_tagline=")
	builder.WriteString(_m.MetadataTagline)
	builder.WriteString(", ")
	builder.WriteString("metadata_title=")
	builder.WriteString(_m.MetadataTitle)
	builder.WriteString(", ")
	builder.WriteString("metadata_video=")
	builder.WriteString(fmt.Sprintf("%v", _m.MetadataVideo))
	builder.WriteString(", ")
	builder.WriteString("metadata_vote_average=")
	builder.WriteString(fmt.Sprintf("%v", _m.MetadataVoteAverage))
	builder.WriteString(", ")
	builder.WriteString("metadata_vote_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.MetadataVoteCount))
	builder.WriteString(", ")
	builder.WriteString("collection_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CollectionID))
	builder.WriteString(", ")
	builder.WriteString("collection_name=")
	builder.WriteString(_m.CollectionName)
	builder.WriteString(", ")
	builder.WriteString("collection_poster_path=")
	builder.WriteString(_m.CollectionPosterPath)
	builder.WriteString(", ")
	builder.WriteString("collection_backdrop_path=")
	builder.WriteString(_m.CollectionBackdropPath)
	builder.WriteByte(')')
	return builder.String()
}

// MovieWithFiles is a parsable slice of MovieWithFile.
type MovieWithFiles []*MovieWithFile
