// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/lunarr-app/lunarr-go/internal/ent/moviewithfile"
	"github.com/lunarr-app/lunarr-go/internal/ent/predicate"
	"github.com/lunarr-app/lunarr-go/internal/models"
)

// MovieWithFileUpdate is the builder for updating MovieWithFile entities.
type MovieWithFileUpdate struct {
	config
	hooks    []Hook
	mutation *MovieWithFileMutation
}

// Where appends a list predicates to the MovieWithFileUpdate builder.
func (_u *MovieWithFileUpdate) Where(ps ...predicate.MovieWithFile) *MovieWithFileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MovieWithFileUpdate) SetUpdatedAt(v time.Time) *MovieWithFileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *MovieWithFileUpdate) SetDeletedAt(v time.Time) *MovieWithFileUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *MovieWithFileUpdate) SetNillableDeletedAt(v *time.Time) *MovieWithFileUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *MovieWithFileUpdate) ClearDeletedAt() *MovieWithFileUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetTmdbID sets the "tmdb_id" field.
func (_u *MovieWithFileUpdate) SetTmdbID(v int32) *MovieWithFileUpdate {
	_u.mutation.ResetTmdbID()
	_u.mutation.SetTmdbID(v)
	return _u
}

// SetNillableTmdbID sets the "tmdb_id" field if the given value is not nil.
func (_u *MovieWithFileUpdate) SetNillableTmdbID(v *int32) *MovieWithFileUpdate {
	if v != nil {
		_u.SetTmdbID(*v)
	}
	return _u
}

// AddTmdbID adds value to the "tmdb_id" field.
func (_u *MovieWithFileUpdate) AddTmdbID(v int32) *MovieWithFileUpdate {
	_u.mutation.AddTmdbID(v)
	return _u
}

// SetLocation sets the "location" field.
func (_u *MovieWithFileUpdate) SetLocation(v string) *MovieWithFileUpdate {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *MovieWithFileUpdate) SetNillableLocation(v *string) *MovieWithFileUpdate {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// SetMetadataAdult sets the "metadata_adult" field.
func (_u *MovieWithFileUpdate) SetMetadataAdult(v bool) *MovieWithFileUpdate {
	_u.mutation.SetMetadataAdult(v)
	return _u
}

// SetNillableMetadataAdult sets the "metadata_adult" field if the given value is not nil.
func (_u *MovieWithFileUpdate) SetNillableMetadataAdult(v *bool) *MovieWithFileUpdate {
	if v != nil {
		_u.SetMetadataAdult(*v)
	}
	return _u
}

// SetMetadataBackdropPath sets the "metadata_backdrop_path" field.
func (_u *MovieWithFileUpdate) SetMetadataBackdropPath(v string) *MovieWithFileUpdate {
	_u.mutation.SetMetadataBackdropPath(v)
	return _u
}

// SetNillableMetadataBackdropPath sets the "metadata_backdrop_path" field if the given value is not nil.
func (_u *MovieWithFileUpdate) SetNillableMetadataBackdropPath(v *string) *MovieWithFileUpdate {
	if v != nil {
		_u.SetMetadataBackdropPath(*v)
	}
	return _u
}

// SetMetadataGenres sets the "metadata_genres" field.
func (_u *MovieWithFileUpdate) SetMetadataGenres(v []models.TMDbGenre) *MovieWithFileUpdate {
	_u.mutation.SetMetadataGenres(v)
	return _u
}

// AppendMetadataGenres appends value to the "metadata_genres" field.
func (_u *MovieWithFileUpdate) AppendMetadataGenres(v []models.TMDbGenre) *MovieWithFileUpdate {
	_u.mutation.AppendMetadataGenres(v)
	return _u
}

// SetMetadataHomepage sets the "metadata_homepage" field.
func (_u *MovieWithFileUpdate) SetMetadataHomepage(v string) *MovieWithFileUpdate {
	_u.mutation.SetMetadataHomepage(v)
	return _u
}

// SetNillableMetadataHomepage sets the "metadata_homepage" field if the given value is not nil.
func (_u *MovieWithFileUpdate) SetNillableMetadataHomepage(v *string) *MovieWithFileUpdate {
	if v != nil {
		_u.SetMetadataHomepage(*v)
	}
	return _u
}

// SetMetadataImdbID sets the "metadata_imdb_id" field.
func (_u *MovieWithFileUpdate) SetMetadataImdbID(v string) *MovieWithFileUpdate {
	_u.mutation.SetMetadataImdbID(v)
	return _u
}

// SetNillableMetadataImdbID sets the "metadata_imdb_id" field if the given value is not nil.
func (_u *MovieWithFileUpdate) SetNillableMetadataImdbID(v *string) *MovieWithFileUpdate {
	if v != nil {
		_u.SetMetadataImdbID(*v)
	}
	return _u
}

// SetMetadataOriginalLanguage sets the "metadata_original_language" field.
func (_u *MovieWithFileUpdate) SetMetadataOriginalLanguage(v string) *MovieWithFileUpdate {
	_u.mutation.SetMetadataOriginalLanguage(v)
	return _u
}

// SetNillableMetadataOriginalLanguage sets the "metadata_original_language" field if the given value is not nil.
func (_u *MovieWithFileUpdate) SetNillableMetadataOriginalLanguage(v *string) *MovieWithFileUpdate {
	if v != nil {
		_u.SetMetadataOriginalLanguage(*v)
	}
	return _u
}

// SetMetadataOriginalTitle sets the "metadata_original_title" field.
func (_u *MovieWithFileUpdate) SetMetadataOriginalTitle(v string) *MovieWithFileUpdate {
	_u.mutation.SetMetadataOriginalTitle(v)
	return _u
}

// SetNillableMetadataOriginalTitle sets the "metadata_original_title" field if the given value is not nil.
func (_u *MovieWithFileUpdate) SetNillableMetadataOriginalTitle(v *string) *MovieWithFileUpdate {
	if v != nil {
		_u.SetMetadataOriginalTitle(*v)
	}
	return _u
}

// SetMetadataOverview sets the "metadata_overview" field.
func (_u *MovieWithFileUpdate) SetMetadataOverview(v string) *MovieWithFileUpdate {
	_u.mutation.SetMetadataOverview(v)
	return _u
}

// SetNillableMetadataOverview sets the "metadata_overview" field if the given value is not nil.
func (_u *MovieWithFileUpdate) SetNillableMetadataOverview(v *string) *MovieWithFileUpdate {
	if v != nil {
		_u.SetMetadataOverview(*v)
	}
	return _u
}

// SetMetadataPopularity sets the "metadata_popularity" field.
func (_u *MovieWithFileUpdate) SetMetadataPopularity(v float32) *MovieWithFileUpdate {
	_u.mutation.ResetMetadataPopularity()
	_u.mutation.SetMetadataPopularity(v)
	return _u
}

// SetNillableMetadataPopularity sets the "metadata_popularity" field if the given value is not nil.
func (_u *MovieWithFileUpdate) SetNillableMetadataPopularity(v *float32) *MovieWithFileUpdate {
	if v != nil {
		_u.SetMetadataPopularity(*v)
	}
	return _u
}

// AddMetadataPopularity adds value to the "metadata_popularity" field.
func (_u *MovieWithFileUpdate) AddMetadataPopularity(v float32) *MovieWithFileUpdate {
	_u.mutation.AddMetadataPopularity(v)
	return _u
}

// SetMetadataPosterPath sets the "metadata_poster_path" field.
func (_u *MovieWithFileUpdate) SetMetadataPosterPath(v string) *MovieWithFileUpdate {
	_u.mutation.SetMetadataPosterPath(v)
	return _u
}

// SetNillableMetadataPosterPath sets the "metadata_poster_path" field if the given value is not nil.
func (_u *MovieWithFileUpdate) SetNillableMetadataPosterPath(v *string) *MovieWithFileUpdate {
	if v != nil {
		_u.SetMetadataPosterPath(*v)
	}
	return _u
}

// SetMetadataReleaseDate sets the "metadata_release_date" field.
func (_u *MovieWithFileUpdate) SetMetadataReleaseDate(v string) *MovieWithFileUpdate {
	_u.mutation.SetMetadataReleaseDate(v)
	return _u
}

// SetNillableMetadataReleaseDate sets the "metadata_release_date" field if the given value is not nil.
func (_u *MovieWithFileUpdate) SetNillableMetadataReleaseDate(v *string) *MovieWithFileUpdate {
	if v != nil {
		_u.SetMetadataReleaseDate(*v)
	}
	return _u
}

// SetMetadataRevenue sets the "metadata_revenue" field.
func (_u *MovieWithFileUpdate) SetMetadataRevenue(v int64) *MovieWithFileUpdate {
	_u.mutation.ResetMetadataRevenue()
	_u.mutation.SetMetadataRevenue(v)
	return _u
}

// SetNillableMetadataRevenue sets the "metadata_revenue" field if the given value is not nil.
func (_u *MovieWithFileUpdate) SetNillableMetadataRevenue(v *int64) *MovieWithFileUpdate {
	if v != nil {
		_u.SetMetadataRevenue(*v)
	}
	return _u
}

// AddMetadataRevenue adds value to the "metadata_revenue" field.
func (_u *MovieWithFileUpdate) AddMetadataRevenue(v int64) *MovieWithFileUpdate {
	_u.mutation.AddMetadataRevenue(v)
	return _u
}

// SetMetadataRuntime sets the "metadata_runtime" field.
func (_u *MovieWithFileUpdate) SetMetadataRuntime(v int) *MovieWithFileUpdate {
	_u.mutation.ResetMetadataRuntime()
	_u.mutation.SetMetadataRuntime(v)
	return _u
}

// SetNillableMetadataRuntime sets the "metadata_runtime" field if the given value is not nil.
func (_u *MovieWithFileUpdate) SetNillableMetadataRuntime(v *int) *MovieWithFileUpdate {
	if v != nil {
		_u.SetMetadataRuntime(*v)
	}
	return _u
}

// AddMetadataRuntime adds value to the "metadata_runtime" field.
func (_u *MovieWithFileUpdate) AddMetadataRuntime(v int) *MovieWithFileUpdate {
	_u.mutation.AddMetadataRuntime(v)
	return _u
}

// SetMetadataSpokenLanguages sets the "metadata_spoken_languages" field.
func (_u *MovieWithFileUpdate) SetMetadataSpokenLanguages(v []models.TMDbSpokenLanguage) *MovieWithFileUpdate {
	_u.mutation.SetMetadataSpokenLanguages(v)
	return _u
}

// AppendMetadataSpokenLanguages appends value to the "metadata_spoken_languages" field.
func (_u *MovieWithFileUpdate) AppendMetadataSpokenLanguages(v []models.TMDbSpokenLanguage) *MovieWithFileUpdate {
	_u.mutation.AppendMetadataSpokenLanguages(v)
	return _u
}

// SetMetadataStatus sets the "metadata_status" field.
func (_u *MovieWithFileUpdate) SetMetadataStatus(v string) *MovieWithFileUpdate {
	_u.mutation.SetMetadataStatus(v)
	return _u
}

// SetNillableMetadataStatus sets the "metadata_status" field if the given value is not nil.
func (_u *MovieWithFileUpdate) SetNillableMetadataStatus(v *string) *MovieWithFileUpdate {
	if v != nil {
		_u.SetMetadataStatus(*v)
	}
	return _u
}

// SetMetadataTagline sets the "metadata_tagline" field.
func (_u *MovieWithFileUpdate) SetMetadataTagline(v string) *MovieWithFileUpdate {
	_u.mutation.SetMetadataTagline(v)
	return _u
}

// SetNillableMetadataTagline sets the "metadata_tagline" field if the given value is not nil.
func (_u *MovieWithFileUpdate) SetNillableMetadataTagline(v *string) *MovieWithFileUpdate {
	if v != nil {
		_u.SetMetadataTagline(*v)
	}
	return _u
}

// SetMetadataTitle sets the "metadata_title" field.
func (_u *MovieWithFileUpdate) SetMetadataTitle(v string) *MovieWithFileUpdate {
	_u.mutation.SetMetadataTitle(v)
	return _u
}

// SetNillableMetadataTitle sets the "metadata_title" field if the given value is not nil.
func (_u *MovieWithFileUpdate) SetNillableMetadataTitle(v *string) *MovieWithFileUpdate {
	if v != nil {
		_u.SetMetadataTitle(*v)
	}
	return _u
}

// SetMetadataVideo sets the "metadata_video" field.
func (_u *MovieWithFileUpdate) SetMetadataVideo(v bool) *MovieWithFileUpdate {
	_u.mutation.SetMetadataVideo(v)
	return _u
}

// SetNillableMetadataVideo sets the "metadata_video" field if the given value is not nil.
func (_u *MovieWithFileUpdate) SetNillableMetadataVideo(v *bool) *MovieWithFileUpdate {
	if v != nil {
		_u.SetMetadataVideo(*v)
	}
	return _u
}

// SetMetadataVoteAverage sets the "metadata_vote_average" field.
func (_u *MovieWithFileUpdate) SetMetadataVoteAverage(v float32) *MovieWithFileUpdate {
	_u.mutation.ResetMetadataVoteAverage()
	_u.mutation.SetMetadataVoteAverage(v)
	return _u
}

// SetNillableMetadataVoteAverage sets the "metadata_vote_average" field if the given value is not nil.
func (_u *MovieWithFileUpdate) SetNillableMetadataVoteAverage(v *float32) *MovieWithFileUpdate {
	if v != nil {
		_u.SetMetadataVoteAverage(*v)
	}
	return _u
}

// AddMetadataVoteAverage adds value to the "metadata_vote_average" field.
func (_u *MovieWithFileUpdate) AddMetadataVoteAverage(v float32) *MovieWithFileUpdate {
	_u.mutation.AddMetadataVoteAverage(v)
	return _u
}

// SetMetadataVoteCount sets the "metadata_vote_count" field.
func (_u *MovieWithFileUpdate) SetMetadataVoteCount(v int64) *MovieWithFileUpdate {
	_u.mutation.ResetMetadataVoteCount()
	_u.mutation.SetMetadataVoteCount(v)
	return _u
}

// SetNillableMetadataVoteCount sets the "metadata_vote_count" field if the given value is not nil.
func (_u *MovieWithFileUpdate) SetNillableMetadataVoteCount(v *int64) *MovieWithFileUpdate {
	if v != nil {
		_u.SetMetadataVoteCount(*v)
	}
	return _u
}

// AddMetadataVoteCount adds value to the "metadata_vote_count" field.
func (_u *MovieWithFileUpdate) AddMetadataVoteCount(v int64) *MovieWithFileUpdate {
	_u.mutation.AddMetadataVoteCount(v)
	return _u
}

// SetCollectionID sets the "collection_id" field.
func (_u *MovieWithFileUpdate) SetCollectionID(v int64) *MovieWithFileUpdate {
	_u.mutation.ResetCollectionID()
	_u.mutation.SetCollectionID(v)
	return _u
}

// SetNillableCollectionID sets the "collection_id" field if the given value is not nil.
func (_u *MovieWithFileUpdate) SetNillableCollectionID(v *int64) *MovieWithFileUpdate {
	if v != nil {
		_u.SetCollectionID(*v)
	}
	return _u
}

// AddCollectionID adds value to the "collection_id" field.
func (_u *MovieWithFileUpdate) AddCollectionID(v int64) *MovieWithFileUpdate {
	_u.mutation.AddCollectionID(v)
	return _u
}

// SetCollectionName sets the "collection_name" field.
func (_u *MovieWithFileUpdate) SetCollectionName(v string) *MovieWithFileUpdate {
	_u.mutation.SetCollectionName(v)
	return _u
}

// SetNillableCollectionName sets the "collection_name" field if the given value is not nil.
func (_u *MovieWithFileUpdate) SetNillableCollectionName(v *string) *MovieWithFileUpdate {
	if v != nil {
		_u.SetCollectionName(*v)
	}
	return _u
}

// SetCollectionPosterPath sets the "collection_poster_path" field.
func (_u *MovieWithFileUpdate) SetCollectionPosterPath(v string) *MovieWithFileUpdate {
	_u.mutation.SetCollectionPosterPath(v)
	return _u
}

// SetNillableCollectionPosterPath sets the "collection_poster_path" field if the given value is not nil.
func (_u *MovieWithFileUpdate) SetNillableCollectionPosterPath(v *string) *MovieWithFileUpdate {
	if v != nil {
		_u.SetCollectionPosterPath(*v)
	}
	return _u
}

// SetCollectionBackdropPath sets the "collection_backdrop_path" field.
func (_u *MovieWithFileUpdate) SetCollectionBackdropPath(v string) *MovieWithFileUpdate {
	_u.mutation.SetCollectionBackdropPath(v)
	return _u
}

// SetNillableCollectionBackdropPath sets the "collection_backdrop_path" field if the given value is not nil.
func (_u *MovieWithFileUpdate) SetNillableCollectionBackdropPath(v *string) *MovieWithFileUpdate {
	if v != nil {
		_u.SetCollectionBackdropPath(*v)
	}
	return _u
}

// Mutation returns the MovieWithFileMutation object of the builder.
func (_u *MovieWithFileUpdate) Mutation() *MovieWithFileMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MovieWithFileUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MovieWithFileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MovieWithFileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MovieWithFileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MovieWithFileUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := moviewithfile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *MovieWithFileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(moviewithfile.Table, moviewithfile.Columns, sqlgraph.NewFieldSpec(moviewithfile.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(moviewithfile.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(moviewithfile.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(moviewithfile.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.TmdbID(); ok {
		_spec.SetField(moviewithfile.FieldTmdbID, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedTmdbID(); ok {
		_spec.AddField(moviewithfile.FieldTmdbID, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(moviewithfile.FieldLocation, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataAdult(); ok {
		_spec.SetField(moviewithfile.FieldMetadataAdult, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MetadataBackdropPath(); ok {
		_spec.SetField(moviewithfile.FieldMetadataBackdropPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataGenres(); ok {
		_spec.SetField(moviewithfile.FieldMetadataGenres, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMetadataGenres(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, moviewithfile.FieldMetadataGenres, value)
		})
	}
	if value, ok := _u.mutation.MetadataHomepage(); ok {
		_spec.SetField(moviewithfile.FieldMetadataHomepage, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataImdbID(); ok {
		_spec.SetField(moviewithfile.FieldMetadataImdbID, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataOriginalLanguage(); ok {
		_spec.SetField(moviewithfile.FieldMetadataOriginalLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataOriginalTitle(); ok {
		_spec.SetField(moviewithfile.FieldMetadataOriginalTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataOverview(); ok {
		_spec.SetField(moviewithfile.FieldMetadataOverview, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataPopularity(); ok {
		_spec.SetField(moviewithfile.FieldMetadataPopularity, field.TypeFloat32, value)
	}
	if value, ok := _u.mutation.AddedMetadataPopularity(); ok {
		_spec.AddField(moviewithfile.FieldMetadataPopularity, field.TypeFloat32, value)
	}
	if value, ok := _u.mutation.MetadataPosterPath(); ok {
		_spec.SetField(moviewithfile.FieldMetadataPosterPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataReleaseDate(); ok {
		_spec.SetField(moviewithfile.FieldMetadataReleaseDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataRevenue(); ok {
		_spec.SetField(moviewithfile.FieldMetadataRevenue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMetadataRevenue(); ok {
		_spec.AddField(moviewithfile.FieldMetadataRevenue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MetadataRuntime(); ok {
		_spec.SetField(moviewithfile.FieldMetadataRuntime, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMetadataRuntime(); ok {
		_spec.AddField(moviewithfile.FieldMetadataRuntime, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MetadataSpokenLanguages(); ok {
		_spec.SetField(moviewithfile.FieldMetadataSpokenLanguages, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMetadataSpokenLanguages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, moviewithfile.FieldMetadataSpokenLanguages, value)
		})
	}
	if value, ok := _u.mutation.MetadataStatus(); ok {
		_spec.SetField(moviewithfile.FieldMetadataStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataTagline(); ok {
		_spec.SetField(moviewithfile.FieldMetadataTagline, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataTitle(); ok {
		_spec.SetField(moviewithfile.FieldMetadataTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataVideo(); ok {
		_spec.SetField(moviewithfile.FieldMetadataVideo, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MetadataVoteAverage(); ok {
		_spec.SetField(moviewithfile.FieldMetadataVoteAverage, field.TypeFloat32, value)
	}
	if value, ok := _u.mutation.AddedMetadataVoteAverage(); ok {
		_spec.AddField(moviewithfile.FieldMetadataVoteAverage, field.TypeFloat32, value)
	}
	if value, ok := _u.mutation.MetadataVoteCount(); ok {
		_spec.SetField(moviewithfile.FieldMetadataVoteCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMetadataVoteCount(); ok {
		_spec.AddField(moviewithfile.FieldMetadataVoteCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CollectionID(); ok {
		_spec.SetField(moviewithfile.FieldCollectionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCollectionID(); ok {
		_spec.AddField(moviewithfile.FieldCollectionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CollectionName(); ok {
		_spec.SetField(moviewithfile.FieldCollectionName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CollectionPosterPath(); ok {
		_spec.SetField(moviewithfile.FieldCollectionPosterPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.CollectionBackdropPath(); ok {
		_spec.SetField(moviewithfile.FieldCollectionBackdropPath, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{moviewithfile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MovieWithFileUpdateOne is the builder for updating a single MovieWithFile entity.
type MovieWithFileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MovieWithFileMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MovieWithFileUpdateOne) SetUpdatedAt(v time.Time) *MovieWithFileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *MovieWithFileUpdateOne) SetDeletedAt(v time.Time) *MovieWithFileUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *MovieWithFileUpdateOne) SetNillableDeletedAt(v *time.Time) *MovieWithFileUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *MovieWithFileUpdateOne) ClearDeletedAt() *MovieWithFileUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetTmdbID sets the "tmdb_id" field.
func (_u *MovieWithFileUpdateOne) SetTmdbID(v int32) *MovieWithFileUpdateOne {
	_u.mutation.ResetTmdbID()
	_u.mutation.SetTmdbID(v)
	return _u
}

// SetNillableTmdbID sets the "tmdb_id" field if the given value is not nil.
func (_u *MovieWithFileUpdateOne) SetNillableTmdbID(v *int32) *MovieWithFileUpdateOne {
	if v != nil {
		_u.SetTmdbID(*v)
	}
	return _u
}

// AddTmdbID adds value to the "tmdb_id" field.
func (_u *MovieWithFileUpdateOne) AddTmdbID(v int32) *MovieWithFileUpdateOne {
	_u.mutation.AddTmdbID(v)
	return _u
}

// SetLocation sets the "location" field.
func (_u *MovieWithFileUpdateOne) SetLocation(v string) *MovieWithFileUpdateOne {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *MovieWithFileUpdateOne) SetNillableLocation(v *string) *MovieWithFileUpdateOne {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// SetMetadataAdult sets the "metadata_adult" field.
func (_u *MovieWithFileUpdateOne) SetMetadataAdult(v bool) *MovieWithFileUpdateOne {
	_u.mutation.SetMetadataAdult(v)
	return _u
}

// SetNillableMetadataAdult sets the "metadata_adult" field if the given value is not nil.
func (_u *MovieWithFileUpdateOne) SetNillableMetadataAdult(v *bool) *MovieWithFileUpdateOne {
	if v != nil {
		_u.SetMetadataAdult(*v)
	}
	return _u
}

// SetMetadataBackdropPath sets the "metadata_backdrop_path" field.
func (_u *MovieWithFileUpdateOne) SetMetadataBackdropPath(v string) *MovieWithFileUpdateOne {
	_u.mutation.SetMetadataBackdropPath(v)
	return _u
}

// SetNillableMetadataBackdropPath sets the "metadata_backdrop_path" field if the given value is not nil.
func (_u *MovieWithFileUpdateOne) SetNillableMetadataBackdropPath(v *string) *MovieWithFileUpdateOne {
	if v != nil {
		_u.SetMetadataBackdropPath(*v)
	}
	return _u
}

// SetMetadataGenres sets the "metadata_genres" field.
func (_u *MovieWithFileUpdateOne) SetMetadataGenres(v []models.TMDbGenre) *MovieWithFileUpdateOne {
	_u.mutation.SetMetadataGenres(v)
	return _u
}

// AppendMetadataGenres appends value to the "metadata_genres" field.
func (_u *MovieWithFileUpdateOne) AppendMetadataGenres(v []models.TMDbGenre) *MovieWithFileUpdateOne {
	_u.mutation.AppendMetadataGenres(v)
	return _u
}

// SetMetadataHomepage sets the "metadata_homepage" field.
func (_u *MovieWithFileUpdateOne) SetMetadataHomepage(v string) *MovieWithFileUpdateOne {
	_u.mutation.SetMetadataHomepage(v)
	return _u
}

// SetNillableMetadataHomepage sets the "metadata_homepage" field if the given value is not nil.
func (_u *MovieWithFileUpdateOne) SetNillableMetadataHomepage(v *string) *MovieWithFileUpdateOne {
	if v != nil {
		_u.SetMetadataHomepage(*v)
	}
	return _u
}

// SetMetadataImdbID sets the "metadata_imdb_id" field.
func (_u *MovieWithFileUpdateOne) SetMetadataImdbID(v string) *MovieWithFileUpdateOne {
	_u.mutation.SetMetadataImdbID(v)
	return _u
}

// SetNillableMetadataImdbID sets the "metadata_imdb_id" field if the given value is not nil.
func (_u *MovieWithFileUpdateOne) SetNillableMetadataImdbID(v *string) *MovieWithFileUpdateOne {
	if v != nil {
		_u.SetMetadataImdbID(*v)
	}
	return _u
}

// SetMetadataOriginalLanguage sets the "metadata_original_language" field.
func (_u *MovieWithFileUpdateOne) SetMetadataOriginalLanguage(v string) *MovieWithFileUpdateOne {
	_u.mutation.SetMetadataOriginalLanguage(v)
	return _u
}

// SetNillableMetadataOriginalLanguage sets the "metadata_original_language" field if the given value is not nil.
func (_u *MovieWithFileUpdateOne) SetNillableMetadataOriginalLanguage(v *string) *MovieWithFileUpdateOne {
	if v != nil {
		_u.SetMetadataOriginalLanguage(*v)
	}
	return _u
}

// SetMetadataOriginalTitle sets the "metadata_original_title" field.
func (_u *MovieWithFileUpdateOne) SetMetadataOriginalTitle(v string) *MovieWithFileUpdateOne {
	_u.mutation.SetMetadataOriginalTitle(v)
	return _u
}

// SetNillableMetadataOriginalTitle sets the "metadata_original_title" field if the given value is not nil.
func (_u *MovieWithFileUpdateOne) SetNillableMetadataOriginalTitle(v *string) *MovieWithFileUpdateOne {
	if v != nil {
		_u.SetMetadataOriginalTitle(*v)
	}
	return _u
}

// SetMetadataOverview sets the "metadata_overview" field.
func (_u *MovieWithFileUpdateOne) SetMetadataOverview(v string) *MovieWithFileUpdateOne {
	_u.mutation.SetMetadataOverview(v)
	return _u
}

// SetNillableMetadataOverview sets the "metadata_overview" field if the given value is not nil.
func (_u *MovieWithFileUpdateOne) SetNillableMetadataOverview(v *string) *MovieWithFileUpdateOne {
	if v != nil {
		_u.SetMetadataOverview(*v)
	}
	return _u
}

// SetMetadataPopularity sets the "metadata_popularity" field.
func (_u *MovieWithFileUpdateOne) SetMetadataPopularity(v float32) *MovieWithFileUpdateOne {
	_u.mutation.ResetMetadataPopularity()
	_u.mutation.SetMetadataPopularity(v)
	return _u
}

// SetNillableMetadataPopularity sets the "metadata_popularity" field if the given value is not nil.
func (_u *MovieWithFileUpdateOne) SetNillableMetadataPopularity(v *float32) *MovieWithFileUpdateOne {
	if v != nil {
		_u.SetMetadataPopularity(*v)
	}
	return _u
}

// AddMetadataPopularity adds value to the "metadata_popularity" field.
func (_u *MovieWithFileUpdateOne) AddMetadataPopularity(v float32) *MovieWithFileUpdateOne {
	_u.mutation.AddMetadataPopularity(v)
	return _u
}

// SetMetadataPosterPath sets the "metadata_poster_path" field.
func (_u *MovieWithFileUpdateOne) SetMetadataPosterPath(v string) *MovieWithFileUpdateOne {
	_u.mutation.SetMetadataPosterPath(v)
	return _u
}

// SetNillableMetadataPosterPath sets the "metadata_poster_path" field if the given value is not nil.
func (_u *MovieWithFileUpdateOne) SetNillableMetadataPosterPath(v *string) *MovieWithFileUpdateOne {
	if v != nil {
		_u.SetMetadataPosterPath(*v)
	}
	return _u
}

// SetMetadataReleaseDate sets the "metadata_release_date" field.
func (_u *MovieWithFileUpdateOne) SetMetadataReleaseDate(v string) *MovieWithFileUpdateOne {
	_u.mutation.SetMetadataReleaseDate(v)
	return _u
}

// SetNillableMetadataReleaseDate sets the "metadata_release_date" field if the given value is not nil.
func (_u *MovieWithFileUpdateOne) SetNillableMetadataReleaseDate(v *string) *MovieWithFileUpdateOne {
	if v != nil {
		_u.SetMetadataReleaseDate(*v)
	}
	return _u
}

// SetMetadataRevenue sets the "metadata_revenue" field.
func (_u *MovieWithFileUpdateOne) SetMetadataRevenue(v int64) *MovieWithFileUpdateOne {
	_u.mutation.ResetMetadataRevenue()
	_u.mutation.SetMetadataRevenue(v)
	return _u
}

// SetNillableMetadataRevenue sets the "metadata_revenue" field if the given value is not nil.
func (_u *MovieWithFileUpdateOne) SetNillableMetadataRevenue(v *int64) *MovieWithFileUpdateOne {
	if v != nil {
		_u.SetMetadataRevenue(*v)
	}
	return _u
}

// AddMetadataRevenue adds value to the "metadata_revenue" field.
func (_u *MovieWithFileUpdateOne) AddMetadataRevenue(v int64) *MovieWithFileUpdateOne {
	_u.mutation.AddMetadataRevenue(v)
	return _u
}

// SetMetadataRuntime sets the "metadata_runtime" field.
func (_u *MovieWithFileUpdateOne) SetMetadataRuntime(v int) *MovieWithFileUpdateOne {
	_u.mutation.ResetMetadataRuntime()
	_u.mutation.SetMetadataRuntime(v)
	return _u
}

// SetNillableMetadataRuntime sets the "metadata_runtime" field if the given value is not nil.
func (_u *MovieWithFileUpdateOne) SetNillableMetadataRuntime(v *int) *MovieWithFileUpdateOne {
	if v != nil {
		_u.SetMetadataRuntime(*v)
	}
	return _u
}

// AddMetadataRuntime adds value to the "metadata_runtime" field.
func (_u *MovieWithFileUpdateOne) AddMetadataRuntime(v int) *MovieWithFileUpdateOne {
	_u.mutation.AddMetadataRuntime(v)
	return _u
}

// SetMetadataSpokenLanguages sets the "metadata_spoken_languages" field.
func (_u *MovieWithFileUpdateOne) SetMetadataSpokenLanguages(v []models.TMDbSpokenLanguage) *MovieWithFileUpdateOne {
	_u.mutation.SetMetadataSpokenLanguages(v)
	return _u
}

// AppendMetadataSpokenLanguages appends value to the "metadata_spoken_languages" field.
func (_u *MovieWithFileUpdateOne) AppendMetadataSpokenLanguages(v []models.TMDbSpokenLanguage) *MovieWithFileUpdateOne {
	_u.mutation.AppendMetadataSpokenLanguages(v)
	return _u
}

// SetMetadataStatus sets the "metadata_status" field.
func (_u *MovieWithFileUpdateOne) SetMetadataStatus(v string) *MovieWithFileUpdateOne {
	_u.mutation.SetMetadataStatus(v)
	return _u
}

// SetNillableMetadataStatus sets the "metadata_status" field if the given value is not nil.
func (_u *MovieWithFileUpdateOne) SetNillableMetadataStatus(v *string) *MovieWithFileUpdateOne {
	if v != nil {
		_u.SetMetadataStatus(*v)
	}
	return _u
}

// SetMetadataTagline sets the "metadata_tagline" field.
func (_u *MovieWithFileUpdateOne) SetMetadataTagline(v string) *MovieWithFileUpdateOne {
	_u.mutation.SetMetadataTagline(v)
	return _u
}

// SetNillableMetadataTagline sets the "metadata_tagline" field if the given value is not nil.
func (_u *MovieWithFileUpdateOne) SetNillableMetadataTagline(v *string) *MovieWithFileUpdateOne {
	if v != nil {
		_u.SetMetadataTagline(*v)
	}
	return _u
}

// SetMetadataTitle sets the "metadata_title" field.
func (_u *MovieWithFileUpdateOne) SetMetadataTitle(v string) *MovieWithFileUpdateOne {
	_u.mutation.SetMetadataTitle(v)
	return _u
}

// SetNillableMetadataTitle sets the "metadata_title" field if the given value is not nil.
func (_u *MovieWithFileUpdateOne) SetNillableMetadataTitle(v *string) *MovieWithFileUpdateOne {
	if v != nil {
		_u.SetMetadataTitle(*v)
	}
	return _u
}

// SetMetadataVideo sets the "metadata_video" field.
func (_u *MovieWithFileUpdateOne) SetMetadataVideo(v bool) *MovieWithFileUpdateOne {
	_u.mutation.SetMetadataVideo(v)
	return _u
}

// SetNillableMetadataVideo sets the "metadata_video" field if the given value is not nil.
func (_u *MovieWithFileUpdateOne) SetNillableMetadataVideo(v *bool) *MovieWithFileUpdateOne {
	if v != nil {
		_u.SetMetadataVideo(*v)
	}
	return _u
}

// SetMetadataVoteAverage sets the "metadata_vote_average" field.
func (_u *MovieWithFileUpdateOne) SetMetadataVoteAverage(v float32) *MovieWithFileUpdateOne {
	_u.mutation.ResetMetadataVoteAverage()
	_u.mutation.SetMetadataVoteAverage(v)
	return _u
}

// SetNillableMetadataVoteAverage sets the "metadata_vote_average" field if the given value is not nil.
func (_u *MovieWithFileUpdateOne) SetNillableMetadataVoteAverage(v *float32) *MovieWithFileUpdateOne {
	if v != nil {
		_u.SetMetadataVoteAverage(*v)
	}
	return _u
}

// AddMetadataVoteAverage adds value to the "metadata_vote_average" field.
func (_u *MovieWithFileUpdateOne) AddMetadataVoteAverage(v float32) *MovieWithFileUpdateOne {
	_u.mutation.AddMetadataVoteAverage(v)
	return _u
}

// SetMetadataVoteCount sets the "metadata_vote_count" field.
func (_u *MovieWithFileUpdateOne) SetMetadataVoteCount(v int64) *MovieWithFileUpdateOne {
	_u.mutation.ResetMetadataVoteCount()
	_u.mutation.SetMetadataVoteCount(v)
	return _u
}

// SetNillableMetadataVoteCount sets the "metadata_vote_count" field if the given value is not nil.
func (_u *MovieWithFileUpdateOne) SetNillableMetadataVoteCount(v *int64) *MovieWithFileUpdateOne {
	if v != nil {
		_u.SetMetadataVoteCount(*v)
	}
	return _u
}

// AddMetadataVoteCount adds value to the "metadata_vote_count" field.
func (_u *MovieWithFileUpdateOne) AddMetadataVoteCount(v int64) *MovieWithFileUpdateOne {
	_u.mutation.AddMetadataVoteCount(v)
	return _u
}

// SetCollectionID sets the "collection_id" field.
func (_u *MovieWithFileUpdateOne) SetCollectionID(v int64) *MovieWithFileUpdateOne {
	_u.mutation.ResetCollectionID()
	_u.mutation.SetCollectionID(v)
	return _u
}

// SetNillableCollectionID sets the "collection_id" field if the given value is not nil.
func (_u *MovieWithFileUpdateOne) SetNillableCollectionID(v *int64) *MovieWithFileUpdateOne {
	if v != nil {
		_u.SetCollectionID(*v)
	}
	return _u
}

// AddCollectionID adds value to the "collection_id" field.
func (_u *MovieWithFileUpdateOne) AddCollectionID(v int64) *MovieWithFileUpdateOne {
	_u.mutation.AddCollectionID(v)
	return _u
}

// SetCollectionName sets the "collection_name" field.
func (_u *MovieWithFileUpdateOne) SetCollectionName(v string) *MovieWithFileUpdateOne {
	_u.mutation.SetCollectionName(v)
	return _u
}

// SetNillableCollectionName sets the "collection_name" field if the given value is not nil.
func (_u *MovieWithFileUpdateOne) SetNillableCollectionName(v *string) *MovieWithFileUpdateOne {
	if v != nil {
		_u.SetCollectionName(*v)
	}
	return _u
}

// SetCollectionPosterPath sets the "collection_poster_path" field.
func (_u *MovieWithFileUpdateOne) SetCollectionPosterPath(v string) *MovieWithFileUpdateOne {
	_u.mutation.SetCollectionPosterPath(v)
	return _u
}

// SetNillableCollectionPosterPath sets the "collection_poster_path" field if the given value is not nil.
func (_u *MovieWithFileUpdateOne) SetNillableCollectionPosterPath(v *string) *MovieWithFileUpdateOne {
	if v != nil {
		_u.SetCollectionPosterPath(*v)
	}
	return _u
}

// SetCollectionBackdropPath sets the "collection_backdrop_path" field.
func (_u *MovieWithFileUpdateOne) SetCollectionBackdropPath(v string) *MovieWithFileUpdateOne {
	_u.mutation.SetCollectionBackdropPath(v)
	return _u
}

// SetNillableCollectionBackdropPath sets the "collection_backdrop_path" field if the given value is not nil.
func (_u *MovieWithFileUpdateOne) SetNillableCollectionBackdropPath(v *string) *MovieWithFileUpdateOne {
	if v != nil {
		_u.SetCollectionBackdropPath(*v)
	}
	return _u
}

// Mutation returns the MovieWithFileMutation object of the builder.
func (_u *MovieWithFileUpdateOne) Mutation() *MovieWithFileMutation {
	return _u.mutation
}

// Where appends a list predicates to the MovieWithFileUpdate builder.
func (_u *MovieWithFileUpdateOne) Where(ps ...predicate.MovieWithFile) *MovieWithFileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MovieWithFileUpdateOne) Select(field string, fields ...string) *MovieWithFileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MovieWithFile entity.
func (_u *MovieWithFileUpdateOne) Save(ctx context.Context) (*MovieWithFile, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MovieWithFileUpdateOne) SaveX(ctx context.Context) *MovieWithFile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MovieWithFileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MovieWithFileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MovieWithFileUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := moviewithfile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *MovieWithFileUpdateOne) sqlSave(ctx context.Context) (_node *MovieWithFile, err error) {
	_spec := sqlgraph.NewUpdateSpec(moviewithfile.Table, moviewithfile.Columns, sqlgraph.NewFieldSpec(moviewithfile.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MovieWithFile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, moviewithfile.FieldID)
		for _, f := range fields {
			if !moviewithfile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != moviewithfile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(moviewithfile.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(moviewithfile.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(moviewithfile.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.TmdbID(); ok {
		_spec.SetField(moviewithfile.FieldTmdbID, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedTmdbID(); ok {
		_spec.AddField(moviewithfile.FieldTmdbID, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(moviewithfile.FieldLocation, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataAdult(); ok {
		_spec.SetField(moviewithfile.FieldMetadataAdult, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MetadataBackdropPath(); ok {
		_spec.SetField(moviewithfile.FieldMetadataBackdropPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataGenres(); ok {
		_spec.SetField(moviewithfile.FieldMetadataGenres, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMetadataGenres(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, moviewithfile.FieldMetadataGenres, value)
		})
	}
	if value, ok := _u.mutation.MetadataHomepage(); ok {
		_spec.SetField(moviewithfile.FieldMetadataHomepage, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataImdbID(); ok {
		_spec.SetField(moviewithfile.FieldMetadataImdbID, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataOriginalLanguage(); ok {
		_spec.SetField(moviewithfile.FieldMetadataOriginalLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataOriginalTitle(); ok {
		_spec.SetField(moviewithfile.FieldMetadataOriginalTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataOverview(); ok {
		_spec.SetField(moviewithfile.FieldMetadataOverview, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataPopularity(); ok {
		_spec.SetField(moviewithfile.FieldMetadataPopularity, field.TypeFloat32, value)
	}
	if value, ok := _u.mutation.AddedMetadataPopularity(); ok {
		_spec.AddField(moviewithfile.FieldMetadataPopularity, field.TypeFloat32, value)
	}
	if value, ok := _u.mutation.MetadataPosterPath(); ok {
		_spec.SetField(moviewithfile.FieldMetadataPosterPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataReleaseDate(); ok {
		_spec.SetField(moviewithfile.FieldMetadataReleaseDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataRevenue(); ok {
		_spec.SetField(moviewithfile.FieldMetadataRevenue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMetadataRevenue(); ok {
		_spec.AddField(moviewithfile.FieldMetadataRevenue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MetadataRuntime(); ok {
		_spec.SetField(moviewithfile.FieldMetadataRuntime, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMetadataRuntime(); ok {
		_spec.AddField(moviewithfile.FieldMetadataRuntime, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MetadataSpokenLanguages(); ok {
		_spec.SetField(moviewithfile.FieldMetadataSpokenLanguages, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMetadataSpokenLanguages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, moviewithfile.FieldMetadataSpokenLanguages, value)
		})
	}
	if value, ok := _u.mutation.MetadataStatus(); ok {
		_spec.SetField(moviewithfile.FieldMetadataStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataTagline(); ok {
		_spec.SetField(moviewithfile.FieldMetadataTagline, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataTitle(); ok {
		_spec.SetField(moviewithfile.FieldMetadataTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataVideo(); ok {
		_spec.SetField(moviewithfile.FieldMetadataVideo, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MetadataVoteAverage(); ok {
		_spec.SetField(moviewithfile.FieldMetadataVoteAverage, field.TypeFloat32, value)
	}
	if value, ok := _u.mutation.AddedMetadataVoteAverage(); ok {
		_spec.AddField(moviewithfile.FieldMetadataVoteAverage, field.TypeFloat32, value)
	}
	if value, ok := _u.mutation.MetadataVoteCount(); ok {
		_spec.SetField(moviewithfile.FieldMetadataVoteCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMetadataVoteCount(); ok {
		_spec.AddField(moviewithfile.FieldMetadataVoteCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CollectionID(); ok {
		_spec.SetField(moviewithfile.FieldCollectionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCollectionID(); ok {
		_spec.AddField(moviewithfile.FieldCollectionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CollectionName(); ok {
		_spec.SetField(moviewithfile.FieldCollectionName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CollectionPosterPath(); ok {
		_spec.SetField(moviewithfile.FieldCollectionPosterPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.CollectionBackdropPath(); ok {
		_spec.SetField(moviewithfile.FieldCollectionBackdropPath, field.TypeString, value)
	}
	_node = &MovieWithFile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{moviewithfile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
