// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lunarr-app/lunarr-go/internal/ent/moviewithfile"
	"github.com/lunarr-app/lunarr-go/internal/models"
)

// MovieWithFileCreate is the builder for creating a MovieWithFile entity.
type MovieWithFileCreate struct {
	config
	mutation *MovieWithFileMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *MovieWithFileCreate) SetCreatedAt(v time.Time) *MovieWithFileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MovieWithFileCreate) SetNillableCreatedAt(v *time.Time) *MovieWithFileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MovieWithFileCreate) SetUpdatedAt(v time.Time) *MovieWithFileCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MovieWithFileCreate) SetNillableUpdatedAt(v *time.Time) *MovieWithFileCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *MovieWithFileCreate) SetDeletedAt(v time.Time) *MovieWithFileCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *MovieWithFileCreate) SetNillableDeletedAt(v *time.Time) *MovieWithFileCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetTmdbID sets the "tmdb_id" field.
func (_c *MovieWithFileCreate) SetTmdbID(v int32) *MovieWithFileCreate {
	_c.mutation.SetTmdbID(v)
	return _c
}

// SetNillableTmdbID sets the "tmdb_id" field if the given value is not nil.
func (_c *MovieWithFileCreate) SetNillableTmdbID(v *int32) *MovieWithFileCreate {
	if v != nil {
		_c.SetTmdbID(*v)
	}
	return _c
}

// SetLocation sets the "location" field.
func (_c *MovieWithFileCreate) SetLocation(v string) *MovieWithFileCreate {
	_c.mutation.SetLocation(v)
	return _c
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_c *MovieWithFileCreate) SetNillableLocation(v *string) *MovieWithFileCreate {
	if v != nil {
		_c.SetLocation(*v)
	}
	return _c
}

// SetMetadataAdult sets the "metadata_adult" field.
func (_c *MovieWithFileCreate) SetMetadataAdult(v bool) *MovieWithFileCreate {
	_c.mutation.SetMetadataAdult(v)
	return _c
}

// SetNillableMetadataAdult sets the "metadata_adult" field if the given value is not nil.
func (_c *MovieWithFileCreate) SetNillableMetadataAdult(v *bool) *MovieWithFileCreate {
	if v != nil {
		_c.SetMetadataAdult(*v)
	}
	return _c
}

// SetMetadataBackdropPath sets the "metadata_backdrop_path" field.
func (_c *MovieWithFileCreate) SetMetadataBackdropPath(v string) *MovieWithFileCreate {
	_c.mutation.SetMetadataBackdropPath(v)
	return _c
}

// SetNillableMetadataBackdropPath sets the "metadata_backdrop_path" field if the given value is not nil.
func (_c *MovieWithFileCreate) SetNillableMetadataBackdropPath(v *string) *MovieWithFileCreate {
	if v != nil {
		_c.SetMetadataBackdropPath(*v)
	}
	return _c
}

// SetMetadataGenres sets the "metadata_genres" field.
func (_c *MovieWithFileCreate) SetMetadataGenres(v []models.TMDbGenre) *MovieWithFileCreate {
	_c.mutation.SetMetadataGenres(v)
	return _c
}

// SetMetadataHomepage sets the "metadata_homepage" field.
func (_c *MovieWithFileCreate) SetMetadataHomepage(v string) *MovieWithFileCreate {
	_c.mutation.SetMetadataHomepage(v)
	return _c
}

// SetNillableMetadataHomepage sets the "metadata_homepage" field if the given value is not nil.
func (_c *MovieWithFileCreate) SetNillableMetadataHomepage(v *string) *MovieWithFileCreate {
	if v != nil {
		_c.SetMetadataHomepage(*v)
	}
	return _c
}

// SetMetadataImdbID sets the "metadata_imdb_id" field.
func (_c *MovieWithFileCreate) SetMetadataImdbID(v string) *MovieWithFileCreate {
	_c.mutation.SetMetadataImdbID(v)
	return _c
}

// SetNillableMetadataImdbID sets the "metadata_imdb_id" field if the given value is not nil.
func (_c *MovieWithFileCreate) SetNillableMetadataImdbID(v *string) *MovieWithFileCreate {
	if v != nil {
		_c.SetMetadataImdbID(*v)
	}
	return _c
}

// SetMetadataOriginalLanguage sets the "metadata_original_language" field.
func (_c *MovieWithFileCreate) SetMetadataOriginalLanguage(v string) *MovieWithFileCreate {
	_c.mutation.SetMetadataOriginalLanguage(v)
	return _c
}

// SetNillableMetadataOriginalLanguage sets the "metadata_original_language" field if the given value is not nil.
func (_c *MovieWithFileCreate) SetNillableMetadataOriginalLanguage(v *string) *MovieWithFileCreate {
	if v != nil {
		_c.SetMetadataOriginalLanguage(*v)
	}
	return _c
}

// SetMetadataOriginalTitle sets the "metadata_original_title" field.
func (_c *MovieWithFileCreate) SetMetadataOriginalTitle(v string) *MovieWithFileCreate {
	_c.mutation.SetMetadataOriginalTitle(v)
	return _c
}

// SetNillableMetadataOriginalTitle sets the "metadata_original_title" field if the given value is not nil.
func (_c *MovieWithFileCreate) SetNillableMetadataOriginalTitle(v *string) *MovieWithFileCreate {
	if v != nil {
		_c.SetMetadataOriginalTitle(*v)
	}
	return _c
}

// SetMetadataOverview sets the "metadata_overview" field.
func (_c *MovieWithFileCreate) SetMetadataOverview(v string) *MovieWithFileCreate {
	_c.mutation.SetMetadataOverview(v)
	return _c
}

// SetNillableMetadataOverview sets the "metadata_overview" field if the given value is not nil.
func (_c *MovieWithFileCreate) SetNillableMetadataOverview(v *string) *MovieWithFileCreate {
	if v != nil {
		_c.SetMetadataOverview(*v)
	}
	return _c
}

// SetMetadataPopularity sets the "metadata_popularity" field.
func (_c *MovieWithFileCreate) SetMetadataPopularity(v float32) *MovieWithFileCreate {
	_c.mutation.SetMetadataPopularity(v)
	return _c
}

// SetNillableMetadataPopularity sets the "metadata_popularity" field if the given value is not nil.
func (_c *MovieWithFileCreate) SetNillableMetadataPopularity(v *float32) *MovieWithFileCreate {
	if v != nil {
		_c.SetMetadataPopularity(*v)
	}
	return _c
}

// SetMetadataPosterPath sets the "metadata_poster_path" field.
func (_c *MovieWithFileCreate) SetMetadataPosterPath(v string) *MovieWithFileCreate {
	_c.mutation.SetMetadataPosterPath(v)
	return _c
}

// SetNillableMetadataPosterPath sets the "metadata_poster_path" field if the given value is not nil.
func (_c *MovieWithFileCreate) SetNillableMetadataPosterPath(v *string) *MovieWithFileCreate {
	if v != nil {
		_c.SetMetadataPosterPath(*v)
	}
	return _c
}

// SetMetadataReleaseDate sets the "metadata_release_date" field.
func (_c *MovieWithFileCreate) SetMetadataReleaseDate(v string) *MovieWithFileCreate {
	_c.mutation.SetMetadataReleaseDate(v)
	return _c
}

// SetNillableMetadataReleaseDate sets the "metadata_release_date" field if the given value is not nil.
func (_c *MovieWithFileCreate) SetNillableMetadataReleaseDate(v *string) *MovieWithFileCreate {
	if v != nil {
		_c.SetMetadataReleaseDate(*v)
	}
	return _c
}

// SetMetadataRevenue sets the "metadata_revenue" field.
func (_c *MovieWithFileCreate) SetMetadataRevenue(v int64) *MovieWithFileCreate {
	_c.mutation.SetMetadataRevenue(v)
	return _c
}

// SetNillableMetadataRevenue sets the "metadata_revenue" field if the given value is not nil.
func (_c *MovieWithFileCreate) SetNillableMetadataRevenue(v *int64) *MovieWithFileCreate {
	if v != nil {
		_c.SetMetadataRevenue(*v)
	}
	return _c
}

// SetMetadataRuntime sets the "metadata_runtime" field.
func (_c *MovieWithFileCreate) SetMetadataRuntime(v int) *MovieWithFileCreate {
	_c.mutation.SetMetadataRuntime(v)
	return _c
}

// SetNillableMetadataRuntime sets the "metadata_runtime" field if the given value is not nil.
func (_c *MovieWithFileCreate) SetNillableMetadataRuntime(v *int) *MovieWithFileCreate {
	if v != nil {
		_c.SetMetadataRuntime(*v)
	}
	return _c
}

// SetMetadataSpokenLanguages sets the "metadata_spoken_languages" field.
func (_c *MovieWithFileCreate) SetMetadataSpokenLanguages(v []models.TMDbSpokenLanguage) *MovieWithFileCreate {
	_c.mutation.SetMetadataSpokenLanguages(v)
	return _c
}

// SetMetadataStatus sets the "metadata_status" field.
func (_c *MovieWithFileCreate) SetMetadataStatus(v string) *MovieWithFileCreate {
	_c.mutation.SetMetadataStatus(v)
	return _c
}

// SetNillableMetadataStatus sets the "metadata_status" field if the given value is not nil.
func (_c *MovieWithFileCreate) SetNillableMetadataStatus(v *string) *MovieWithFileCreate {
	if v != nil {
		_c.SetMetadataStatus(*v)
	}
	return _c
}

// SetMetadataTagline sets the "metadata_tagline" field.
func (_c *MovieWithFileCreate) SetMetadataTagline(v string) *MovieWithFileCreate {
	_c.mutation.SetMetadataTagline(v)
	return _c
}

// SetNillableMetadataTagline sets the "metadata_tagline" field if the given value is not nil.
func (_c *MovieWithFileCreate) SetNillableMetadataTagline(v *string) *MovieWithFileCreate {
	if v != nil {
		_c.SetMetadataTagline(*v)
	}
	return _c
}

// SetMetadataTitle sets the "metadata_title" field.
func (_c *MovieWithFileCreate) SetMetadataTitle(v string) *MovieWithFileCreate {
	_c.mutation.SetMetadataTitle(v)
	return _c
}

// SetNillableMetadataTitle sets the "metadata_title" field if the given value is not nil.
func (_c *MovieWithFileCreate) SetNillableMetadataTitle(v *string) *MovieWithFileCreate {
	if v != nil {
		_c.SetMetadataTitle(*v)
	}
	return _c
}

// SetMetadataVideo sets the "metadata_video" field.
func (_c *MovieWithFileCreate) SetMetadataVideo(v bool) *MovieWithFileCreate {
	_c.mutation.SetMetadataVideo(v)
	return _c
}

// SetNillableMetadataVideo sets the "metadata_video" field if the given value is not nil.
func (_c *MovieWithFileCreate) SetNillableMetadataVideo(v *bool) *MovieWithFileCreate {
	if v != nil {
		_c.SetMetadataVideo(*v)
	}
	return _c
}

// SetMetadataVoteAverage sets the "metadata_vote_average" field.
func (_c *MovieWithFileCreate) SetMetadataVoteAverage(v float32) *MovieWithFileCreate {
	_c.mutation.SetMetadataVoteAverage(v)
	return _c
}

// SetNillableMetadataVoteAverage sets the "metadata_vote_average" field if the given value is not nil.
func (_c *MovieWithFileCreate) SetNillableMetadataVoteAverage(v *float32) *MovieWithFileCreate {
	if v != nil {
		_c.SetMetadataVoteAverage(*v)
	}
	return _c
}

// SetMetadataVoteCount sets the "metadata_vote_count" field.
func (_c *MovieWithFileCreate) SetMetadataVoteCount(v int64) *MovieWithFileCreate {
	_c.mutation.SetMetadataVoteCount(v)
	return _c
}

// SetNillableMetadataVoteCount sets the "metadata_vote_count" field if the given value is not nil.
func (_c *MovieWithFileCreate) SetNillableMetadataVoteCount(v *int64) *MovieWithFileCreate {
	if v != nil {
		_c.SetMetadataVoteCount(*v)
	}
	return _c
}

// SetCollectionID sets the "collection_id" field.
func (_c *MovieWithFileCreate) SetCollectionID(v int64) *MovieWithFileCreate {
	_c.mutation.SetCollectionID(v)
	return _c
}

// SetNillableCollectionID sets the "collection_id" field if the given value is not nil.
func (_c *MovieWithFileCreate) SetNillableCollectionID(v *int64) *MovieWithFileCreate {
	if v != nil {
		_c.SetCollectionID(*v)
	}
	return _c
}

// SetCollectionName sets the "collection_name" field.
func (_c *MovieWithFileCreate) SetCollectionName(v string) *MovieWithFileCreate {
	_c.mutation.SetCollectionName(v)
	return _c
}

// SetNillableCollectionName sets the "collection_name" field if the given value is not nil.
func (_c *MovieWithFileCreate) SetNillableCollectionName(v *string) *MovieWithFileCreate {
	if v != nil {
		_c.SetCollectionName(*v)
	}
	return _c
}

// SetCollectionPosterPath sets the "collection_poster_path" field.
func (_c *MovieWithFileCreate) SetCollectionPosterPath(v string) *MovieWithFileCreate {
	_c.mutation.SetCollectionPosterPath(v)
	return _c
}

// SetNillableCollectionPosterPath sets the "collection_poster_path" field if the given value is not nil.
func (_c *MovieWithFileCreate) SetNillableCollectionPosterPath(v *string) *MovieWithFileCreate {
	if v != nil {
		_c.SetCollectionPosterPath(*v)
	}
	return _c
}

// SetCollectionBackdropPath sets the "collection_backdrop_path" field.
func (_c *MovieWithFileCreate) SetCollectionBackdropPath(v string) *MovieWithFileCreate {
	_c.mutation.SetCollectionBackdropPath(v)
	return _c
}

// SetNillableCollectionBackdropPath sets the "collection_backdrop_path" field if the given value is not nil.
func (_c *MovieWithFileCreate) SetNillableCollectionBackdropPath(v *string) *MovieWithFileCreate {
	if v != nil {
		_c.SetCollectionBackdropPath(*v)
	}
	return _c
}

// Mutation returns the MovieWithFileMutation object of the builder.
func (_c *MovieWithFileCreate) Mutation() *MovieWithFileMutation {
	return _c.mutation
}

// Save creates the MovieWithFile in the database.
func (_c *MovieWithFileCreate) Save(ctx context.Context) (*MovieWithFile, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MovieWithFileCreate) SaveX(ctx context.Context) *MovieWithFile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MovieWithFileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MovieWithFileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MovieWithFileCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := moviewithfile.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := moviewithfile.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.TmdbID(); !ok {
		v := moviewithfile.DefaultTmdbID
		_c.mutation.SetTmdbID(v)
	}
	if _, ok := _c.mutation.Location(); !ok {
		v := moviewithfile.DefaultLocation
		_c.mutation.SetLocation(v)
	}
	if _, ok := _c.mutation.MetadataAdult(); !ok {
		v := moviewithfile.DefaultMetadataAdult
		_c.mutation.SetMetadataAdult(v)
	}
	if _, ok := _c.mutation.MetadataBackdropPath(); !ok {
		v := moviewithfile.DefaultMetadataBackdropPath
		_c.mutation.SetMetadataBackdropPath(v)
	}
	if _, ok := _c.mutation.MetadataGenres(); !ok {
		v := moviewithfile.DefaultMetadataGenres
		_c.mutation.SetMetadataGenres(v)
	}
	if _, ok := _c.mutation.MetadataHomepage(); !ok {
		v := moviewithfile.DefaultMetadataHomepage
		_c.mutation.SetMetadataHomepage(v)
	}
	if _, ok := _c.mutation.MetadataImdbID(); !ok {
		v := moviewithfile.DefaultMetadataImdbID
		_c.mutation.SetMetadataImdbID(v)
	}
	if _, ok := _c.mutation.MetadataOriginalLanguage(); !ok {
		v := moviewithfile.DefaultMetadataOriginalLanguage
		_c.mutation.SetMetadataOriginalLanguage(v)
	}
	if _, ok := _c.mutation.MetadataOriginalTitle(); !ok {
		v := moviewithfile.DefaultMetadataOriginalTitle
		_c.mutation.SetMetadataOriginalTitle(v)
	}
	if _, ok := _c.mutation.MetadataOverview(); !ok {
		v := moviewithfile.DefaultMetadataOverview
		_c.mutation.SetMetadataOverview(v)
	}
	if _, ok := _c.mutation.MetadataPopularity(); !ok {
		v := moviewithfile.DefaultMetadataPopularity
		_c.mutation.SetMetadataPopularity(v)
	}
	if _, ok := _c.mutation.MetadataPosterPath(); !ok {
		v := moviewithfile.DefaultMetadataPosterPath
		_c.mutation.SetMetadataPosterPath(v)
	}
	if _, ok := _c.mutation.MetadataReleaseDate(); !ok {
		v := moviewithfile.DefaultMetadataReleaseDate
		_c.mutation.SetMetadataReleaseDate(v)
	}
	if _, ok := _c.mutation.MetadataRevenue(); !ok {
		v := moviewithfile.DefaultMetadataRevenue
		_c.mutation.SetMetadataRevenue(v)
	}
	if _, ok := _c.mutation.MetadataRuntime(); !ok {
		v := moviewithfile.DefaultMetadataRuntime
		_c.mutation.SetMetadataRuntime(v)
	}
	if _, ok := _c.mutation.MetadataSpokenLanguages(); !ok {
		v := moviewithfile.DefaultMetadataSpokenLanguages
		_c.mutation.SetMetadataSpokenLanguages(v)
	}
	if _, ok := _c.mutation.MetadataStatus(); !ok {
		v := moviewithfile.DefaultMetadataStatus
		_c.mutation.SetMetadataStatus(v)
	}
	if _, ok := _c.mutation.MetadataTagline(); !ok {
		v := moviewithfile.DefaultMetadataTagline
		_c.mutation.SetMetadataTagline(v)
	}
	if _, ok := _c.mutation.MetadataTitle(); !ok {
		v := moviewithfile.DefaultMetadataTitle
		_c.mutation.SetMetadataTitle(v)
	}
	if _, ok := _c.mutation.MetadataVideo(); !ok {
		v := moviewithfile.DefaultMetadataVideo
		_c.mutation.SetMetadataVideo(v)
	}
	if _, ok := _c.mutation.MetadataVoteAverage(); !ok {
		v := moviewithfile.DefaultMetadataVoteAverage
		_c.mutation.SetMetadataVoteAverage(v)
	}
	if _, ok := _c.mutation.MetadataVoteCount(); !ok {
		v := moviewithfile.DefaultMetadataVoteCount
		_c.mutation.SetMetadataVoteCount(v)
	}
	if _, ok := _c.mutation.CollectionID(); !ok {
		v := moviewithfile.DefaultCollectionID
		_c.mutation.SetCollectionID(v)
	}
	if _, ok := _c.mutation.CollectionName(); !ok {
		v := moviewithfile.DefaultCollectionName
		_c.mutation.SetCollectionName(v)
	}
	if _, ok := _c.mutation.CollectionPosterPath(); !ok {
		v := moviewithfile.DefaultCollectionPosterPath
		_c.mutation.SetCollectionPosterPath(v)
	}
	if _, ok := _c.mutation.CollectionBackdropPath(); !ok {
		v := moviewithfile.DefaultCollectionBackdropPath
		_c.mutation.SetCollectionBackdropPath(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MovieWithFileCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MovieWithFile.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MovieWithFile.updated_at"`)}
	}
	if _, ok := _c.mutation.TmdbID(); !ok {
		return &ValidationError{Name: "tmdb_id", err: errors.New(`ent: missing required field "MovieWithFile.tmdb_id"`)}
	}
	if _, ok := _c.mutation.Location(); !ok {
		return &ValidationError{Name: "location", err: errors.New(`ent: missing required field "MovieWithFile.location"`)}
	}
	if _, ok := _c.mutation.MetadataAdult(); !ok {
		return &ValidationError{Name: "metadata_adult", err: errors.New(`ent: missing required field "MovieWithFile.metadata_adult"`)}
	}
	if _, ok := _c.mutation.MetadataBackdropPath(); !ok {
		return &ValidationError{Name: "metadata_backdrop_path", err: errors.New(`ent: missing required field "MovieWithFile.metadata_backdrop_path"`)}
	}
	if _, ok := _c.mutation.MetadataGenres(); !ok {
		return &ValidationError{Name: "metadata_genres", err: errors.New(`ent: missing required field "MovieWithFile.metadata_genres"`)}
	}
	if _, ok := _c.mutation.MetadataHomepage(); !ok {
		return &ValidationError{Name: "metadata_homepage", err: errors.New(`ent: missing required field "MovieWithFile.metadata_homepage"`)}
	}
	if _, ok := _c.mutation.MetadataImdbID(); !ok {
		return &ValidationError{Name: "metadata_imdb_id", err: errors.New(`ent: missing required field "MovieWithFile.metadata_imdb_id"`)}
	}
	if _, ok := _c.mutation.MetadataOriginalLanguage(); !ok {
		return &ValidationError{Name: "metadata_original_language", err: errors.New(`ent: missing required field "MovieWithFile.metadata_original_language"`)}
	}
	if _, ok := _c.mutation.MetadataOriginalTitle(); !ok {
		return &ValidationError{Name: "metadata_original_title", err: errors.New(`ent: missing required field "MovieWithFile.metadata_original_title"`)}
	}
	if _, ok := _c.mutation.MetadataOverview(); !ok {
		return &ValidationError{Name: "metadata_overview", err: errors.New(`ent: missing required field "MovieWithFile.metadata_overview"`)}
	}
	if _, ok := _c.mutation.MetadataPopularity(); !ok {
		return &ValidationError{Name: "metadata_popularity", err: errors.New(`ent: missing required field "MovieWithFile.metadata_popularity"`)}
	}
	if _, ok := _c.mutation.MetadataPosterPath(); !ok {
		return &ValidationError{Name: "metadata_poster_path", err: errors.New(`ent: missing required field "MovieWithFile.metadata_poster_path"`)}
	}
	if _, ok := _c.mutation.MetadataReleaseDate(); !ok {
		return &ValidationError{Name: "metadata_release_date", err: errors.New(`ent: missing required field "MovieWithFile.metadata_release_date"`)}
	}
	if _, ok := _c.mutation.MetadataRevenue(); !ok {
		return &ValidationError{Name: "metadata_revenue", err: errors.New(`ent: missing required field "MovieWithFile.metadata_revenue"`)}
	}
	if _, ok := _c.mutation.MetadataRuntime(); !ok {
		return &ValidationError{Name: "metadata_runtime", err: errors.New(`ent: missing required field "MovieWithFile.metadata_runtime"`)}
	}
	if _, ok := _c.mutation.MetadataSpokenLanguages(); !ok {
		return &ValidationError{Name: "metadata_spoken_languages", err: errors.New(`ent: missing required field "MovieWithFile.metadata_spoken_languages"`)}
	}
	if _, ok := _c.mutation.MetadataStatus(); !ok {
		return &ValidationError{Name: "metadata_status", err: errors.New(`ent: missing required field "MovieWithFile.metadata_status"`)}
	}
	if _, ok := _c.mutation.MetadataTagline(); !ok {
		return &ValidationError{Name: "metadata_tagline", err: errors.New(`ent: missing required field "MovieWithFile.metadata_tagline"`)}
	}
	if _, ok := _c.mutation.MetadataTitle(); !ok {
		return &ValidationError{Name: "metadata_title", err: errors.New(`ent: missing required field "MovieWithFile.metadata_title"`)}
	}
	if _, ok := _c.mutation.MetadataVideo(); !ok {
		return &ValidationError{Name: "metadata_video", err: errors.New(`ent: missing required field "MovieWithFile.metadata_video"`)}
	}
	if _, ok := _c.mutation.MetadataVoteAverage(); !ok {
		return &ValidationError{Name: "metadata_vote_average", err: errors.New(`ent: missing required field "MovieWithFile.metadata_vote_average"`)}
	}
	if _, ok := _c.mutation.MetadataVoteCount(); !ok {
		return &ValidationError{Name: "metadata_vote_count", err: errors.New(`ent: missing required field "MovieWithFile.metadata_vote_count"`)}
	}
	if _, ok := _c.mutation.CollectionID(); !ok {
		return &ValidationError{Name: "collection_id", err: errors.New(`ent: missing required field "MovieWithFile.collection_id"`)}
	}
	if _, ok := _c.mutation.CollectionName(); !ok {
		return &ValidationError{Name: "collection_name", err: errors.New(`ent: missing required field "MovieWithFile.collection_name"`)}
	}
	if _, ok := _c.mutation.CollectionPosterPath(); !ok {
		return &ValidationError{Name: "collection_poster_path", err: errors.New(`ent: missing required field "MovieWithFile.collection_poster_path"`)}
	}
	if _, ok := _c.mutation.CollectionBackdropPath(); !ok {
		return &ValidationError{Name: "collection_backdrop_path", err: errors.New(`ent: missing required field "MovieWithFile.collection_backdrop_path"`)}
	}
	return nil
}

func (_c *MovieWithFileCreate) sqlSave(ctx context.Context) (*MovieWithFile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MovieWithFileCreate) createSpec() (*MovieWithFile, *sqlgraph.CreateSpec) {
	var (
		_node = &MovieWithFile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(moviewithfile.Table, sqlgraph.NewFieldSpec(moviewithfile.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(moviewithfile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(moviewithfile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(moviewithfile.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.TmdbID(); ok {
		_spec.SetField(moviewithfile.FieldTmdbID, field.TypeInt32, value)
		_node.TmdbID = value
	}
	if value, ok := _c.mutation.Location(); ok {
		_spec.SetField(moviewithfile.FieldLocation, field.TypeString, value)
		_node.Location = value
	}
	if value, ok := _c.mutation.MetadataAdult(); ok {
		_spec.SetField(moviewithfile.FieldMetadataAdult, field.TypeBool, value)
		_node.MetadataAdult = value
	}
	if value, ok := _c.mutation.MetadataBackdropPath(); ok {
		_spec.SetField(moviewithfile.FieldMetadataBackdropPath, field.TypeString, value)
		_node.MetadataBackdropPath = value
	}
	if value, ok := _c.mutation.MetadataGenres(); ok {
		_spec.SetField(moviewithfile.FieldMetadataGenres, field.TypeJSON, value)
		_node.MetadataGenres = value
	}
	if value, ok := _c.mutation.MetadataHomepage(); ok {
		_spec.SetField(moviewithfile.FieldMetadataHomepage, field.TypeString, value)
		_node.MetadataHomepage = value
	}
	if value, ok := _c.mutation.MetadataImdbID(); ok {
		_spec.SetField(moviewithfile.FieldMetadataImdbID, field.TypeString, value)
		_node.MetadataImdbID = value
	}
	if value, ok := _c.mutation.MetadataOriginalLanguage(); ok {
		_spec.SetField(moviewithfile.FieldMetadataOriginalLanguage, field.TypeString, value)
		_node.MetadataOriginalLanguage = value
	}
	if value, ok := _c.mutation.MetadataOriginalTitle(); ok {
		_spec.SetField(moviewithfile.FieldMetadataOriginalTitle, field.TypeString, value)
		_node.MetadataOriginalTitle = value
	}
	if value, ok := _c.mutation.MetadataOverview(); ok {
		_spec.SetField(moviewithfile.FieldMetadataOverview, field.TypeString, value)
		_node.MetadataOverview = value
	}
	if value, ok := _c.mutation.MetadataPopularity(); ok {
		_spec.SetField(moviewithfile.FieldMetadataPopularity, field.TypeFloat32, value)
		_node.MetadataPopularity = value
	}
	if value, ok := _c.mutation.MetadataPosterPath(); ok {
		_spec.SetField(moviewithfile.FieldMetadataPosterPath, field.TypeString, value)
		_node.MetadataPosterPath = value
	}
	if value, ok := _c.mutation.MetadataReleaseDate(); ok {
		_spec.SetField(moviewithfile.FieldMetadataReleaseDate, field.TypeString, value)
		_node.MetadataReleaseDate = value
	}
	if value, ok := _c.mutation.MetadataRevenue(); ok {
		_spec.SetField(moviewithfile.FieldMetadataRevenue, field.TypeInt64, value)
		_node.MetadataRevenue = value
	}
	if value, ok := _c.mutation.MetadataRuntime(); ok {
		_spec.SetField(moviewithfile.FieldMetadataRuntime, field.TypeInt, value)
		_node.MetadataRuntime = value
	}
	if value, ok := _c.mutation.MetadataSpokenLanguages(); ok {
		_spec.SetField(moviewithfile.FieldMetadataSpokenLanguages, field.TypeJSON, value)
		_node.MetadataSpokenLanguages = value
	}
	if value, ok := _c.mutation.MetadataStatus(); ok {
		_spec.SetField(moviewithfile.FieldMetadataStatus, field.TypeString, value)
		_node.MetadataStatus = value
	}
	if value, ok := _c.mutation.MetadataTagline(); ok {
		_spec.SetField(moviewithfile.FieldMetadataTagline, field.TypeString, value)
		_node.MetadataTagline = value
	}
	if value, ok := _c.mutation.MetadataTitle(); ok {
		_spec.SetField(moviewithfile.FieldMetadataTitle, field.TypeString, value)
		_node.MetadataTitle = value
	}
	if value, ok := _c.mutation.MetadataVideo(); ok {
		_spec.SetField(moviewithfile.FieldMetadataVideo, field.TypeBool, value)
		_node.MetadataVideo = value
	}
	if value, ok := _c.mutation.MetadataVoteAverage(); ok {
		_spec.SetField(moviewithfile.FieldMetadataVoteAverage, field.TypeFloat32, value)
		_node.MetadataVoteAverage = value
	}
	if value, ok := _c.mutation.MetadataVoteCount(); ok {
		_spec.SetField(moviewithfile.FieldMetadataVoteCount, field.TypeInt64, value)
		_node.MetadataVoteCount = value
	}
	if value, ok := _c.mutation.CollectionID(); ok {
		_spec.SetField(moviewithfile.FieldCollectionID, field.TypeInt64, value)
		_node.CollectionID = value
	}
	if value, ok := _c.mutation.CollectionName(); ok {
		_spec.SetField(moviewithfile.FieldCollectionName, field.TypeString, value)
		_node.CollectionName = value
	}
	if value, ok := _c.mutation.CollectionPosterPath(); ok {
		_spec.SetField(moviewithfile.FieldCollectionPosterPath, field.TypeString, value)
		_node.CollectionPosterPath = value
	}
	if value, ok := _c.mutation.CollectionBackdropPath(); ok {
		_spec.SetField(moviewithfile.FieldCollectionBackdropPath, field.TypeString, value)
		_node.CollectionBackdropPath = value
	}
	return _node, _spec
}

// MovieWithFileCreateBulk is the builder for creating many MovieWithFile entities in bulk.
type MovieWithFileCreateBulk struct {
	config
	err      error
	builders []*MovieWithFileCreate
}

// Save creates the MovieWithFile entities in the database.
func (_c *MovieWithFileCreateBulk) Save(ctx context.Context) ([]*MovieWithFile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MovieWithFile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MovieWithFileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MovieWithFileCreateBulk) SaveX(ctx context.Context) []*MovieWithFile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MovieWithFileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MovieWithFileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
