// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/lunarr-app/lunarr-go/internal/ent/moviewithfile"
	"github.com/lunarr-app/lunarr-go/internal/ent/schema"
	"github.com/lunarr-app/lunarr-go/internal/ent/useraccount"
	"github.com/lunarr-app/lunarr-go/internal/models"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	moviewithfileFields := schema.MovieWithFile{}.Fields()
	_ = moviewithfileFields
	// moviewithfileDescCreatedAt is the schema descriptor for created_at field.
	moviewithfileDescCreatedAt := moviewithfileFields[0].Descriptor()
	// moviewithfile.DefaultCreatedAt holds the default value on creation for the created_at field.
	moviewithfile.DefaultCreatedAt = moviewithfileDescCreatedAt.Default.(func() time.Time)
	// moviewithfileDescUpdatedAt is the schema descriptor for updated_at field.
	moviewithfileDescUpdatedAt := moviewithfileFields[1].Descriptor()
	// moviewithfile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	moviewithfile.DefaultUpdatedAt = moviewithfileDescUpdatedAt.Default.(func() time.Time)
	// moviewithfile.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	moviewithfile.UpdateDefaultUpdatedAt = moviewithfileDescUpdatedAt.UpdateDefault.(func() time.Time)
	// moviewithfileDescTmdbID is the schema descriptor for tmdb_id field.
	moviewithfileDescTmdbID := moviewithfileFields[3].Descriptor()
	// moviewithfile.DefaultTmdbID holds the default value on creation for the tmdb_id field.
	moviewithfile.DefaultTmdbID = moviewithfileDescTmdbID.Default.(int32)
	// moviewithfileDescLocation is the schema descriptor for location field.
	moviewithfileDescLocation := moviewithfileFields[4].Descriptor()
	// moviewithfile.DefaultLocation holds the default value on creation for the location field.
	moviewithfile.DefaultLocation = moviewithfileDescLocation.Default.(string)
	// moviewithfileDescMetadataAdult is the schema descriptor for metadata_adult field.
	moviewithfileDescMetadataAdult := moviewithfileFields[5].Descriptor()
	// moviewithfile.DefaultMetadataAdult holds the default value on creation for the metadata_adult field.
	moviewithfile.DefaultMetadataAdult = moviewithfileDescMetadataAdult.Default.(bool)
	// moviewithfileDescMetadataBackdropPath is the schema descriptor for metadata_backdrop_path field.
	moviewithfileDescMetadataBackdropPath := moviewithfileFields[6].Descriptor()
	// moviewithfile.DefaultMetadataBackdropPath holds the default value on creation for the metadata_backdrop_path field.
	moviewithfile.DefaultMetadataBackdropPath = moviewithfileDescMetadataBackdropPath.Default.(string)
	// moviewithfileDescMetadataGenres is the schema descriptor for metadata_genres field.
	moviewithfileDescMetadataGenres := moviewithfileFields[7].Descriptor()
	// moviewithfile.DefaultMetadataGenres holds the default value on creation for the metadata_genres field.
	moviewithfile.DefaultMetadataGenres = moviewithfileDescMetadataGenres.Default.([]models.TMDbGenre)
	// moviewithfileDescMetadataHomepage is the schema descriptor for metadata_homepage field.
	moviewithfileDescMetadataHomepage := moviewithfileFields[8].Descriptor()
	// moviewithfile.DefaultMetadataHomepage holds the default value on creation for the metadata_homepage field.
	moviewithfile.DefaultMetadataHomepage = moviewithfileDescMetadataHomepage.Default.(string)
	// moviewithfileDescMetadataImdbID is the schema descriptor for metadata_imdb_id field.
	moviewithfileDescMetadataImdbID := moviewithfileFields[9].Descriptor()
	// moviewithfile.DefaultMetadataImdbID holds the default value on creation for the metadata_imdb_id field.
	moviewithfile.DefaultMetadataImdbID = moviewithfileDescMetadataImdbID.Default.(string)
	// moviewithfileDescMetadataOriginalLanguage is the schema descriptor for metadata_original_language field.
	moviewithfileDescMetadataOriginalLanguage := moviewithfileFields[10].Descriptor()
	// moviewithfile.DefaultMetadataOriginalLanguage holds the default value on creation for the metadata_original_language field.
	moviewithfile.DefaultMetadataOriginalLanguage = moviewithfileDescMetadataOriginalLanguage.Default.(string)
	// moviewithfileDescMetadataOriginalTitle is the schema descriptor for metadata_original_title field.
	moviewithfileDescMetadataOriginalTitle := moviewithfileFields[11].Descriptor()
	// moviewithfile.DefaultMetadataOriginalTitle holds the default value on creation for the metadata_original_title field.
	moviewithfile.DefaultMetadataOriginalTitle = moviewithfileDescMetadataOriginalTitle.Default.(string)
	// moviewithfileDescMetadataOverview is the schema descriptor for metadata_overview field.
	moviewithfileDescMetadataOverview := moviewithfileFields[12].Descriptor()
	// moviewithfile.DefaultMetadataOverview holds the default value on creation for the metadata_overview field.
	moviewithfile.DefaultMetadataOverview = moviewithfileDescMetadataOverview.Default.(string)
	// moviewithfileDescMetadataPopularity is the schema descriptor for metadata_popularity field.
	moviewithfileDescMetadataPopularity := moviewithfileFields[13].Descriptor()
	// moviewithfile.DefaultMetadataPopularity holds the default value on creation for the metadata_popularity field.
	moviewithfile.DefaultMetadataPopularity = moviewithfileDescMetadataPopularity.Default.(float32)
	// moviewithfileDescMetadataPosterPath is the schema descriptor for metadata_poster_path field.
	moviewithfileDescMetadataPosterPath := moviewithfileFields[14].Descriptor()
	// moviewithfile.DefaultMetadataPosterPath holds the default value on creation for the metadata_poster_path field.
	moviewithfile.DefaultMetadataPosterPath = moviewithfileDescMetadataPosterPath.Default.(string)
	// moviewithfileDescMetadataReleaseDate is the schema descriptor for metadata_release_date field.
	moviewithfileDescMetadataReleaseDate := moviewithfileFields[15].Descriptor()
	// moviewithfile.DefaultMetadataReleaseDate holds the default value on creation for the metadata_release_date field.
	moviewithfile.DefaultMetadataReleaseDate = moviewithfileDescMetadataReleaseDate.Default.(string)
	// moviewithfileDescMetadataRevenue is the schema descriptor for metadata_revenue field.
	moviewithfileDescMetadataRevenue := moviewithfileFields[16].Descriptor()
	// moviewithfile.DefaultMetadataRevenue holds the default value on creation for the metadata_revenue field.
	moviewithfile.DefaultMetadataRevenue = moviewithfileDescMetadataRevenue.Default.(int64)
	// moviewithfileDescMetadataRuntime is the schema descriptor for metadata_runtime field.
	moviewithfileDescMetadataRuntime := moviewithfileFields[17].Descriptor()
	// moviewithfile.DefaultMetadataRuntime holds the default value on creation for the metadata_runtime field.
	moviewithfile.DefaultMetadataRuntime = moviewithfileDescMetadataRuntime.Default.(int)
	// moviewithfileDescMetadataSpokenLanguages is the schema descriptor for metadata_spoken_languages field.
	moviewithfileDescMetadataSpokenLanguages := moviewithfileFields[18].Descriptor()
	// moviewithfile.DefaultMetadataSpokenLanguages holds the default value on creation for the metadata_spoken_languages field.
	moviewithfile.DefaultMetadataSpokenLanguages = moviewithfileDescMetadataSpokenLanguages.Default.([]models.TMDbSpokenLanguage)
	// moviewithfileDescMetadataStatus is the schema descriptor for metadata_status field.
	moviewithfileDescMetadataStatus := moviewithfileFields[19].Descriptor()
	// moviewithfile.DefaultMetadataStatus holds the default value on creation for the metadata_status field.
	moviewithfile.DefaultMetadataStatus = moviewithfileDescMetadataStatus.Default.(string)
	// moviewithfileDescMetadataTagline is the schema descriptor for metadata_tagline field.
	moviewithfileDescMetadataTagline := moviewithfileFields[20].Descriptor()
	// moviewithfile.DefaultMetadataTagline holds the default value on creation for the metadata_tagline field.
	moviewithfile.DefaultMetadataTagline = moviewithfileDescMetadataTagline.Default.(string)
	// moviewithfileDescMetadataTitle is the schema descriptor for metadata_title field.
	moviewithfileDescMetadataTitle := moviewithfileFields[21].Descriptor()
	// moviewithfile.DefaultMetadataTitle holds the default value on creation for the metadata_title field.
	moviewithfile.DefaultMetadataTitle = moviewithfileDescMetadataTitle.Default.(string)
	// moviewithfileDescMetadataVideo is the schema descriptor for metadata_video field.
	moviewithfileDescMetadataVideo := moviewithfileFields[22].Descriptor()
	// moviewithfile.DefaultMetadataVideo holds the default value on creation for the metadata_video field.
	moviewithfile.DefaultMetadataVideo = moviewithfileDescMetadataVideo.Default.(bool)
	// moviewithfileDescMetadataVoteAverage is the schema descriptor for metadata_vote_average field.
	moviewithfileDescMetadataVoteAverage := moviewithfileFields[23].Descriptor()
	// moviewithfile.DefaultMetadataVoteAverage holds the default value on creation for the metadata_vote_average field.
	moviewithfile.DefaultMetadataVoteAverage = moviewithfileDescMetadataVoteAverage.Default.(float32)
	// moviewithfileDescMetadataVoteCount is the schema descriptor for metadata_vote_count field.
	moviewithfileDescMetadataVoteCount := moviewithfileFields[24].Descriptor()
	// moviewithfile.DefaultMetadataVoteCount holds the default value on creation for the metadata_vote_count field.
	moviewithfile.DefaultMetadataVoteCount = moviewithfileDescMetadataVoteCount.Default.(int64)
	// moviewithfileDescCollectionID is the schema descriptor for collection_id field.
	moviewithfileDescCollectionID := moviewithfileFields[25].Descriptor()
	// moviewithfile.DefaultCollectionID holds the default value on creation for the collection_id field.
	moviewithfile.DefaultCollectionID = moviewithfileDescCollectionID.Default.(int64)
	// moviewithfileDescCollectionName is the schema descriptor for collection_name field.
	moviewithfileDescCollectionName := moviewithfileFields[26].Descriptor()
	// moviewithfile.DefaultCollectionName holds the default value on creation for the collection_name field.
	moviewithfile.DefaultCollectionName = moviewithfileDescCollectionName.Default.(string)
	// moviewithfileDescCollectionPosterPath is the schema descriptor for collection_poster_path field.
	moviewithfileDescCollectionPosterPath := moviewithfileFields[27].Descriptor()
	// moviewithfile.DefaultCollectionPosterPath holds the default value on creation for the collection_poster_path field.
	moviewithfile.DefaultCollectionPosterPath = moviewithfileDescCollectionPosterPath.Default.(string)
	// moviewithfileDescCollectionBackdropPath is the schema descriptor for collection_backdrop_path field.
	moviewithfileDescCollectionBackdropPath := moviewithfileFields[28].Descriptor()
	// moviewithfile.DefaultCollectionBackdropPath holds the default value on creation for the collection_backdrop_path field.
	moviewithfile.DefaultCollectionBackdropPath = moviewithfileDescCollectionBackdropPath.Default.(string)
	useraccountFields := schema.UserAccount{}.Fields()
	_ = useraccountFields
	// useraccountDescCreatedAt is the schema descriptor for created_at field.
	useraccountDescCreatedAt := useraccountFields[0].Descriptor()
	// useraccount.DefaultCreatedAt holds the default value on creation for the created_at field.
	useraccount.DefaultCreatedAt = useraccountDescCreatedAt.Default.(func() time.Time)
	// useraccountDescUpdatedAt is the schema descriptor for updated_at field.
	useraccountDescUpdatedAt := useraccountFields[1].Descriptor()
	// useraccount.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	useraccount.DefaultUpdatedAt = useraccountDescUpdatedAt.Default.(func() time.Time)
	// useraccount.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	useraccount.UpdateDefaultUpdatedAt = useraccountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// useraccountDescDisplayname is the schema descriptor for displayname field.
	useraccountDescDisplayname := useraccountFields[3].Descriptor()
	// useraccount.DisplaynameValidator is a validator for the "displayname" field. It is called by the builders before save.
	useraccount.DisplaynameValidator = useraccountDescDisplayname.Validators[0].(func(string) error)
	// useraccountDescUsername is the schema descriptor for username field.
	useraccountDescUsername := useraccountFields[4].Descriptor()
	// useraccount.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	useraccount.UsernameValidator = useraccountDescUsername.Validators[0].(func(string) error)
	// useraccountDescEmail is the schema descriptor for email field.
	useraccountDescEmail := useraccountFields[5].Descriptor()
	// useraccount.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	useraccount.EmailValidator = useraccountDescEmail.Validators[0].(func(string) error)
	// useraccountDescSex is the schema descriptor for sex field.
	useraccountDescSex := useraccountFields[7].Descriptor()
	// useraccount.SexValidator is a validator for the "sex" field. It is called by the builders before save.
	useraccount.SexValidator = useraccountDescSex.Validators[0].(func(string) error)
	// useraccountDescRole is the schema descriptor for role field.
	useraccountDescRole := useraccountFields[8].Descriptor()
	// useraccount.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	useraccount.RoleValidator = useraccountDescRole.Validators[0].(func(string) error)
	// useraccountDescAPIKey is the schema descriptor for api_key field.
	useraccountDescAPIKey := useraccountFields[9].Descriptor()
	// useraccount.APIKeyValidator is a validator for the "api_key" field. It is called by the builders before save.
	useraccount.APIKeyValidator = useraccountDescAPIKey.Validators[0].(func(string) error)
	// useraccountDescCurrentStatus is the schema descriptor for current_status field.
	useraccountDescCurrentStatus := useraccountFields[10].Descriptor()
	// useraccount.DefaultCurrentStatus holds the default value on creation for the current_status field.
	useraccount.DefaultCurrentStatus = useraccountDescCurrentStatus.Default.(string)
	// useraccount.CurrentStatusValidator is a validator for the "current_status" field. It is called by the builders before save.
	useraccount.CurrentStatusValidator = useraccountDescCurrentStatus.Validators[0].(func(string) error)
	// useraccountDescSettingTheme is the schema descriptor for setting_theme field.
	useraccountDescSettingTheme := useraccountFields[11].Descriptor()
	// useraccount.DefaultSettingTheme holds the default value on creation for the setting_theme field.
	useraccount.DefaultSettingTheme = useraccountDescSettingTheme.Default.(string)
	// useraccount.SettingThemeValidator is a validator for the "setting_theme" field. It is called by the builders before save.
	useraccount.SettingThemeValidator = useraccountDescSettingTheme.Validators[0].(func(string) error)
	// useraccountDescSettingEnabled is the schema descriptor for setting_enabled field.
	useraccountDescSettingEnabled := useraccountFields[12].Descriptor()
	// useraccount.DefaultSettingEnabled holds the default value on creation for the setting_enabled field.
	useraccount.DefaultSettingEnabled = useraccountDescSettingEnabled.Default.(bool)
	// useraccountDescSettingLanguage is the schema descriptor for setting_language field.
	useraccountDescSettingLanguage := useraccountFields[13].Descriptor()
	// useraccount.DefaultSettingLanguage holds the default value on creation for the setting_language field.
	useraccount.DefaultSettingLanguage = useraccountDescSettingLanguage.Default.(string)
	// useraccount.SettingLanguageValidator is a validator for the "setting_language" field. It is called by the builders before save.
	useraccount.SettingLanguageValidator = useraccountDescSettingLanguage.Validators[0].(func(string) error)
	// useraccountDescSettingResolution is the schema descriptor for setting_resolution field.
	useraccountDescSettingResolution := useraccountFields[14].Descriptor()
	// useraccount.DefaultSettingResolution holds the default value on creation for the setting_resolution field.
	useraccount.DefaultSettingResolution = useraccountDescSettingResolution.Default.(string)
	// useraccount.SettingResolutionValidator is a validator for the "setting_resolution" field. It is called by the builders before save.
	useraccount.SettingResolutionValidator = useraccountDescSettingResolution.Validators[0].(func(string) error)
	// useraccountDescSettingBitrate is the schema descriptor for setting_bitrate field.
	useraccountDescSettingBitrate := useraccountFields[15].Descriptor()
	// useraccount.DefaultSettingBitrate holds the default value on creation for the setting_bitrate field.
	useraccount.DefaultSettingBitrate = useraccountDescSettingBitrate.Default.(int)
	// useraccountDescSettingCodec is the schema descriptor for setting_codec field.
	useraccountDescSettingCodec := useraccountFields[16].Descriptor()
	// useraccount.DefaultSettingCodec holds the default value on creation for the setting_codec field.
	useraccount.DefaultSettingCodec = useraccountDescSettingCodec.Default.(string)
	// useraccount.SettingCodecValidator is a validator for the "setting_codec" field. It is called by the builders before save.
	useraccount.SettingCodecValidator = useraccountDescSettingCodec.Validators[0].(func(string) error)
}
