// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lunarr-app/lunarr-go/internal/ent/useraccount"
)

// UserAccountCreate is the builder for creating a UserAccount entity.
type UserAccountCreate struct {
	config
	mutation *UserAccountMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserAccountCreate) SetCreatedAt(v time.Time) *UserAccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserAccountCreate) SetNillableCreatedAt(v *time.Time) *UserAccountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserAccountCreate) SetUpdatedAt(v time.Time) *UserAccountCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserAccountCreate) SetNillableUpdatedAt(v *time.Time) *UserAccountCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *UserAccountCreate) SetDeletedAt(v time.Time) *UserAccountCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *UserAccountCreate) SetNillableDeletedAt(v *time.Time) *UserAccountCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetDisplayname sets the "displayname" field.
func (_c *UserAccountCreate) SetDisplayname(v string) *UserAccountCreate {
	_c.mutation.SetDisplayname(v)
	return _c
}

// SetUsername sets the "username" field.
func (_c *UserAccountCreate) SetUsername(v string) *UserAccountCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *UserAccountCreate) SetEmail(v string) *UserAccountCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetPassword sets the "password" field.
func (_c *UserAccountCreate) SetPassword(v string) *UserAccountCreate {
	_c.mutation.SetPassword(v)
	return _c
}

// SetSex sets the "sex" field.
func (_c *UserAccountCreate) SetSex(v string) *UserAccountCreate {
	_c.mutation.SetSex(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *UserAccountCreate) SetRole(v string) *UserAccountCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetAPIKey sets the "api_key" field.
func (_c *UserAccountCreate) SetAPIKey(v string) *UserAccountCreate {
	_c.mutation.SetAPIKey(v)
	return _c
}

// SetCurrentStatus sets the "current_status" field.
func (_c *UserAccountCreate) SetCurrentStatus(v string) *UserAccountCreate {
	_c.mutation.SetCurrentStatus(v)
	return _c
}

// SetNillableCurrentStatus sets the "current_status" field if the given value is not nil.
func (_c *UserAccountCreate) SetNillableCurrentStatus(v *string) *UserAccountCreate {
	if v != nil {
		_c.SetCurrentStatus(*v)
	}
	return _c
}

// SetSettingTheme sets the "setting_theme" field.
func (_c *UserAccountCreate) SetSettingTheme(v string) *UserAccountCreate {
	_c.mutation.SetSettingTheme(v)
	return _c
}

// SetNillableSettingTheme sets the "setting_theme" field if the given value is not nil.
func (_c *UserAccountCreate) SetNillableSettingTheme(v *string) *UserAccountCreate {
	if v != nil {
		_c.SetSettingTheme(*v)
	}
	return _c
}

// SetSettingEnabled sets the "setting_enabled" field.
func (_c *UserAccountCreate) SetSettingEnabled(v bool) *UserAccountCreate {
	_c.mutation.SetSettingEnabled(v)
	return _c
}

// SetNillableSettingEnabled sets the "setting_enabled" field if the given value is not nil.
func (_c *UserAccountCreate) SetNillableSettingEnabled(v *bool) *UserAccountCreate {
	if v != nil {
		_c.SetSettingEnabled(*v)
	}
	return _c
}

// SetSettingLanguage sets the "setting_language" field.
func (_c *UserAccountCreate) SetSettingLanguage(v string) *UserAccountCreate {
	_c.mutation.SetSettingLanguage(v)
	return _c
}

// SetNillableSettingLanguage sets the "setting_language" field if the given value is not nil.
func (_c *UserAccountCreate) SetNillableSettingLanguage(v *string) *UserAccountCreate {
	if v != nil {
		_c.SetSettingLanguage(*v)
	}
	return _c
}

// SetSettingResolution sets the "setting_resolution" field.
func (_c *UserAccountCreate) SetSettingResolution(v string) *UserAccountCreate {
	_c.mutation.SetSettingResolution(v)
	return _c
}

// SetNillableSettingResolution sets the "setting_resolution" field if the given value is not nil.
func (_c *UserAccountCreate) SetNillableSettingResolution(v *string) *UserAccountCreate {
	if v != nil {
		_c.SetSettingResolution(*v)
	}
	return _c
}

// SetSettingBitrate sets the "setting_bitrate" field.
func (_c *UserAccountCreate) SetSettingBitrate(v int) *UserAccountCreate {
	_c.mutation.SetSettingBitrate(v)
	return _c
}

// SetNillableSettingBitrate sets the "setting_bitrate" field if the given value is not nil.
func (_c *UserAccountCreate) SetNillableSettingBitrate(v *int) *UserAccountCreate {
	if v != nil {
		_c.SetSettingBitrate(*v)
	}
	return _c
}

// SetSettingCodec sets the "setting_codec" field.
func (_c *UserAccountCreate) SetSettingCodec(v string) *UserAccountCreate {
	_c.mutation.SetSettingCodec(v)
	return _c
}

// SetNillableSettingCodec sets the "setting_codec" field if the given value is not nil.
func (_c *UserAccountCreate) SetNillableSettingCodec(v *string) *UserAccountCreate {
	if v != nil {
		_c.SetSettingCodec(*v)
	}
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *UserAccountCreate) SetLastSeenAt(v time.Time) *UserAccountCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_c *UserAccountCreate) SetNillableLastSeenAt(v *time.Time) *UserAccountCreate {
	if v != nil {
		_c.SetLastSeenAt(*v)
	}
	return _c
}

// Mutation returns the UserAccountMutation object of the builder.
func (_c *UserAccountCreate) Mutation() *UserAccountMutation {
	return _c.mutation
}

// Save creates the UserAccount in the database.
func (_c *UserAccountCreate) Save(ctx context.Context) (*UserAccount, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserAccountCreate) SaveX(ctx context.Context) *UserAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserAccountCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := useraccount.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := useraccount.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.CurrentStatus(); !ok {
		v := useraccount.DefaultCurrentStatus
		_c.mutation.SetCurrentStatus(v)
	}
	if _, ok := _c.mutation.SettingTheme(); !ok {
		v := useraccount.DefaultSettingTheme
		_c.mutation.SetSettingTheme(v)
	}
	if _, ok := _c.mutation.SettingEnabled(); !ok {
		v := useraccount.DefaultSettingEnabled
		_c.mutation.SetSettingEnabled(v)
	}
	if _, ok := _c.mutation.SettingLanguage(); !ok {
		v := useraccount.DefaultSettingLanguage
		_c.mutation.SetSettingLanguage(v)
	}
	if _, ok := _c.mutation.SettingResolution(); !ok {
		v := useraccount.DefaultSettingResolution
		_c.mutation.SetSettingResolution(v)
	}
	if _, ok := _c.mutation.SettingBitrate(); !ok {
		v := useraccount.DefaultSettingBitrate
		_c.mutation.SetSettingBitrate(v)
	}
	if _, ok := _c.mutation.SettingCodec(); !ok {
		v := useraccount.DefaultSettingCodec
		_c.mutation.SetSettingCodec(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserAccountCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserAccount.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserAccount.updated_at"`)}
	}
	if _, ok := _c.mutation.Displayname(); !ok {
		return &ValidationError{Name: "displayname", err: errors.New(`ent: missing required field "UserAccount.displayname"`)}
	}
	if v, ok := _c.mutation.Displayname(); ok {
		if err := useraccount.DisplaynameValidator(v); err != nil {
			return &ValidationError{Name: "displayname", err: fmt.Errorf(`ent: validator failed for field "UserAccount.displayname": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "UserAccount.username"`)}
	}
	if v, ok := _c.mutation.Username(); ok {
		if err := useraccount.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "UserAccount.username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "UserAccount.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := useraccount.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "UserAccount.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "UserAccount.password"`)}
	}
	if _, ok := _c.mutation.Sex(); !ok {
		return &ValidationError{Name: "sex", err: errors.New(`ent: missing required field "UserAccount.sex"`)}
	}
	if v, ok := _c.mutation.Sex(); ok {
		if err := useraccount.SexValidator(v); err != nil {
			return &ValidationError{Name: "sex", err: fmt.Errorf(`ent: validator failed for field "UserAccount.sex": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "UserAccount.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := useraccount.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "UserAccount.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.APIKey(); !ok {
		return &ValidationError{Name: "api_key", err: errors.New(`ent: missing required field "UserAccount.api_key"`)}
	}
	if v, ok := _c.mutation.APIKey(); ok {
		if err := useraccount.APIKeyValidator(v); err != nil {
			return &ValidationError{Name: "api_key", err: fmt.Errorf(`ent: validator failed for field "UserAccount.api_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CurrentStatus(); !ok {
		return &ValidationError{Name: "current_status", err: errors.New(`ent: missing required field "UserAccount.current_status"`)}
	}
	if v, ok := _c.mutation.CurrentStatus(); ok {
		if err := useraccount.CurrentStatusValidator(v); err != nil {
			return &ValidationError{Name: "current_status", err: fmt.Errorf(`ent: validator failed for field "UserAccount.current_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SettingTheme(); !ok {
		return &ValidationError{Name: "setting_theme", err: errors.New(`ent: missing required field "UserAccount.setting_theme"`)}
	}
	if v, ok := _c.mutation.SettingTheme(); ok {
		if err := useraccount.SettingThemeValidator(v); err != nil {
			return &ValidationError{Name: "setting_theme", err: fmt.Errorf(`ent: validator failed for field "UserAccount.setting_theme": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SettingEnabled(); !ok {
		return &ValidationError{Name: "setting_enabled", err: errors.New(`ent: missing required field "UserAccount.setting_enabled"`)}
	}
	if _, ok := _c.mutation.SettingLanguage(); !ok {
		return &ValidationError{Name: "setting_language", err: errors.New(`ent: missing required field "UserAccount.setting_language"`)}
	}
	if v, ok := _c.mutation.SettingLanguage(); ok {
		if err := useraccount.SettingLanguageValidator(v); err != nil {
			return &ValidationError{Name: "setting_language", err: fmt.Errorf(`ent: validator failed for field "UserAccount.setting_language": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SettingResolution(); !ok {
		return &ValidationError{Name: "setting_resolution", err: errors.New(`ent: missing required field "UserAccount.setting_resolution"`)}
	}
	if v, ok := _c.mutation.SettingResolution(); ok {
		if err := useraccount.SettingResolutionValidator(v); err != nil {
			return &ValidationError{Name: "setting_resolution", err: fmt.Errorf(`ent: validator failed for field "UserAccount.setting_resolution": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SettingBitrate(); !ok {
		return &ValidationError{Name: "setting_bitrate", err: errors.New(`ent: missing required field "UserAccount.setting_bitrate"`)}
	}
	if _, ok := _c.mutation.SettingCodec(); !ok {
		return &ValidationError{Name: "setting_codec", err: errors.New(`ent: missing required field "UserAccount.setting_codec"`)}
	}
	if v, ok := _c.mutation.SettingCodec(); ok {
		if err := useraccount.SettingCodecValidator(v); err != nil {
			return &ValidationError{Name: "setting_codec", err: fmt.Errorf(`ent: validator failed for field "UserAccount.setting_codec": %w`, err)}
		}
	}
	return nil
}

func (_c *UserAccountCreate) sqlSave(ctx context.Context) (*UserAccount, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserAccountCreate) createSpec() (*UserAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &UserAccount{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(useraccount.Table, sqlgraph.NewFieldSpec(useraccount.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(useraccount.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(useraccount.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(useraccount.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Displayname(); ok {
		_spec.SetField(useraccount.FieldDisplayname, field.TypeString, value)
		_node.Displayname = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(useraccount.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(useraccount.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Password(); ok {
		_spec.SetField(useraccount.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := _c.mutation.Sex(); ok {
		_spec.SetField(useraccount.FieldSex, field.TypeString, value)
		_node.Sex = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(useraccount.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.APIKey(); ok {
		_spec.SetField(useraccount.FieldAPIKey, field.TypeString, value)
		_node.APIKey = value
	}
	if value, ok := _c.mutation.CurrentStatus(); ok {
		_spec.SetField(useraccount.FieldCurrentStatus, field.TypeString, value)
		_node.CurrentStatus = value
	}
	if value, ok := _c.mutation.SettingTheme(); ok {
		_spec.SetField(useraccount.FieldSettingTheme, field.TypeString, value)
		_node.SettingTheme = value
	}
	if value, ok := _c.mutation.SettingEnabled(); ok {
		_spec.SetField(useraccount.FieldSettingEnabled, field.TypeBool, value)
		_node.SettingEnabled = value
	}
	if value, ok := _c.mutation.SettingLanguage(); ok {
		_spec.SetField(useraccount.FieldSettingLanguage, field.TypeString, value)
		_node.SettingLanguage = value
	}
	if value, ok := _c.mutation.SettingResolution(); ok {
		_spec.SetField(useraccount.FieldSettingResolution, field.TypeString, value)
		_node.SettingResolution = value
	}
	if value, ok := _c.mutation.SettingBitrate(); ok {
		_spec.SetField(useraccount.FieldSettingBitrate, field.TypeInt, value)
		_node.SettingBitrate = value
	}
	if value, ok := _c.mutation.SettingCodec(); ok {
		_spec.SetField(useraccount.FieldSettingCodec, field.TypeString, value)
		_node.SettingCodec = value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(useraccount.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = value
	}
	return _node, _spec
}

// UserAccountCreateBulk is the builder for creating many UserAccount entities in bulk.
type UserAccountCreateBulk struct {
	config
	err      error
	builders []*UserAccountCreate
}

// Save creates the UserAccount entities in the database.
func (_c *UserAccountCreateBulk) Save(ctx context.Context) ([]*UserAccount, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserAccount, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserAccountCreateBulk) SaveX(ctx context.Context) []*UserAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
