// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lunarr-app/lunarr-go/internal/ent/predicate"
	"github.com/lunarr-app/lunarr-go/internal/ent/useraccount"
)

// UserAccountUpdate is the builder for updating UserAccount entities.
type UserAccountUpdate struct {
	config
	hooks    []Hook
	mutation *UserAccountMutation
}

// Where appends a list predicates to the UserAccountUpdate builder.
func (_u *UserAccountUpdate) Where(ps ...predicate.UserAccount) *UserAccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserAccountUpdate) SetUpdatedAt(v time.Time) *UserAccountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UserAccountUpdate) SetDeletedAt(v time.Time) *UserAccountUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UserAccountUpdate) SetNillableDeletedAt(v *time.Time) *UserAccountUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UserAccountUpdate) ClearDeletedAt() *UserAccountUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDisplayname sets the "displayname" field.
func (_u *UserAccountUpdate) SetDisplayname(v string) *UserAccountUpdate {
	_u.mutation.SetDisplayname(v)
	return _u
}

// SetNillableDisplayname sets the "displayname" field if the given value is not nil.
func (_u *UserAccountUpdate) SetNillableDisplayname(v *string) *UserAccountUpdate {
	if v != nil {
		_u.SetDisplayname(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *UserAccountUpdate) SetUsername(v string) *UserAccountUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserAccountUpdate) SetNillableUsername(v *string) *UserAccountUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserAccountUpdate) SetEmail(v string) *UserAccountUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserAccountUpdate) SetNillableEmail(v *string) *UserAccountUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *UserAccountUpdate) SetPassword(v string) *UserAccountUpdate {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *UserAccountUpdate) SetNillablePassword(v *string) *UserAccountUpdate {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// SetSex sets the "sex" field.
func (_u *UserAccountUpdate) SetSex(v string) *UserAccountUpdate {
	_u.mutation.SetSex(v)
	return _u
}

// SetNillableSex sets the "sex" field if the given value is not nil.
func (_u *UserAccountUpdate) SetNillableSex(v *string) *UserAccountUpdate {
	if v != nil {
		_u.SetSex(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *UserAccountUpdate) SetRole(v string) *UserAccountUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *UserAccountUpdate) SetNillableRole(v *string) *UserAccountUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *UserAccountUpdate) SetAPIKey(v string) *UserAccountUpdate {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *UserAccountUpdate) SetNillableAPIKey(v *string) *UserAccountUpdate {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// SetCurrentStatus sets the "current_status" field.
func (_u *UserAccountUpdate) SetCurrentStatus(v string) *UserAccountUpdate {
	_u.mutation.SetCurrentStatus(v)
	return _u
}

// SetNillableCurrentStatus sets the "current_status" field if the given value is not nil.
func (_u *UserAccountUpdate) SetNillableCurrentStatus(v *string) *UserAccountUpdate {
	if v != nil {
		_u.SetCurrentStatus(*v)
	}
	return _u
}

// SetSettingTheme sets the "setting_theme" field.
func (_u *UserAccountUpdate) SetSettingTheme(v string) *UserAccountUpdate {
	_u.mutation.SetSettingTheme(v)
	return _u
}

// SetNillableSettingTheme sets the "setting_theme" field if the given value is not nil.
func (_u *UserAccountUpdate) SetNillableSettingTheme(v *string) *UserAccountUpdate {
	if v != nil {
		_u.SetSettingTheme(*v)
	}
	return _u
}

// SetSettingEnabled sets the "setting_enabled" field.
func (_u *UserAccountUpdate) SetSettingEnabled(v bool) *UserAccountUpdate {
	_u.mutation.SetSettingEnabled(v)
	return _u
}

// SetNillableSettingEnabled sets the "setting_enabled" field if the given value is not nil.
func (_u *UserAccountUpdate) SetNillableSettingEnabled(v *bool) *UserAccountUpdate {
	if v != nil {
		_u.SetSettingEnabled(*v)
	}
	return _u
}

// SetSettingLanguage sets the "setting_language" field.
func (_u *UserAccountUpdate) SetSettingLanguage(v string) *UserAccountUpdate {
	_u.mutation.SetSettingLanguage(v)
	return _u
}

// SetNillableSettingLanguage sets the "setting_language" field if the given value is not nil.
func (_u *UserAccountUpdate) SetNillableSettingLanguage(v *string) *UserAccountUpdate {
	if v != nil {
		_u.SetSettingLanguage(*v)
	}
	return _u
}

// SetSettingResolution sets the "setting_resolution" field.
func (_u *UserAccountUpdate) SetSettingResolution(v string) *UserAccountUpdate {
	_u.mutation.SetSettingResolution(v)
	return _u
}

// SetNillableSettingResolution sets the "setting_resolution" field if the given value is not nil.
func (_u *UserAccountUpdate) SetNillableSettingResolution(v *string) *UserAccountUpdate {
	if v != nil {
		_u.SetSettingResolution(*v)
	}
	return _u
}

// SetSettingBitrate sets the "setting_bitrate" field.
func (_u *UserAccountUpdate) SetSettingBitrate(v int) *UserAccountUpdate {
	_u.mutation.ResetSettingBitrate()
	_u.mutation.SetSettingBitrate(v)
	return _u
}

// SetNillableSettingBitrate sets the "setting_bitrate" field if the given value is not nil.
func (_u *UserAccountUpdate) SetNillableSettingBitrate(v *int) *UserAccountUpdate {
	if v != nil {
		_u.SetSettingBitrate(*v)
	}
	return _u
}

// AddSettingBitrate adds value to the "setting_bitrate" field.
func (_u *UserAccountUpdate) AddSettingBitrate(v int) *UserAccountUpdate {
	_u.mutation.AddSettingBitrate(v)
	return _u
}

// SetSettingCodec sets the "setting_codec" field.
func (_u *UserAccountUpdate) SetSettingCodec(v string) *UserAccountUpdate {
	_u.mutation.SetSettingCodec(v)
	return _u
}

// SetNillableSettingCodec sets the "setting_codec" field if the given value is not nil.
func (_u *UserAccountUpdate) SetNillableSettingCodec(v *string) *UserAccountUpdate {
	if v != nil {
		_u.SetSettingCodec(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *UserAccountUpdate) SetLastSeenAt(v time.Time) *UserAccountUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *UserAccountUpdate) SetNillableLastSeenAt(v *time.Time) *UserAccountUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (_u *UserAccountUpdate) ClearLastSeenAt() *UserAccountUpdate {
	_u.mutation.ClearLastSeenAt()
	return _u
}

// Mutation returns the UserAccountMutation object of the builder.
func (_u *UserAccountUpdate) Mutation() *UserAccountMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserAccountUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserAccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserAccountUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := useraccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAccountUpdate) check() error {
	if v, ok := _u.mutation.Displayname(); ok {
		if err := useraccount.DisplaynameValidator(v); err != nil {
			return &ValidationError{Name: "displayname", err: fmt.Errorf(`ent: validator failed for field "UserAccount.displayname": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Username(); ok {
		if err := useraccount.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "UserAccount.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := useraccount.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "UserAccount.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sex(); ok {
		if err := useraccount.SexValidator(v); err != nil {
			return &ValidationError{Name: "sex", err: fmt.Errorf(`ent: validator failed for field "UserAccount.sex": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := useraccount.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "UserAccount.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKey(); ok {
		if err := useraccount.APIKeyValidator(v); err != nil {
			return &ValidationError{Name: "api_key", err: fmt.Errorf(`ent: validator failed for field "UserAccount.api_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CurrentStatus(); ok {
		if err := useraccount.CurrentStatusValidator(v); err != nil {
			return &ValidationError{Name: "current_status", err: fmt.Errorf(`ent: validator failed for field "UserAccount.current_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SettingTheme(); ok {
		if err := useraccount.SettingThemeValidator(v); err != nil {
			return &ValidationError{Name: "setting_theme", err: fmt.Errorf(`ent: validator failed for field "UserAccount.setting_theme": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SettingLanguage(); ok {
		if err := useraccount.SettingLanguageValidator(v); err != nil {
			return &ValidationError{Name: "setting_language", err: fmt.Errorf(`ent: validator failed for field "UserAccount.setting_language": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SettingResolution(); ok {
		if err := useraccount.SettingResolutionValidator(v); err != nil {
			return &ValidationError{Name: "setting_resolution", err: fmt.Errorf(`ent: validator failed for field "UserAccount.setting_resolution": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SettingCodec(); ok {
		if err := useraccount.SettingCodecValidator(v); err != nil {
			return &ValidationError{Name: "setting_codec", err: fmt.Errorf(`ent: validator failed for field "UserAccount.setting_codec": %w`, err)}
		}
	}
	return nil
}

func (_u *UserAccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useraccount.Table, useraccount.Columns, sqlgraph.NewFieldSpec(useraccount.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useraccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(useraccount.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(useraccount.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Displayname(); ok {
		_spec.SetField(useraccount.FieldDisplayname, field.TypeString, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(useraccount.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(useraccount.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(useraccount.FieldPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sex(); ok {
		_spec.SetField(useraccount.FieldSex, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(useraccount.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(useraccount.FieldAPIKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.CurrentStatus(); ok {
		_spec.SetField(useraccount.FieldCurrentStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SettingTheme(); ok {
		_spec.SetField(useraccount.FieldSettingTheme, field.TypeString, value)
	}
	if value, ok := _u.mutation.SettingEnabled(); ok {
		_spec.SetField(useraccount.FieldSettingEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SettingLanguage(); ok {
		_spec.SetField(useraccount.FieldSettingLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.SettingResolution(); ok {
		_spec.SetField(useraccount.FieldSettingResolution, field.TypeString, value)
	}
	if value, ok := _u.mutation.SettingBitrate(); ok {
		_spec.SetField(useraccount.FieldSettingBitrate, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSettingBitrate(); ok {
		_spec.AddField(useraccount.FieldSettingBitrate, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SettingCodec(); ok {
		_spec.SetField(useraccount.FieldSettingCodec, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(useraccount.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.LastSeenAtCleared() {
		_spec.ClearField(useraccount.FieldLastSeenAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useraccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserAccountUpdateOne is the builder for updating a single UserAccount entity.
type UserAccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserAccountMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserAccountUpdateOne) SetUpdatedAt(v time.Time) *UserAccountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UserAccountUpdateOne) SetDeletedAt(v time.Time) *UserAccountUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UserAccountUpdateOne) SetNillableDeletedAt(v *time.Time) *UserAccountUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UserAccountUpdateOne) ClearDeletedAt() *UserAccountUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDisplayname sets the "displayname" field.
func (_u *UserAccountUpdateOne) SetDisplayname(v string) *UserAccountUpdateOne {
	_u.mutation.SetDisplayname(v)
	return _u
}

// SetNillableDisplayname sets the "displayname" field if the given value is not nil.
func (_u *UserAccountUpdateOne) SetNillableDisplayname(v *string) *UserAccountUpdateOne {
	if v != nil {
		_u.SetDisplayname(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *UserAccountUpdateOne) SetUsername(v string) *UserAccountUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserAccountUpdateOne) SetNillableUsername(v *string) *UserAccountUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserAccountUpdateOne) SetEmail(v string) *UserAccountUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserAccountUpdateOne) SetNillableEmail(v *string) *UserAccountUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *UserAccountUpdateOne) SetPassword(v string) *UserAccountUpdateOne {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *UserAccountUpdateOne) SetNillablePassword(v *string) *UserAccountUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// SetSex sets the "sex" field.
func (_u *UserAccountUpdateOne) SetSex(v string) *UserAccountUpdateOne {
	_u.mutation.SetSex(v)
	return _u
}

// SetNillableSex sets the "sex" field if the given value is not nil.
func (_u *UserAccountUpdateOne) SetNillableSex(v *string) *UserAccountUpdateOne {
	if v != nil {
		_u.SetSex(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *UserAccountUpdateOne) SetRole(v string) *UserAccountUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *UserAccountUpdateOne) SetNillableRole(v *string) *UserAccountUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *UserAccountUpdateOne) SetAPIKey(v string) *UserAccountUpdateOne {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *UserAccountUpdateOne) SetNillableAPIKey(v *string) *UserAccountUpdateOne {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// SetCurrentStatus sets the "current_status" field.
func (_u *UserAccountUpdateOne) SetCurrentStatus(v string) *UserAccountUpdateOne {
	_u.mutation.SetCurrentStatus(v)
	return _u
}

// SetNillableCurrentStatus sets the "current_status" field if the given value is not nil.
func (_u *UserAccountUpdateOne) SetNillableCurrentStatus(v *string) *UserAccountUpdateOne {
	if v != nil {
		_u.SetCurrentStatus(*v)
	}
	return _u
}

// SetSettingTheme sets the "setting_theme" field.
func (_u *UserAccountUpdateOne) SetSettingTheme(v string) *UserAccountUpdateOne {
	_u.mutation.SetSettingTheme(v)
	return _u
}

// SetNillableSettingTheme sets the "setting_theme" field if the given value is not nil.
func (_u *UserAccountUpdateOne) SetNillableSettingTheme(v *string) *UserAccountUpdateOne {
	if v != nil {
		_u.SetSettingTheme(*v)
	}
	return _u
}

// SetSettingEnabled sets the "setting_enabled" field.
func (_u *UserAccountUpdateOne) SetSettingEnabled(v bool) *UserAccountUpdateOne {
	_u.mutation.SetSettingEnabled(v)
	return _u
}

// SetNillableSettingEnabled sets the "setting_enabled" field if the given value is not nil.
func (_u *UserAccountUpdateOne) SetNillableSettingEnabled(v *bool) *UserAccountUpdateOne {
	if v != nil {
		_u.SetSettingEnabled(*v)
	}
	return _u
}

// SetSettingLanguage sets the "setting_language" field.
func (_u *UserAccountUpdateOne) SetSettingLanguage(v string) *UserAccountUpdateOne {
	_u.mutation.SetSettingLanguage(v)
	return _u
}

// SetNillableSettingLanguage sets the "setting_language" field if the given value is not nil.
func (_u *UserAccountUpdateOne) SetNillableSettingLanguage(v *string) *UserAccountUpdateOne {
	if v != nil {
		_u.SetSettingLanguage(*v)
	}
	return _u
}

// SetSettingResolution sets the "setting_resolution" field.
func (_u *UserAccountUpdateOne) SetSettingResolution(v string) *UserAccountUpdateOne {
	_u.mutation.SetSettingResolution(v)
	return _u
}

// SetNillableSettingResolution sets the "setting_resolution" field if the given value is not nil.
func (_u *UserAccountUpdateOne) SetNillableSettingResolution(v *string) *UserAccountUpdateOne {
	if v != nil {
		_u.SetSettingResolution(*v)
	}
	return _u
}

// SetSettingBitrate sets the "setting_bitrate" field.
func (_u *UserAccountUpdateOne) SetSettingBitrate(v int) *UserAccountUpdateOne {
	_u.mutation.ResetSettingBitrate()
	_u.mutation.SetSettingBitrate(v)
	return _u
}

// SetNillableSettingBitrate sets the "setting_bitrate" field if the given value is not nil.
func (_u *UserAccountUpdateOne) SetNillableSettingBitrate(v *int) *UserAccountUpdateOne {
	if v != nil {
		_u.SetSettingBitrate(*v)
	}
	return _u
}

// AddSettingBitrate adds value to the "setting_bitrate" field.
func (_u *UserAccountUpdateOne) AddSettingBitrate(v int) *UserAccountUpdateOne {
	_u.mutation.AddSettingBitrate(v)
	return _u
}

// SetSettingCodec sets the "setting_codec" field.
func (_u *UserAccountUpdateOne) SetSettingCodec(v string) *UserAccountUpdateOne {
	_u.mutation.SetSettingCodec(v)
	return _u
}

// SetNillableSettingCodec sets the "setting_codec" field if the given value is not nil.
func (_u *UserAccountUpdateOne) SetNillableSettingCodec(v *string) *UserAccountUpdateOne {
	if v != nil {
		_u.SetSettingCodec(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *UserAccountUpdateOne) SetLastSeenAt(v time.Time) *UserAccountUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *UserAccountUpdateOne) SetNillableLastSeenAt(v *time.Time) *UserAccountUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (_u *UserAccountUpdateOne) ClearLastSeenAt() *UserAccountUpdateOne {
	_u.mutation.ClearLastSeenAt()
	return _u
}

// Mutation returns the UserAccountMutation object of the builder.
func (_u *UserAccountUpdateOne) Mutation() *UserAccountMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserAccountUpdate builder.
func (_u *UserAccountUpdateOne) Where(ps ...predicate.UserAccount) *UserAccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserAccountUpdateOne) Select(field string, fields ...string) *UserAccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserAccount entity.
func (_u *UserAccountUpdateOne) Save(ctx context.Context) (*UserAccount, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAccountUpdateOne) SaveX(ctx context.Context) *UserAccount {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserAccountUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := useraccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAccountUpdateOne) check() error {
	if v, ok := _u.mutation.Displayname(); ok {
		if err := useraccount.DisplaynameValidator(v); err != nil {
			return &ValidationError{Name: "displayname", err: fmt.Errorf(`ent: validator failed for field "UserAccount.displayname": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Username(); ok {
		if err := useraccount.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "UserAccount.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := useraccount.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "UserAccount.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sex(); ok {
		if err := useraccount.SexValidator(v); err != nil {
			return &ValidationError{Name: "sex", err: fmt.Errorf(`ent: validator failed for field "UserAccount.sex": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := useraccount.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "UserAccount.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKey(); ok {
		if err := useraccount.APIKeyValidator(v); err != nil {
			return &ValidationError{Name: "api_key", err: fmt.Errorf(`ent: validator failed for field "UserAccount.api_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CurrentStatus(); ok {
		if err := useraccount.CurrentStatusValidator(v); err != nil {
			return &ValidationError{Name: "current_status", err: fmt.Errorf(`ent: validator failed for field "UserAccount.current_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SettingTheme(); ok {
		if err := useraccount.SettingThemeValidator(v); err != nil {
			return &ValidationError{Name: "setting_theme", err: fmt.Errorf(`ent: validator failed for field "UserAccount.setting_theme": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SettingLanguage(); ok {
		if err := useraccount.SettingLanguageValidator(v); err != nil {
			return &ValidationError{Name: "setting_language", err: fmt.Errorf(`ent: validator failed for field "UserAccount.setting_language": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SettingResolution(); ok {
		if err := useraccount.SettingResolutionValidator(v); err != nil {
			return &ValidationError{Name: "setting_resolution", err: fmt.Errorf(`ent: validator failed for field "UserAccount.setting_resolution": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SettingCodec(); ok {
		if err := useraccount.SettingCodecValidator(v); err != nil {
			return &ValidationError{Name: "setting_codec", err: fmt.Errorf(`ent: validator failed for field "UserAccount.setting_codec": %w`, err)}
		}
	}
	return nil
}

func (_u *UserAccountUpdateOne) sqlSave(ctx context.Context) (_node *UserAccount, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useraccount.Table, useraccount.Columns, sqlgraph.NewFieldSpec(useraccount.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useraccount.FieldID)
		for _, f := range fields {
			if !useraccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != useraccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useraccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(useraccount.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(useraccount.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Displayname(); ok {
		_spec.SetField(useraccount.FieldDisplayname, field.TypeString, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(useraccount.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(useraccount.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(useraccount.FieldPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sex(); ok {
		_spec.SetField(useraccount.FieldSex, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(useraccount.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(useraccount.FieldAPIKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.CurrentStatus(); ok {
		_spec.SetField(useraccount.FieldCurrentStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SettingTheme(); ok {
		_spec.SetField(useraccount.FieldSettingTheme, field.TypeString, value)
	}
	if value, ok := _u.mutation.SettingEnabled(); ok {
		_spec.SetField(useraccount.FieldSettingEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SettingLanguage(); ok {
		_spec.SetField(useraccount.FieldSettingLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.SettingResolution(); ok {
		_spec.SetField(useraccount.FieldSettingResolution, field.TypeString, value)
	}
	if value, ok := _u.mutation.SettingBitrate(); ok {
		_spec.SetField(useraccount.FieldSettingBitrate, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSettingBitrate(); ok {
		_spec.AddField(useraccount.FieldSettingBitrate, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SettingCodec(); ok {
		_spec.SetField(useraccount.FieldSettingCodec, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(useraccount.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.LastSeenAtCleared() {
		_spec.ClearField(useraccount.FieldLastSeenAt, field.TypeTime)
	}
	_node = &UserAccount{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useraccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
