// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/lunarr-app/lunarr-go/internal/ent/useraccount"
)

// UserAccount is the model entity for the UserAccount schema.
type UserAccount struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Displayname holds the value of the "displayname" field.
	Displayname string `json:"displayname,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Password holds the value of the "password" field.
	Password string `json:"password,omitempty"`
	// Sex holds the value of the "sex" field.
	Sex string `json:"sex,omitempty"`
	// Role holds the value of the "role" field.
	Role string `json:"role,omitempty"`
	// APIKey holds the value of the "api_key" field.
	APIKey string `json:"api_key,omitempty"`
	// CurrentStatus holds the value of the "current_status" field.
	CurrentStatus string `json:"current_status,omitempty"`
	// SettingTheme holds the value of the "setting_theme" field.
	SettingTheme string `json:"setting_theme,omitempty"`
	// SettingEnabled holds the value of the "setting_enabled" field.
	SettingEnabled bool `json:"setting_enabled,omitempty"`
	// SettingLanguage holds the value of the "setting_language" field.
	SettingLanguage string `json:"setting_language,omitempty"`
	// SettingResolution holds the value of the "setting_resolution" field.
	SettingResolution string `json:"setting_resolution,omitempty"`
	// SettingBitrate holds the value of the "setting_bitrate" field.
	SettingBitrate int `json:"setting_bitrate,omitempty"`
	// SettingCodec holds the value of the "setting_codec" field.
	SettingCodec string `json:"setting_codec,omitempty"`
	// LastSeenAt holds the value of the "last_seen_at" field.
	LastSeenAt   time.Time `json:"last_seen_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserAccount) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case useraccount.FieldSettingEnabled:
			values[i] = new(sql.NullBool)
		case useraccount.FieldID, useraccount.FieldSettingBitrate:
			values[i] = new(sql.NullInt64)
		case useraccount.FieldDisplayname, useraccount.FieldUsername, useraccount.FieldEmail, useraccount.FieldPassword, useraccount.FieldSex, useraccount.FieldRole, useraccount.FieldAPIKey, useraccount.FieldCurrentStatus, useraccount.FieldSettingTheme, useraccount.FieldSettingLanguage, useraccount.FieldSettingResolution, useraccount.FieldSettingCodec:
			values[i] = new(sql.NullString)
		case useraccount.FieldCreatedAt, useraccount.FieldUpdatedAt, useraccount.FieldDeletedAt, useraccount.FieldLastSeenAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserAccount fields.
func (_m *UserAccount) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case useraccount.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case useraccount.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case useraccount.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case useraccount.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case useraccount.FieldDisplayname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field displayname", values[i])
			} else if value.Valid {
				_m.Displayname = value.String
			}
		case useraccount.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case useraccount.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case useraccount.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				_m.Password = value.String
			}
		case useraccount.FieldSex:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sex", values[i])
			} else if value.Valid {
				_m.Sex = value.String
			}
		case useraccount.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case useraccount.FieldAPIKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_key", values[i])
			} else if value.Valid {
				_m.APIKey = value.String
			}
		case useraccount.FieldCurrentStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field current_status", values[i])
			} else if value.Valid {
				_m.CurrentStatus = value.String
			}
		case useraccount.FieldSettingTheme:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field setting_theme", values[i])
			} else if value.Valid {
				_m.SettingTheme = value.String
			}
		case useraccount.FieldSettingEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field setting_enabled", values[i])
			} else if value.Valid {
				_m.SettingEnabled = value.Bool
			}
		case useraccount.FieldSettingLanguage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field setting_language", values[i])
			} else if value.Valid {
				_m.SettingLanguage = value.String
			}
		case useraccount.FieldSettingResolution:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field setting_resolution", values[i])
			} else if value.Valid {
				_m.SettingResolution = value.String
			}
		case useraccount.FieldSettingBitrate:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field setting_bitrate", values[i])
			} else if value.Valid {
				_m.SettingBitrate = int(value.Int64)
			}
		case useraccount.FieldSettingCodec:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field setting_codec", values[i])
			} else if value.Valid {
				_m.SettingCodec = value.String
			}
		case useraccount.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				_m.LastSeenAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserAccount.
// This includes values selected through modifiers, order, etc.
func (_m *UserAccount) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UserAccount.
// Note that you need to call UserAccount.Unwrap() before calling this method if this UserAccount
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserAccount) Update() *UserAccountUpdateOne {
	return NewUserAccountClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserAccount entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserAccount) Unwrap() *UserAccount {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserAccount is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserAccount) String() string {
	var builder strings.Builder
	builder.WriteString("UserAccount(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("displayname=")
	builder.WriteString(_m.Displayname)
	builder.WriteString(", ")
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("password=")
	builder.WriteString(_m.Password)
	builder.WriteString(", ")
	builder.WriteString("sex=")
	builder.WriteString(_m.Sex)
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("api_key=")
	builder.WriteString(_m.APIKey)
	builder.WriteString(", ")
	builder.WriteString("current_status=")
	builder.WriteString(_m.CurrentStatus)
	builder.WriteString(", ")
	builder.WriteString("setting_theme=")
	builder.WriteString(_m.SettingTheme)
	builder.WriteString(", ")
	builder.WriteString("setting_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.SettingEnabled))
	builder.WriteString(", ")
	builder.WriteString("setting_language=")
	builder.WriteString(_m.SettingLanguage)
	builder.WriteString(", ")
	builder.WriteString("setting_resolution=")
	builder.WriteString(_m.SettingResolution)
	builder.WriteString(", ")
	builder.WriteString("setting_bitrate=")
	builder.WriteString(fmt.Sprintf("%v", _m.SettingBitrate))
	builder.WriteString(", ")
	builder.WriteString("setting_codec=")
	builder.WriteString(_m.SettingCodec)
	builder.WriteString(", ")
	builder.WriteString("last_seen_at=")
	builder.WriteString(_m.LastSeenAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserAccounts is a parsable slice of UserAccount.
type UserAccounts []*UserAccount
