// Code generated by ent, DO NOT EDIT.

package moviewithfile

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/lunarr-app/lunarr-go/internal/models"
)

const (
	// Label holds the string label denoting the moviewithfile type in the database.
	Label = "movie_with_file"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldTmdbID holds the string denoting the tmdb_id field in the database.
	FieldTmdbID = "tmdb_id"
	// FieldLocation holds the string denoting the location field in the database.
	FieldLocation = "location"
	// FieldMetadataAdult holds the string denoting the metadata_adult field in the database.
	FieldMetadataAdult = "metadata_adult"
	// FieldMetadataBackdropPath holds the string denoting the metadata_backdrop_path field in the database.
	FieldMetadataBackdropPath = "metadata_backdrop_path"
	// FieldMetadataGenres holds the string denoting the metadata_genres field in the database.
	FieldMetadataGenres = "metadata_genres"
	// FieldMetadataHomepage holds the string denoting the metadata_homepage field in the database.
	FieldMetadataHomepage = "metadata_homepage"
	// FieldMetadataImdbID holds the string denoting the metadata_imdb_id field in the database.
	FieldMetadataImdbID = "metadata_imdb_id"
	// FieldMetadataOriginalLanguage holds the string denoting the metadata_original_language field in the database.
	FieldMetadataOriginalLanguage = "metadata_original_language"
	// FieldMetadataOriginalTitle holds the string denoting the metadata_original_title field in the database.
	FieldMetadataOriginalTitle = "metadata_original_title"
	// FieldMetadataOverview holds the string denoting the metadata_overview field in the database.
	FieldMetadataOverview = "metadata_overview"
	// FieldMetadataPopularity holds the string denoting the metadata_popularity field in the database.
	FieldMetadataPopularity = "metadata_popularity"
	// FieldMetadataPosterPath holds the string denoting the metadata_poster_path field in the database.
	FieldMetadataPosterPath = "metadata_poster_path"
	// FieldMetadataReleaseDate holds the string denoting the metadata_release_date field in the database.
	FieldMetadataReleaseDate = "metadata_release_date"
	// FieldMetadataRevenue holds the string denoting the metadata_revenue field in the database.
	FieldMetadataRevenue = "metadata_revenue"
	// FieldMetadataRuntime holds the string denoting the metadata_runtime field in the database.
	FieldMetadataRuntime = "metadata_runtime"
	// FieldMetadataSpokenLanguages holds the string denoting the metadata_spoken_languages field in the database.
	FieldMetadataSpokenLanguages = "metadata_spoken_languages"
	// FieldMetadataStatus holds the string denoting the metadata_status field in the database.
	FieldMetadataStatus = "metadata_status"
	// FieldMetadataTagline holds the string denoting the metadata_tagline field in the database.
	FieldMetadataTagline = "metadata_tagline"
	// FieldMetadataTitle holds the string denoting the metadata_title field in the database.
	FieldMetadataTitle = "metadata_title"
	// FieldMetadataVideo holds the string denoting the metadata_video field in the database.
	FieldMetadataVideo = "metadata_video"
	// FieldMetadataVoteAverage holds the string denoting the metadata_vote_average field in the database.
	FieldMetadataVoteAverage = "metadata_vote_average"
	// FieldMetadataVoteCount holds the string denoting the metadata_vote_count field in the database.
	FieldMetadataVoteCount = "metadata_vote_count"
	// FieldCollectionID holds the string denoting the collection_id field in the database.
	FieldCollectionID = "collection_id"
	// FieldCollectionName holds the string denoting the collection_name field in the database.
	FieldCollectionName = "collection_name"
	// FieldCollectionPosterPath holds the string denoting the collection_poster_path field in the database.
	FieldCollectionPosterPath = "collection_poster_path"
	// FieldCollectionBackdropPath holds the string denoting the collection_backdrop_path field in the database.
	FieldCollectionBackdropPath = "collection_backdrop_path"
	// Table holds the table name of the moviewithfile in the database.
	Table = "movie_with_files"
)

// Columns holds all SQL columns for moviewithfile fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldTmdbID,
	FieldLocation,
	FieldMetadataAdult,
	FieldMetadataBackdropPath,
	FieldMetadataGenres,
	FieldMetadataHomepage,
	FieldMetadataImdbID,
	FieldMetadataOriginalLanguage,
	FieldMetadataOriginalTitle,
	FieldMetadataOverview,
	FieldMetadataPopularity,
	FieldMetadataPosterPath,
	FieldMetadataReleaseDate,
	FieldMetadataRevenue,
	FieldMetadataRuntime,
	FieldMetadataSpokenLanguages,
	FieldMetadataStatus,
	FieldMetadataTagline,
	FieldMetadataTitle,
	FieldMetadataVideo,
	FieldMetadataVoteAverage,
	FieldMetadataVoteCount,
	FieldCollectionID,
	FieldCollectionName,
	FieldCollectionPosterPath,
	FieldCollectionBackdropPath,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultTmdbID holds the default value on creation for the "tmdb_id" field.
	DefaultTmdbID int32
	// DefaultLocation holds the default value on creation for the "location" field.
	DefaultLocation string
	// DefaultMetadataAdult holds the default value on creation for the "metadata_adult" field.
	DefaultMetadataAdult bool
	// DefaultMetadataBackdropPath holds the default value on creation for the "metadata_backdrop_path" field.
	DefaultMetadataBackdropPath string
	// DefaultMetadataGenres holds the default value on creation for the "metadata_genres" field.
	DefaultMetadataGenres []models.TMDbGenre
	// DefaultMetadataHomepage holds the default value on creation for the "metadata_homepage" field.
	DefaultMetadataHomepage string
	// DefaultMetadataImdbID holds the default value on creation for the "metadata_imdb_id" field.
	DefaultMetadataImdbID string
	// DefaultMetadataOriginalLanguage holds the default value on creation for the "metadata_original_language" field.
	DefaultMetadataOriginalLanguage string
	// DefaultMetadataOriginalTitle holds the default value on creation for the "metadata_original_title" field.
	DefaultMetadataOriginalTitle string
	// DefaultMetadataOverview holds the default value on creation for the "metadata_overview" field.
	DefaultMetadataOverview string
	// DefaultMetadataPopularity holds the default value on creation for the "metadata_popularity" field.
	DefaultMetadataPopularity float32
	// DefaultMetadataPosterPath holds the default value on creation for the "metadata_poster_path" field.
	DefaultMetadataPosterPath string
	// DefaultMetadataReleaseDate holds the default value on creation for the "metadata_release_date" field.
	DefaultMetadataReleaseDate string
	// DefaultMetadataRevenue holds the default value on creation for the "metadata_revenue" field.
	DefaultMetadataRevenue int64
	// DefaultMetadataRuntime holds the default value on creation for the "metadata_runtime" field.
	DefaultMetadataRuntime int
	// DefaultMetadataSpokenLanguages holds the default value on creation for the "metadata_spoken_languages" field.
	DefaultMetadataSpokenLanguages []models.TMDbSpokenLanguage
	// DefaultMetadataStatus holds the default value on creation for the "metadata_status" field.
	DefaultMetadataStatus string
	// DefaultMetadataTagline holds the default value on creation for the "metadata_tagline" field.
	DefaultMetadataTagline string
	// DefaultMetadataTitle holds the default value on creation for the "metadata_title" field.
	DefaultMetadataTitle string
	// DefaultMetadataVideo holds the default value on creation for the "metadata_video" field.
	DefaultMetadataVideo bool
	// DefaultMetadataVoteAverage holds the default value on creation for the "metadata_vote_average" field.
	DefaultMetadataVoteAverage float32
	// DefaultMetadataVoteCount holds the default value on creation for the "metadata_vote_count" field.
	DefaultMetadataVoteCount int64
	// DefaultCollectionID holds the default value on creation for the "collection_id" field.
	DefaultCollectionID int64
	// DefaultCollectionName holds the default value on creation for the "collection_name" field.
	DefaultCollectionName string
	// DefaultCollectionPosterPath holds the default value on creation for the "collection_poster_path" field.
	DefaultCollectionPosterPath string
	// DefaultCollectionBackdropPath holds the default value on creation for the "collection_backdrop_path" field.
	DefaultCollectionBackdropPath string
)

// OrderOption defines the ordering options for the MovieWithFile queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByTmdbID orders the results by the tmdb_id field.
func ByTmdbID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTmdbID, opts...).ToFunc()
}

// ByLocation orders the results by the location field.
func ByLocation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocation, opts...).ToFunc()
}

// ByMetadataAdult orders the results by the metadata_adult field.
func ByMetadataAdult(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataAdult, opts...).ToFunc()
}

// ByMetadataBackdropPath orders the results by the metadata_backdrop_path field.
func ByMetadataBackdropPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataBackdropPath, opts...).ToFunc()
}

// ByMetadataHomepage orders the results by the metadata_homepage field.
func ByMetadataHomepage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataHomepage, opts...).ToFunc()
}

// ByMetadataImdbID orders the results by the metadata_imdb_id field.
func ByMetadataImdbID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataImdbID, opts...).ToFunc()
}

// ByMetadataOriginalLanguage orders the results by the metadata_original_language field.
func ByMetadataOriginalLanguage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataOriginalLanguage, opts...).ToFunc()
}

// ByMetadataOriginalTitle orders the results by the metadata_original_title field.
func ByMetadataOriginalTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataOriginalTitle, opts...).ToFunc()
}

// ByMetadataOverview orders the results by the metadata_overview field.
func ByMetadataOverview(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataOverview, opts...).ToFunc()
}

// ByMetadataPopularity orders the results by the metadata_popularity field.
func ByMetadataPopularity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataPopularity, opts...).ToFunc()
}

// ByMetadataPosterPath orders the results by the metadata_poster_path field.
func ByMetadataPosterPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataPosterPath, opts...).ToFunc()
}

// ByMetadataReleaseDate orders the results by the metadata_release_date field.
func ByMetadataReleaseDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataReleaseDate, opts...).ToFunc()
}

// ByMetadataRevenue orders the results by the metadata_revenue field.
func ByMetadataRevenue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataRevenue, opts...).ToFunc()
}

// ByMetadataRuntime orders the results by the metadata_runtime field.
func ByMetadataRuntime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataRuntime, opts...).ToFunc()
}

// ByMetadataStatus orders the results by the metadata_status field.
func ByMetadataStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataStatus, opts...).ToFunc()
}

// ByMetadataTagline orders the results by the metadata_tagline field.
func ByMetadataTagline(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataTagline, opts...).ToFunc()
}

// ByMetadataTitle orders the results by the metadata_title field.
func ByMetadataTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataTitle, opts...).ToFunc()
}

// ByMetadataVideo orders the results by the metadata_video field.
func ByMetadataVideo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataVideo, opts...).ToFunc()
}

// ByMetadataVoteAverage orders the results by the metadata_vote_average field.
func ByMetadataVoteAverage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataVoteAverage, opts...).ToFunc()
}

// ByMetadataVoteCount orders the results by the metadata_vote_count field.
func ByMetadataVoteCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataVoteCount, opts...).ToFunc()
}

// ByCollectionID orders the results by the collection_id field.
func ByCollectionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCollectionID, opts...).ToFunc()
}

// ByCollectionName orders the results by the collection_name field.
func ByCollectionName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCollectionName, opts...).ToFunc()
}

// ByCollectionPosterPath orders the results by the collection_poster_path field.
func ByCollectionPosterPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCollectionPosterPath, opts...).ToFunc()
}

// ByCollectionBackdropPath orders the results by the collection_backdrop_path field.
func ByCollectionBackdropPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCollectionBackdropPath, opts...).ToFunc()
}
