// Code generated by ent, DO NOT EDIT.

package moviewithfile

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/lunarr-app/lunarr-go/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldDeletedAt, v))
}

// TmdbID applies equality check predicate on the "tmdb_id" field. It's identical to TmdbIDEQ.
func TmdbID(v int32) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldTmdbID, v))
}

// Location applies equality check predicate on the "location" field. It's identical to LocationEQ.
func Location(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldLocation, v))
}

// MetadataAdult applies equality check predicate on the "metadata_adult" field. It's identical to MetadataAdultEQ.
func MetadataAdult(v bool) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataAdult, v))
}

// MetadataBackdropPath applies equality check predicate on the "metadata_backdrop_path" field. It's identical to MetadataBackdropPathEQ.
func MetadataBackdropPath(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataBackdropPath, v))
}

// MetadataHomepage applies equality check predicate on the "metadata_homepage" field. It's identical to MetadataHomepageEQ.
func MetadataHomepage(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataHomepage, v))
}

// MetadataImdbID applies equality check predicate on the "metadata_imdb_id" field. It's identical to MetadataImdbIDEQ.
func MetadataImdbID(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataImdbID, v))
}

// MetadataOriginalLanguage applies equality check predicate on the "metadata_original_language" field. It's identical to MetadataOriginalLanguageEQ.
func MetadataOriginalLanguage(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataOriginalLanguage, v))
}

// MetadataOriginalTitle applies equality check predicate on the "metadata_original_title" field. It's identical to MetadataOriginalTitleEQ.
func MetadataOriginalTitle(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataOriginalTitle, v))
}

// MetadataOverview applies equality check predicate on the "metadata_overview" field. It's identical to MetadataOverviewEQ.
func MetadataOverview(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataOverview, v))
}

// MetadataPopularity applies equality check predicate on the "metadata_popularity" field. It's identical to MetadataPopularityEQ.
func MetadataPopularity(v float32) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataPopularity, v))
}

// MetadataPosterPath applies equality check predicate on the "metadata_poster_path" field. It's identical to MetadataPosterPathEQ.
func MetadataPosterPath(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataPosterPath, v))
}

// MetadataReleaseDate applies equality check predicate on the "metadata_release_date" field. It's identical to MetadataReleaseDateEQ.
func MetadataReleaseDate(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataReleaseDate, v))
}

// MetadataRevenue applies equality check predicate on the "metadata_revenue" field. It's identical to MetadataRevenueEQ.
func MetadataRevenue(v int64) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataRevenue, v))
}

// MetadataRuntime applies equality check predicate on the "metadata_runtime" field. It's identical to MetadataRuntimeEQ.
func MetadataRuntime(v int) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataRuntime, v))
}

// MetadataStatus applies equality check predicate on the "metadata_status" field. It's identical to MetadataStatusEQ.
func MetadataStatus(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataStatus, v))
}

// MetadataTagline applies equality check predicate on the "metadata_tagline" field. It's identical to MetadataTaglineEQ.
func MetadataTagline(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataTagline, v))
}

// MetadataTitle applies equality check predicate on the "metadata_title" field. It's identical to MetadataTitleEQ.
func MetadataTitle(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataTitle, v))
}

// MetadataVideo applies equality check predicate on the "metadata_video" field. It's identical to MetadataVideoEQ.
func MetadataVideo(v bool) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataVideo, v))
}

// MetadataVoteAverage applies equality check predicate on the "metadata_vote_average" field. It's identical to MetadataVoteAverageEQ.
func MetadataVoteAverage(v float32) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataVoteAverage, v))
}

// MetadataVoteCount applies equality check predicate on the "metadata_vote_count" field. It's identical to MetadataVoteCountEQ.
func MetadataVoteCount(v int64) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataVoteCount, v))
}

// CollectionID applies equality check predicate on the "collection_id" field. It's identical to CollectionIDEQ.
func CollectionID(v int64) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldCollectionID, v))
}

// CollectionName applies equality check predicate on the "collection_name" field. It's identical to CollectionNameEQ.
func CollectionName(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldCollectionName, v))
}

// CollectionPosterPath applies equality check predicate on the "collection_poster_path" field. It's identical to CollectionPosterPathEQ.
func CollectionPosterPath(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldCollectionPosterPath, v))
}

// CollectionBackdropPath applies equality check predicate on the "collection_backdrop_path" field. It's identical to CollectionBackdropPathEQ.
func CollectionBackdropPath(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldCollectionBackdropPath, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNotNull(FieldDeletedAt))
}

// TmdbIDEQ applies the EQ predicate on the "tmdb_id" field.
func TmdbIDEQ(v int32) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldTmdbID, v))
}

// TmdbIDNEQ applies the NEQ predicate on the "tmdb_id" field.
func TmdbIDNEQ(v int32) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNEQ(FieldTmdbID, v))
}

// TmdbIDIn applies the In predicate on the "tmdb_id" field.
func TmdbIDIn(vs ...int32) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldIn(FieldTmdbID, vs...))
}

// TmdbIDNotIn applies the NotIn predicate on the "tmdb_id" field.
func TmdbIDNotIn(vs ...int32) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNotIn(FieldTmdbID, vs...))
}

// TmdbIDGT applies the GT predicate on the "tmdb_id" field.
func TmdbIDGT(v int32) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGT(FieldTmdbID, v))
}

// TmdbIDGTE applies the GTE predicate on the "tmdb_id" field.
func TmdbIDGTE(v int32) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGTE(FieldTmdbID, v))
}

// TmdbIDLT applies the LT predicate on the "tmdb_id" field.
func TmdbIDLT(v int32) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLT(FieldTmdbID, v))
}

// TmdbIDLTE applies the LTE predicate on the "tmdb_id" field.
func TmdbIDLTE(v int32) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLTE(FieldTmdbID, v))
}

// LocationEQ applies the EQ predicate on the "location" field.
func LocationEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldLocation, v))
}

// LocationNEQ applies the NEQ predicate on the "location" field.
func LocationNEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNEQ(FieldLocation, v))
}

// LocationIn applies the In predicate on the "location" field.
func LocationIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldIn(FieldLocation, vs...))
}

// LocationNotIn applies the NotIn predicate on the "location" field.
func LocationNotIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNotIn(FieldLocation, vs...))
}

// LocationGT applies the GT predicate on the "location" field.
func LocationGT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGT(FieldLocation, v))
}

// LocationGTE applies the GTE predicate on the "location" field.
func LocationGTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGTE(FieldLocation, v))
}

// LocationLT applies the LT predicate on the "location" field.
func LocationLT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLT(FieldLocation, v))
}

// LocationLTE applies the LTE predicate on the "location" field.
func LocationLTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLTE(FieldLocation, v))
}

// LocationContains applies the Contains predicate on the "location" field.
func LocationContains(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContains(FieldLocation, v))
}

// LocationHasPrefix applies the HasPrefix predicate on the "location" field.
func LocationHasPrefix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasPrefix(FieldLocation, v))
}

// LocationHasSuffix applies the HasSuffix predicate on the "location" field.
func LocationHasSuffix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasSuffix(FieldLocation, v))
}

// LocationEqualFold applies the EqualFold predicate on the "location" field.
func LocationEqualFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEqualFold(FieldLocation, v))
}

// LocationContainsFold applies the ContainsFold predicate on the "location" field.
func LocationContainsFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContainsFold(FieldLocation, v))
}

// MetadataAdultEQ applies the EQ predicate on the "metadata_adult" field.
func MetadataAdultEQ(v bool) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataAdult, v))
}

// MetadataAdultNEQ applies the NEQ predicate on the "metadata_adult" field.
func MetadataAdultNEQ(v bool) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNEQ(FieldMetadataAdult, v))
}

// MetadataBackdropPathEQ applies the EQ predicate on the "metadata_backdrop_path" field.
func MetadataBackdropPathEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataBackdropPath, v))
}

// MetadataBackdropPathNEQ applies the NEQ predicate on the "metadata_backdrop_path" field.
func MetadataBackdropPathNEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNEQ(FieldMetadataBackdropPath, v))
}

// MetadataBackdropPathIn applies the In predicate on the "metadata_backdrop_path" field.
func MetadataBackdropPathIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldIn(FieldMetadataBackdropPath, vs...))
}

// MetadataBackdropPathNotIn applies the NotIn predicate on the "metadata_backdrop_path" field.
func MetadataBackdropPathNotIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNotIn(FieldMetadataBackdropPath, vs...))
}

// MetadataBackdropPathGT applies the GT predicate on the "metadata_backdrop_path" field.
func MetadataBackdropPathGT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGT(FieldMetadataBackdropPath, v))
}

// MetadataBackdropPathGTE applies the GTE predicate on the "metadata_backdrop_path" field.
func MetadataBackdropPathGTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGTE(FieldMetadataBackdropPath, v))
}

// MetadataBackdropPathLT applies the LT predicate on the "metadata_backdrop_path" field.
func MetadataBackdropPathLT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLT(FieldMetadataBackdropPath, v))
}

// MetadataBackdropPathLTE applies the LTE predicate on the "metadata_backdrop_path" field.
func MetadataBackdropPathLTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLTE(FieldMetadataBackdropPath, v))
}

// MetadataBackdropPathContains applies the Contains predicate on the "metadata_backdrop_path" field.
func MetadataBackdropPathContains(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContains(FieldMetadataBackdropPath, v))
}

// MetadataBackdropPathHasPrefix applies the HasPrefix predicate on the "metadata_backdrop_path" field.
func MetadataBackdropPathHasPrefix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasPrefix(FieldMetadataBackdropPath, v))
}

// MetadataBackdropPathHasSuffix applies the HasSuffix predicate on the "metadata_backdrop_path" field.
func MetadataBackdropPathHasSuffix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasSuffix(FieldMetadataBackdropPath, v))
}

// MetadataBackdropPathEqualFold applies the EqualFold predicate on the "metadata_backdrop_path" field.
func MetadataBackdropPathEqualFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEqualFold(FieldMetadataBackdropPath, v))
}

// MetadataBackdropPathContainsFold applies the ContainsFold predicate on the "metadata_backdrop_path" field.
func MetadataBackdropPathContainsFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContainsFold(FieldMetadataBackdropPath, v))
}

// MetadataHomepageEQ applies the EQ predicate on the "metadata_homepage" field.
func MetadataHomepageEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataHomepage, v))
}

// MetadataHomepageNEQ applies the NEQ predicate on the "metadata_homepage" field.
func MetadataHomepageNEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNEQ(FieldMetadataHomepage, v))
}

// MetadataHomepageIn applies the In predicate on the "metadata_homepage" field.
func MetadataHomepageIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldIn(FieldMetadataHomepage, vs...))
}

// MetadataHomepageNotIn applies the NotIn predicate on the "metadata_homepage" field.
func MetadataHomepageNotIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNotIn(FieldMetadataHomepage, vs...))
}

// MetadataHomepageGT applies the GT predicate on the "metadata_homepage" field.
func MetadataHomepageGT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGT(FieldMetadataHomepage, v))
}

// MetadataHomepageGTE applies the GTE predicate on the "metadata_homepage" field.
func MetadataHomepageGTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGTE(FieldMetadataHomepage, v))
}

// MetadataHomepageLT applies the LT predicate on the "metadata_homepage" field.
func MetadataHomepageLT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLT(FieldMetadataHomepage, v))
}

// MetadataHomepageLTE applies the LTE predicate on the "metadata_homepage" field.
func MetadataHomepageLTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLTE(FieldMetadataHomepage, v))
}

// MetadataHomepageContains applies the Contains predicate on the "metadata_homepage" field.
func MetadataHomepageContains(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContains(FieldMetadataHomepage, v))
}

// MetadataHomepageHasPrefix applies the HasPrefix predicate on the "metadata_homepage" field.
func MetadataHomepageHasPrefix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasPrefix(FieldMetadataHomepage, v))
}

// MetadataHomepageHasSuffix applies the HasSuffix predicate on the "metadata_homepage" field.
func MetadataHomepageHasSuffix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasSuffix(FieldMetadataHomepage, v))
}

// MetadataHomepageEqualFold applies the EqualFold predicate on the "metadata_homepage" field.
func MetadataHomepageEqualFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEqualFold(FieldMetadataHomepage, v))
}

// MetadataHomepageContainsFold applies the ContainsFold predicate on the "metadata_homepage" field.
func MetadataHomepageContainsFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContainsFold(FieldMetadataHomepage, v))
}

// MetadataImdbIDEQ applies the EQ predicate on the "metadata_imdb_id" field.
func MetadataImdbIDEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataImdbID, v))
}

// MetadataImdbIDNEQ applies the NEQ predicate on the "metadata_imdb_id" field.
func MetadataImdbIDNEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNEQ(FieldMetadataImdbID, v))
}

// MetadataImdbIDIn applies the In predicate on the "metadata_imdb_id" field.
func MetadataImdbIDIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldIn(FieldMetadataImdbID, vs...))
}

// MetadataImdbIDNotIn applies the NotIn predicate on the "metadata_imdb_id" field.
func MetadataImdbIDNotIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNotIn(FieldMetadataImdbID, vs...))
}

// MetadataImdbIDGT applies the GT predicate on the "metadata_imdb_id" field.
func MetadataImdbIDGT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGT(FieldMetadataImdbID, v))
}

// MetadataImdbIDGTE applies the GTE predicate on the "metadata_imdb_id" field.
func MetadataImdbIDGTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGTE(FieldMetadataImdbID, v))
}

// MetadataImdbIDLT applies the LT predicate on the "metadata_imdb_id" field.
func MetadataImdbIDLT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLT(FieldMetadataImdbID, v))
}

// MetadataImdbIDLTE applies the LTE predicate on the "metadata_imdb_id" field.
func MetadataImdbIDLTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLTE(FieldMetadataImdbID, v))
}

// MetadataImdbIDContains applies the Contains predicate on the "metadata_imdb_id" field.
func MetadataImdbIDContains(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContains(FieldMetadataImdbID, v))
}

// MetadataImdbIDHasPrefix applies the HasPrefix predicate on the "metadata_imdb_id" field.
func MetadataImdbIDHasPrefix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasPrefix(FieldMetadataImdbID, v))
}

// MetadataImdbIDHasSuffix applies the HasSuffix predicate on the "metadata_imdb_id" field.
func MetadataImdbIDHasSuffix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasSuffix(FieldMetadataImdbID, v))
}

// MetadataImdbIDEqualFold applies the EqualFold predicate on the "metadata_imdb_id" field.
func MetadataImdbIDEqualFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEqualFold(FieldMetadataImdbID, v))
}

// MetadataImdbIDContainsFold applies the ContainsFold predicate on the "metadata_imdb_id" field.
func MetadataImdbIDContainsFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContainsFold(FieldMetadataImdbID, v))
}

// MetadataOriginalLanguageEQ applies the EQ predicate on the "metadata_original_language" field.
func MetadataOriginalLanguageEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataOriginalLanguage, v))
}

// MetadataOriginalLanguageNEQ applies the NEQ predicate on the "metadata_original_language" field.
func MetadataOriginalLanguageNEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNEQ(FieldMetadataOriginalLanguage, v))
}

// MetadataOriginalLanguageIn applies the In predicate on the "metadata_original_language" field.
func MetadataOriginalLanguageIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldIn(FieldMetadataOriginalLanguage, vs...))
}

// MetadataOriginalLanguageNotIn applies the NotIn predicate on the "metadata_original_language" field.
func MetadataOriginalLanguageNotIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNotIn(FieldMetadataOriginalLanguage, vs...))
}

// MetadataOriginalLanguageGT applies the GT predicate on the "metadata_original_language" field.
func MetadataOriginalLanguageGT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGT(FieldMetadataOriginalLanguage, v))
}

// MetadataOriginalLanguageGTE applies the GTE predicate on the "metadata_original_language" field.
func MetadataOriginalLanguageGTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGTE(FieldMetadataOriginalLanguage, v))
}

// MetadataOriginalLanguageLT applies the LT predicate on the "metadata_original_language" field.
func MetadataOriginalLanguageLT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLT(FieldMetadataOriginalLanguage, v))
}

// MetadataOriginalLanguageLTE applies the LTE predicate on the "metadata_original_language" field.
func MetadataOriginalLanguageLTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLTE(FieldMetadataOriginalLanguage, v))
}

// MetadataOriginalLanguageContains applies the Contains predicate on the "metadata_original_language" field.
func MetadataOriginalLanguageContains(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContains(FieldMetadataOriginalLanguage, v))
}

// MetadataOriginalLanguageHasPrefix applies the HasPrefix predicate on the "metadata_original_language" field.
func MetadataOriginalLanguageHasPrefix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasPrefix(FieldMetadataOriginalLanguage, v))
}

// MetadataOriginalLanguageHasSuffix applies the HasSuffix predicate on the "metadata_original_language" field.
func MetadataOriginalLanguageHasSuffix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasSuffix(FieldMetadataOriginalLanguage, v))
}

// MetadataOriginalLanguageEqualFold applies the EqualFold predicate on the "metadata_original_language" field.
func MetadataOriginalLanguageEqualFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEqualFold(FieldMetadataOriginalLanguage, v))
}

// MetadataOriginalLanguageContainsFold applies the ContainsFold predicate on the "metadata_original_language" field.
func MetadataOriginalLanguageContainsFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContainsFold(FieldMetadataOriginalLanguage, v))
}

// MetadataOriginalTitleEQ applies the EQ predicate on the "metadata_original_title" field.
func MetadataOriginalTitleEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataOriginalTitle, v))
}

// MetadataOriginalTitleNEQ applies the NEQ predicate on the "metadata_original_title" field.
func MetadataOriginalTitleNEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNEQ(FieldMetadataOriginalTitle, v))
}

// MetadataOriginalTitleIn applies the In predicate on the "metadata_original_title" field.
func MetadataOriginalTitleIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldIn(FieldMetadataOriginalTitle, vs...))
}

// MetadataOriginalTitleNotIn applies the NotIn predicate on the "metadata_original_title" field.
func MetadataOriginalTitleNotIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNotIn(FieldMetadataOriginalTitle, vs...))
}

// MetadataOriginalTitleGT applies the GT predicate on the "metadata_original_title" field.
func MetadataOriginalTitleGT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGT(FieldMetadataOriginalTitle, v))
}

// MetadataOriginalTitleGTE applies the GTE predicate on the "metadata_original_title" field.
func MetadataOriginalTitleGTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGTE(FieldMetadataOriginalTitle, v))
}

// MetadataOriginalTitleLT applies the LT predicate on the "metadata_original_title" field.
func MetadataOriginalTitleLT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLT(FieldMetadataOriginalTitle, v))
}

// MetadataOriginalTitleLTE applies the LTE predicate on the "metadata_original_title" field.
func MetadataOriginalTitleLTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLTE(FieldMetadataOriginalTitle, v))
}

// MetadataOriginalTitleContains applies the Contains predicate on the "metadata_original_title" field.
func MetadataOriginalTitleContains(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContains(FieldMetadataOriginalTitle, v))
}

// MetadataOriginalTitleHasPrefix applies the HasPrefix predicate on the "metadata_original_title" field.
func MetadataOriginalTitleHasPrefix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasPrefix(FieldMetadataOriginalTitle, v))
}

// MetadataOriginalTitleHasSuffix applies the HasSuffix predicate on the "metadata_original_title" field.
func MetadataOriginalTitleHasSuffix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasSuffix(FieldMetadataOriginalTitle, v))
}

// MetadataOriginalTitleEqualFold applies the EqualFold predicate on the "metadata_original_title" field.
func MetadataOriginalTitleEqualFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEqualFold(FieldMetadataOriginalTitle, v))
}

// MetadataOriginalTitleContainsFold applies the ContainsFold predicate on the "metadata_original_title" field.
func MetadataOriginalTitleContainsFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContainsFold(FieldMetadataOriginalTitle, v))
}

// MetadataOverviewEQ applies the EQ predicate on the "metadata_overview" field.
func MetadataOverviewEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataOverview, v))
}

// MetadataOverviewNEQ applies the NEQ predicate on the "metadata_overview" field.
func MetadataOverviewNEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNEQ(FieldMetadataOverview, v))
}

// MetadataOverviewIn applies the In predicate on the "metadata_overview" field.
func MetadataOverviewIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldIn(FieldMetadataOverview, vs...))
}

// MetadataOverviewNotIn applies the NotIn predicate on the "metadata_overview" field.
func MetadataOverviewNotIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNotIn(FieldMetadataOverview, vs...))
}

// MetadataOverviewGT applies the GT predicate on the "metadata_overview" field.
func MetadataOverviewGT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGT(FieldMetadataOverview, v))
}

// MetadataOverviewGTE applies the GTE predicate on the "metadata_overview" field.
func MetadataOverviewGTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGTE(FieldMetadataOverview, v))
}

// MetadataOverviewLT applies the LT predicate on the "metadata_overview" field.
func MetadataOverviewLT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLT(FieldMetadataOverview, v))
}

// MetadataOverviewLTE applies the LTE predicate on the "metadata_overview" field.
func MetadataOverviewLTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLTE(FieldMetadataOverview, v))
}

// MetadataOverviewContains applies the Contains predicate on the "metadata_overview" field.
func MetadataOverviewContains(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContains(FieldMetadataOverview, v))
}

// MetadataOverviewHasPrefix applies the HasPrefix predicate on the "metadata_overview" field.
func MetadataOverviewHasPrefix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasPrefix(FieldMetadataOverview, v))
}

// MetadataOverviewHasSuffix applies the HasSuffix predicate on the "metadata_overview" field.
func MetadataOverviewHasSuffix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasSuffix(FieldMetadataOverview, v))
}

// MetadataOverviewEqualFold applies the EqualFold predicate on the "metadata_overview" field.
func MetadataOverviewEqualFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEqualFold(FieldMetadataOverview, v))
}

// MetadataOverviewContainsFold applies the ContainsFold predicate on the "metadata_overview" field.
func MetadataOverviewContainsFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContainsFold(FieldMetadataOverview, v))
}

// MetadataPopularityEQ applies the EQ predicate on the "metadata_popularity" field.
func MetadataPopularityEQ(v float32) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataPopularity, v))
}

// MetadataPopularityNEQ applies the NEQ predicate on the "metadata_popularity" field.
func MetadataPopularityNEQ(v float32) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNEQ(FieldMetadataPopularity, v))
}

// MetadataPopularityIn applies the In predicate on the "metadata_popularity" field.
func MetadataPopularityIn(vs ...float32) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldIn(FieldMetadataPopularity, vs...))
}

// MetadataPopularityNotIn applies the NotIn predicate on the "metadata_popularity" field.
func MetadataPopularityNotIn(vs ...float32) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNotIn(FieldMetadataPopularity, vs...))
}

// MetadataPopularityGT applies the GT predicate on the "metadata_popularity" field.
func MetadataPopularityGT(v float32) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGT(FieldMetadataPopularity, v))
}

// MetadataPopularityGTE applies the GTE predicate on the "metadata_popularity" field.
func MetadataPopularityGTE(v float32) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGTE(FieldMetadataPopularity, v))
}

// MetadataPopularityLT applies the LT predicate on the "metadata_popularity" field.
func MetadataPopularityLT(v float32) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLT(FieldMetadataPopularity, v))
}

// MetadataPopularityLTE applies the LTE predicate on the "metadata_popularity" field.
func MetadataPopularityLTE(v float32) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLTE(FieldMetadataPopularity, v))
}

// MetadataPosterPathEQ applies the EQ predicate on the "metadata_poster_path" field.
func MetadataPosterPathEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataPosterPath, v))
}

// MetadataPosterPathNEQ applies the NEQ predicate on the "metadata_poster_path" field.
func MetadataPosterPathNEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNEQ(FieldMetadataPosterPath, v))
}

// MetadataPosterPathIn applies the In predicate on the "metadata_poster_path" field.
func MetadataPosterPathIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldIn(FieldMetadataPosterPath, vs...))
}

// MetadataPosterPathNotIn applies the NotIn predicate on the "metadata_poster_path" field.
func MetadataPosterPathNotIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNotIn(FieldMetadataPosterPath, vs...))
}

// MetadataPosterPathGT applies the GT predicate on the "metadata_poster_path" field.
func MetadataPosterPathGT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGT(FieldMetadataPosterPath, v))
}

// MetadataPosterPathGTE applies the GTE predicate on the "metadata_poster_path" field.
func MetadataPosterPathGTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGTE(FieldMetadataPosterPath, v))
}

// MetadataPosterPathLT applies the LT predicate on the "metadata_poster_path" field.
func MetadataPosterPathLT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLT(FieldMetadataPosterPath, v))
}

// MetadataPosterPathLTE applies the LTE predicate on the "metadata_poster_path" field.
func MetadataPosterPathLTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLTE(FieldMetadataPosterPath, v))
}

// MetadataPosterPathContains applies the Contains predicate on the "metadata_poster_path" field.
func MetadataPosterPathContains(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContains(FieldMetadataPosterPath, v))
}

// MetadataPosterPathHasPrefix applies the HasPrefix predicate on the "metadata_poster_path" field.
func MetadataPosterPathHasPrefix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasPrefix(FieldMetadataPosterPath, v))
}

// MetadataPosterPathHasSuffix applies the HasSuffix predicate on the "metadata_poster_path" field.
func MetadataPosterPathHasSuffix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasSuffix(FieldMetadataPosterPath, v))
}

// MetadataPosterPathEqualFold applies the EqualFold predicate on the "metadata_poster_path" field.
func MetadataPosterPathEqualFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEqualFold(FieldMetadataPosterPath, v))
}

// MetadataPosterPathContainsFold applies the ContainsFold predicate on the "metadata_poster_path" field.
func MetadataPosterPathContainsFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContainsFold(FieldMetadataPosterPath, v))
}

// MetadataReleaseDateEQ applies the EQ predicate on the "metadata_release_date" field.
func MetadataReleaseDateEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataReleaseDate, v))
}

// MetadataReleaseDateNEQ applies the NEQ predicate on the "metadata_release_date" field.
func MetadataReleaseDateNEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNEQ(FieldMetadataReleaseDate, v))
}

// MetadataReleaseDateIn applies the In predicate on the "metadata_release_date" field.
func MetadataReleaseDateIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldIn(FieldMetadataReleaseDate, vs...))
}

// MetadataReleaseDateNotIn applies the NotIn predicate on the "metadata_release_date" field.
func MetadataReleaseDateNotIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNotIn(FieldMetadataReleaseDate, vs...))
}

// MetadataReleaseDateGT applies the GT predicate on the "metadata_release_date" field.
func MetadataReleaseDateGT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGT(FieldMetadataReleaseDate, v))
}

// MetadataReleaseDateGTE applies the GTE predicate on the "metadata_release_date" field.
func MetadataReleaseDateGTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGTE(FieldMetadataReleaseDate, v))
}

// MetadataReleaseDateLT applies the LT predicate on the "metadata_release_date" field.
func MetadataReleaseDateLT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLT(FieldMetadataReleaseDate, v))
}

// MetadataReleaseDateLTE applies the LTE predicate on the "metadata_release_date" field.
func MetadataReleaseDateLTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLTE(FieldMetadataReleaseDate, v))
}

// MetadataReleaseDateContains applies the Contains predicate on the "metadata_release_date" field.
func MetadataReleaseDateContains(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContains(FieldMetadataReleaseDate, v))
}

// MetadataReleaseDateHasPrefix applies the HasPrefix predicate on the "metadata_release_date" field.
func MetadataReleaseDateHasPrefix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasPrefix(FieldMetadataReleaseDate, v))
}

// MetadataReleaseDateHasSuffix applies the HasSuffix predicate on the "metadata_release_date" field.
func MetadataReleaseDateHasSuffix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasSuffix(FieldMetadataReleaseDate, v))
}

// MetadataReleaseDateEqualFold applies the EqualFold predicate on the "metadata_release_date" field.
func MetadataReleaseDateEqualFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEqualFold(FieldMetadataReleaseDate, v))
}

// MetadataReleaseDateContainsFold applies the ContainsFold predicate on the "metadata_release_date" field.
func MetadataReleaseDateContainsFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContainsFold(FieldMetadataReleaseDate, v))
}

// MetadataRevenueEQ applies the EQ predicate on the "metadata_revenue" field.
func MetadataRevenueEQ(v int64) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataRevenue, v))
}

// MetadataRevenueNEQ applies the NEQ predicate on the "metadata_revenue" field.
func MetadataRevenueNEQ(v int64) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNEQ(FieldMetadataRevenue, v))
}

// MetadataRevenueIn applies the In predicate on the "metadata_revenue" field.
func MetadataRevenueIn(vs ...int64) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldIn(FieldMetadataRevenue, vs...))
}

// MetadataRevenueNotIn applies the NotIn predicate on the "metadata_revenue" field.
func MetadataRevenueNotIn(vs ...int64) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNotIn(FieldMetadataRevenue, vs...))
}

// MetadataRevenueGT applies the GT predicate on the "metadata_revenue" field.
func MetadataRevenueGT(v int64) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGT(FieldMetadataRevenue, v))
}

// MetadataRevenueGTE applies the GTE predicate on the "metadata_revenue" field.
func MetadataRevenueGTE(v int64) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGTE(FieldMetadataRevenue, v))
}

// MetadataRevenueLT applies the LT predicate on the "metadata_revenue" field.
func MetadataRevenueLT(v int64) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLT(FieldMetadataRevenue, v))
}

// MetadataRevenueLTE applies the LTE predicate on the "metadata_revenue" field.
func MetadataRevenueLTE(v int64) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLTE(FieldMetadataRevenue, v))
}

// MetadataRuntimeEQ applies the EQ predicate on the "metadata_runtime" field.
func MetadataRuntimeEQ(v int) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataRuntime, v))
}

// MetadataRuntimeNEQ applies the NEQ predicate on the "metadata_runtime" field.
func MetadataRuntimeNEQ(v int) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNEQ(FieldMetadataRuntime, v))
}

// MetadataRuntimeIn applies the In predicate on the "metadata_runtime" field.
func MetadataRuntimeIn(vs ...int) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldIn(FieldMetadataRuntime, vs...))
}

// MetadataRuntimeNotIn applies the NotIn predicate on the "metadata_runtime" field.
func MetadataRuntimeNotIn(vs ...int) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNotIn(FieldMetadataRuntime, vs...))
}

// MetadataRuntimeGT applies the GT predicate on the "metadata_runtime" field.
func MetadataRuntimeGT(v int) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGT(FieldMetadataRuntime, v))
}

// MetadataRuntimeGTE applies the GTE predicate on the "metadata_runtime" field.
func MetadataRuntimeGTE(v int) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGTE(FieldMetadataRuntime, v))
}

// MetadataRuntimeLT applies the LT predicate on the "metadata_runtime" field.
func MetadataRuntimeLT(v int) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLT(FieldMetadataRuntime, v))
}

// MetadataRuntimeLTE applies the LTE predicate on the "metadata_runtime" field.
func MetadataRuntimeLTE(v int) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLTE(FieldMetadataRuntime, v))
}

// MetadataStatusEQ applies the EQ predicate on the "metadata_status" field.
func MetadataStatusEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataStatus, v))
}

// MetadataStatusNEQ applies the NEQ predicate on the "metadata_status" field.
func MetadataStatusNEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNEQ(FieldMetadataStatus, v))
}

// MetadataStatusIn applies the In predicate on the "metadata_status" field.
func MetadataStatusIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldIn(FieldMetadataStatus, vs...))
}

// MetadataStatusNotIn applies the NotIn predicate on the "metadata_status" field.
func MetadataStatusNotIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNotIn(FieldMetadataStatus, vs...))
}

// MetadataStatusGT applies the GT predicate on the "metadata_status" field.
func MetadataStatusGT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGT(FieldMetadataStatus, v))
}

// MetadataStatusGTE applies the GTE predicate on the "metadata_status" field.
func MetadataStatusGTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGTE(FieldMetadataStatus, v))
}

// MetadataStatusLT applies the LT predicate on the "metadata_status" field.
func MetadataStatusLT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLT(FieldMetadataStatus, v))
}

// MetadataStatusLTE applies the LTE predicate on the "metadata_status" field.
func MetadataStatusLTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLTE(FieldMetadataStatus, v))
}

// MetadataStatusContains applies the Contains predicate on the "metadata_status" field.
func MetadataStatusContains(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContains(FieldMetadataStatus, v))
}

// MetadataStatusHasPrefix applies the HasPrefix predicate on the "metadata_status" field.
func MetadataStatusHasPrefix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasPrefix(FieldMetadataStatus, v))
}

// MetadataStatusHasSuffix applies the HasSuffix predicate on the "metadata_status" field.
func MetadataStatusHasSuffix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasSuffix(FieldMetadataStatus, v))
}

// MetadataStatusEqualFold applies the EqualFold predicate on the "metadata_status" field.
func MetadataStatusEqualFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEqualFold(FieldMetadataStatus, v))
}

// MetadataStatusContainsFold applies the ContainsFold predicate on the "metadata_status" field.
func MetadataStatusContainsFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContainsFold(FieldMetadataStatus, v))
}

// MetadataTaglineEQ applies the EQ predicate on the "metadata_tagline" field.
func MetadataTaglineEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataTagline, v))
}

// MetadataTaglineNEQ applies the NEQ predicate on the "metadata_tagline" field.
func MetadataTaglineNEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNEQ(FieldMetadataTagline, v))
}

// MetadataTaglineIn applies the In predicate on the "metadata_tagline" field.
func MetadataTaglineIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldIn(FieldMetadataTagline, vs...))
}

// MetadataTaglineNotIn applies the NotIn predicate on the "metadata_tagline" field.
func MetadataTaglineNotIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNotIn(FieldMetadataTagline, vs...))
}

// MetadataTaglineGT applies the GT predicate on the "metadata_tagline" field.
func MetadataTaglineGT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGT(FieldMetadataTagline, v))
}

// MetadataTaglineGTE applies the GTE predicate on the "metadata_tagline" field.
func MetadataTaglineGTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGTE(FieldMetadataTagline, v))
}

// MetadataTaglineLT applies the LT predicate on the "metadata_tagline" field.
func MetadataTaglineLT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLT(FieldMetadataTagline, v))
}

// MetadataTaglineLTE applies the LTE predicate on the "metadata_tagline" field.
func MetadataTaglineLTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLTE(FieldMetadataTagline, v))
}

// MetadataTaglineContains applies the Contains predicate on the "metadata_tagline" field.
func MetadataTaglineContains(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContains(FieldMetadataTagline, v))
}

// MetadataTaglineHasPrefix applies the HasPrefix predicate on the "metadata_tagline" field.
func MetadataTaglineHasPrefix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasPrefix(FieldMetadataTagline, v))
}

// MetadataTaglineHasSuffix applies the HasSuffix predicate on the "metadata_tagline" field.
func MetadataTaglineHasSuffix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasSuffix(FieldMetadataTagline, v))
}

// MetadataTaglineEqualFold applies the EqualFold predicate on the "metadata_tagline" field.
func MetadataTaglineEqualFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEqualFold(FieldMetadataTagline, v))
}

// MetadataTaglineContainsFold applies the ContainsFold predicate on the "metadata_tagline" field.
func MetadataTaglineContainsFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContainsFold(FieldMetadataTagline, v))
}

// MetadataTitleEQ applies the EQ predicate on the "metadata_title" field.
func MetadataTitleEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataTitle, v))
}

// MetadataTitleNEQ applies the NEQ predicate on the "metadata_title" field.
func MetadataTitleNEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNEQ(FieldMetadataTitle, v))
}

// MetadataTitleIn applies the In predicate on the "metadata_title" field.
func MetadataTitleIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldIn(FieldMetadataTitle, vs...))
}

// MetadataTitleNotIn applies the NotIn predicate on the "metadata_title" field.
func MetadataTitleNotIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNotIn(FieldMetadataTitle, vs...))
}

// MetadataTitleGT applies the GT predicate on the "metadata_title" field.
func MetadataTitleGT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGT(FieldMetadataTitle, v))
}

// MetadataTitleGTE applies the GTE predicate on the "metadata_title" field.
func MetadataTitleGTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGTE(FieldMetadataTitle, v))
}

// MetadataTitleLT applies the LT predicate on the "metadata_title" field.
func MetadataTitleLT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLT(FieldMetadataTitle, v))
}

// MetadataTitleLTE applies the LTE predicate on the "metadata_title" field.
func MetadataTitleLTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLTE(FieldMetadataTitle, v))
}

// MetadataTitleContains applies the Contains predicate on the "metadata_title" field.
func MetadataTitleContains(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContains(FieldMetadataTitle, v))
}

// MetadataTitleHasPrefix applies the HasPrefix predicate on the "metadata_title" field.
func MetadataTitleHasPrefix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasPrefix(FieldMetadataTitle, v))
}

// MetadataTitleHasSuffix applies the HasSuffix predicate on the "metadata_title" field.
func MetadataTitleHasSuffix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasSuffix(FieldMetadataTitle, v))
}

// MetadataTitleEqualFold applies the EqualFold predicate on the "metadata_title" field.
func MetadataTitleEqualFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEqualFold(FieldMetadataTitle, v))
}

// MetadataTitleContainsFold applies the ContainsFold predicate on the "metadata_title" field.
func MetadataTitleContainsFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContainsFold(FieldMetadataTitle, v))
}

// MetadataVideoEQ applies the EQ predicate on the "metadata_video" field.
func MetadataVideoEQ(v bool) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataVideo, v))
}

// MetadataVideoNEQ applies the NEQ predicate on the "metadata_video" field.
func MetadataVideoNEQ(v bool) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNEQ(FieldMetadataVideo, v))
}

// MetadataVoteAverageEQ applies the EQ predicate on the "metadata_vote_average" field.
func MetadataVoteAverageEQ(v float32) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataVoteAverage, v))
}

// MetadataVoteAverageNEQ applies the NEQ predicate on the "metadata_vote_average" field.
func MetadataVoteAverageNEQ(v float32) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNEQ(FieldMetadataVoteAverage, v))
}

// MetadataVoteAverageIn applies the In predicate on the "metadata_vote_average" field.
func MetadataVoteAverageIn(vs ...float32) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldIn(FieldMetadataVoteAverage, vs...))
}

// MetadataVoteAverageNotIn applies the NotIn predicate on the "metadata_vote_average" field.
func MetadataVoteAverageNotIn(vs ...float32) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNotIn(FieldMetadataVoteAverage, vs...))
}

// MetadataVoteAverageGT applies the GT predicate on the "metadata_vote_average" field.
func MetadataVoteAverageGT(v float32) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGT(FieldMetadataVoteAverage, v))
}

// MetadataVoteAverageGTE applies the GTE predicate on the "metadata_vote_average" field.
func MetadataVoteAverageGTE(v float32) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGTE(FieldMetadataVoteAverage, v))
}

// MetadataVoteAverageLT applies the LT predicate on the "metadata_vote_average" field.
func MetadataVoteAverageLT(v float32) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLT(FieldMetadataVoteAverage, v))
}

// MetadataVoteAverageLTE applies the LTE predicate on the "metadata_vote_average" field.
func MetadataVoteAverageLTE(v float32) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLTE(FieldMetadataVoteAverage, v))
}

// MetadataVoteCountEQ applies the EQ predicate on the "metadata_vote_count" field.
func MetadataVoteCountEQ(v int64) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldMetadataVoteCount, v))
}

// MetadataVoteCountNEQ applies the NEQ predicate on the "metadata_vote_count" field.
func MetadataVoteCountNEQ(v int64) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNEQ(FieldMetadataVoteCount, v))
}

// MetadataVoteCountIn applies the In predicate on the "metadata_vote_count" field.
func MetadataVoteCountIn(vs ...int64) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldIn(FieldMetadataVoteCount, vs...))
}

// MetadataVoteCountNotIn applies the NotIn predicate on the "metadata_vote_count" field.
func MetadataVoteCountNotIn(vs ...int64) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNotIn(FieldMetadataVoteCount, vs...))
}

// MetadataVoteCountGT applies the GT predicate on the "metadata_vote_count" field.
func MetadataVoteCountGT(v int64) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGT(FieldMetadataVoteCount, v))
}

// MetadataVoteCountGTE applies the GTE predicate on the "metadata_vote_count" field.
func MetadataVoteCountGTE(v int64) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGTE(FieldMetadataVoteCount, v))
}

// MetadataVoteCountLT applies the LT predicate on the "metadata_vote_count" field.
func MetadataVoteCountLT(v int64) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLT(FieldMetadataVoteCount, v))
}

// MetadataVoteCountLTE applies the LTE predicate on the "metadata_vote_count" field.
func MetadataVoteCountLTE(v int64) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLTE(FieldMetadataVoteCount, v))
}

// CollectionIDEQ applies the EQ predicate on the "collection_id" field.
func CollectionIDEQ(v int64) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldCollectionID, v))
}

// CollectionIDNEQ applies the NEQ predicate on the "collection_id" field.
func CollectionIDNEQ(v int64) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNEQ(FieldCollectionID, v))
}

// CollectionIDIn applies the In predicate on the "collection_id" field.
func CollectionIDIn(vs ...int64) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldIn(FieldCollectionID, vs...))
}

// CollectionIDNotIn applies the NotIn predicate on the "collection_id" field.
func CollectionIDNotIn(vs ...int64) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNotIn(FieldCollectionID, vs...))
}

// CollectionIDGT applies the GT predicate on the "collection_id" field.
func CollectionIDGT(v int64) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGT(FieldCollectionID, v))
}

// CollectionIDGTE applies the GTE predicate on the "collection_id" field.
func CollectionIDGTE(v int64) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGTE(FieldCollectionID, v))
}

// CollectionIDLT applies the LT predicate on the "collection_id" field.
func CollectionIDLT(v int64) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLT(FieldCollectionID, v))
}

// CollectionIDLTE applies the LTE predicate on the "collection_id" field.
func CollectionIDLTE(v int64) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLTE(FieldCollectionID, v))
}

// CollectionNameEQ applies the EQ predicate on the "collection_name" field.
func CollectionNameEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldCollectionName, v))
}

// CollectionNameNEQ applies the NEQ predicate on the "collection_name" field.
func CollectionNameNEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNEQ(FieldCollectionName, v))
}

// CollectionNameIn applies the In predicate on the "collection_name" field.
func CollectionNameIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldIn(FieldCollectionName, vs...))
}

// CollectionNameNotIn applies the NotIn predicate on the "collection_name" field.
func CollectionNameNotIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNotIn(FieldCollectionName, vs...))
}

// CollectionNameGT applies the GT predicate on the "collection_name" field.
func CollectionNameGT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGT(FieldCollectionName, v))
}

// CollectionNameGTE applies the GTE predicate on the "collection_name" field.
func CollectionNameGTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGTE(FieldCollectionName, v))
}

// CollectionNameLT applies the LT predicate on the "collection_name" field.
func CollectionNameLT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLT(FieldCollectionName, v))
}

// CollectionNameLTE applies the LTE predicate on the "collection_name" field.
func CollectionNameLTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLTE(FieldCollectionName, v))
}

// CollectionNameContains applies the Contains predicate on the "collection_name" field.
func CollectionNameContains(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContains(FieldCollectionName, v))
}

// CollectionNameHasPrefix applies the HasPrefix predicate on the "collection_name" field.
func CollectionNameHasPrefix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasPrefix(FieldCollectionName, v))
}

// CollectionNameHasSuffix applies the HasSuffix predicate on the "collection_name" field.
func CollectionNameHasSuffix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasSuffix(FieldCollectionName, v))
}

// CollectionNameEqualFold applies the EqualFold predicate on the "collection_name" field.
func CollectionNameEqualFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEqualFold(FieldCollectionName, v))
}

// CollectionNameContainsFold applies the ContainsFold predicate on the "collection_name" field.
func CollectionNameContainsFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContainsFold(FieldCollectionName, v))
}

// CollectionPosterPathEQ applies the EQ predicate on the "collection_poster_path" field.
func CollectionPosterPathEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldCollectionPosterPath, v))
}

// CollectionPosterPathNEQ applies the NEQ predicate on the "collection_poster_path" field.
func CollectionPosterPathNEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNEQ(FieldCollectionPosterPath, v))
}

// CollectionPosterPathIn applies the In predicate on the "collection_poster_path" field.
func CollectionPosterPathIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldIn(FieldCollectionPosterPath, vs...))
}

// CollectionPosterPathNotIn applies the NotIn predicate on the "collection_poster_path" field.
func CollectionPosterPathNotIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNotIn(FieldCollectionPosterPath, vs...))
}

// CollectionPosterPathGT applies the GT predicate on the "collection_poster_path" field.
func CollectionPosterPathGT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGT(FieldCollectionPosterPath, v))
}

// CollectionPosterPathGTE applies the GTE predicate on the "collection_poster_path" field.
func CollectionPosterPathGTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGTE(FieldCollectionPosterPath, v))
}

// CollectionPosterPathLT applies the LT predicate on the "collection_poster_path" field.
func CollectionPosterPathLT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLT(FieldCollectionPosterPath, v))
}

// CollectionPosterPathLTE applies the LTE predicate on the "collection_poster_path" field.
func CollectionPosterPathLTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLTE(FieldCollectionPosterPath, v))
}

// CollectionPosterPathContains applies the Contains predicate on the "collection_poster_path" field.
func CollectionPosterPathContains(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContains(FieldCollectionPosterPath, v))
}

// CollectionPosterPathHasPrefix applies the HasPrefix predicate on the "collection_poster_path" field.
func CollectionPosterPathHasPrefix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasPrefix(FieldCollectionPosterPath, v))
}

// CollectionPosterPathHasSuffix applies the HasSuffix predicate on the "collection_poster_path" field.
func CollectionPosterPathHasSuffix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasSuffix(FieldCollectionPosterPath, v))
}

// CollectionPosterPathEqualFold applies the EqualFold predicate on the "collection_poster_path" field.
func CollectionPosterPathEqualFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEqualFold(FieldCollectionPosterPath, v))
}

// CollectionPosterPathContainsFold applies the ContainsFold predicate on the "collection_poster_path" field.
func CollectionPosterPathContainsFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContainsFold(FieldCollectionPosterPath, v))
}

// CollectionBackdropPathEQ applies the EQ predicate on the "collection_backdrop_path" field.
func CollectionBackdropPathEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEQ(FieldCollectionBackdropPath, v))
}

// CollectionBackdropPathNEQ applies the NEQ predicate on the "collection_backdrop_path" field.
func CollectionBackdropPathNEQ(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNEQ(FieldCollectionBackdropPath, v))
}

// CollectionBackdropPathIn applies the In predicate on the "collection_backdrop_path" field.
func CollectionBackdropPathIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldIn(FieldCollectionBackdropPath, vs...))
}

// CollectionBackdropPathNotIn applies the NotIn predicate on the "collection_backdrop_path" field.
func CollectionBackdropPathNotIn(vs ...string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldNotIn(FieldCollectionBackdropPath, vs...))
}

// CollectionBackdropPathGT applies the GT predicate on the "collection_backdrop_path" field.
func CollectionBackdropPathGT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGT(FieldCollectionBackdropPath, v))
}

// CollectionBackdropPathGTE applies the GTE predicate on the "collection_backdrop_path" field.
func CollectionBackdropPathGTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldGTE(FieldCollectionBackdropPath, v))
}

// CollectionBackdropPathLT applies the LT predicate on the "collection_backdrop_path" field.
func CollectionBackdropPathLT(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLT(FieldCollectionBackdropPath, v))
}

// CollectionBackdropPathLTE applies the LTE predicate on the "collection_backdrop_path" field.
func CollectionBackdropPathLTE(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldLTE(FieldCollectionBackdropPath, v))
}

// CollectionBackdropPathContains applies the Contains predicate on the "collection_backdrop_path" field.
func CollectionBackdropPathContains(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContains(FieldCollectionBackdropPath, v))
}

// CollectionBackdropPathHasPrefix applies the HasPrefix predicate on the "collection_backdrop_path" field.
func CollectionBackdropPathHasPrefix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasPrefix(FieldCollectionBackdropPath, v))
}

// CollectionBackdropPathHasSuffix applies the HasSuffix predicate on the "collection_backdrop_path" field.
func CollectionBackdropPathHasSuffix(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldHasSuffix(FieldCollectionBackdropPath, v))
}

// CollectionBackdropPathEqualFold applies the EqualFold predicate on the "collection_backdrop_path" field.
func CollectionBackdropPathEqualFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldEqualFold(FieldCollectionBackdropPath, v))
}

// CollectionBackdropPathContainsFold applies the ContainsFold predicate on the "collection_backdrop_path" field.
func CollectionBackdropPathContainsFold(v string) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.FieldContainsFold(FieldCollectionBackdropPath, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MovieWithFile) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MovieWithFile) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MovieWithFile) predicate.MovieWithFile {
	return predicate.MovieWithFile(sql.NotPredicates(p))
}
