export const DEVICE_PAIRING_TTL_MS = 10 * 60 * 1000;
export const DEVICE_PAIRING_POLL_INTERVAL_MS = 2_000;
export const DEVICE_PAIRING_USER_CODE_LENGTH = 8;
export const DEVICE_PAIRING_API_KEY_EXPIRES_IN_DAYS = 730;
export const DEVICE_PAIRING_API_KEY_EXPIRES_IN_SECONDS = DEVICE_PAIRING_API_KEY_EXPIRES_IN_DAYS * 24 * 60 * 60;
export const DEVICE_PAIRING_START_RATE_LIMIT_PER_MINUTE = 12;
export const DEVICE_PAIRING_APPROVE_RATE_LIMIT_PER_MINUTE = 20;
export const DEVICE_PAIRING_POLL_RATE_LIMIT_PER_MINUTE = 120;
