// Code generated by ent, DO NOT EDIT.

package useraccount

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the useraccount type in the database.
	Label = "user_account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldDisplayname holds the string denoting the displayname field in the database.
	FieldDisplayname = "displayname"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldSex holds the string denoting the sex field in the database.
	FieldSex = "sex"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldAPIKey holds the string denoting the api_key field in the database.
	FieldAPIKey = "api_key"
	// FieldCurrentStatus holds the string denoting the current_status field in the database.
	FieldCurrentStatus = "current_status"
	// FieldSettingTheme holds the string denoting the setting_theme field in the database.
	FieldSettingTheme = "setting_theme"
	// FieldSettingEnabled holds the string denoting the setting_enabled field in the database.
	FieldSettingEnabled = "setting_enabled"
	// FieldSettingLanguage holds the string denoting the setting_language field in the database.
	FieldSettingLanguage = "setting_language"
	// FieldSettingResolution holds the string denoting the setting_resolution field in the database.
	FieldSettingResolution = "setting_resolution"
	// FieldSettingBitrate holds the string denoting the setting_bitrate field in the database.
	FieldSettingBitrate = "setting_bitrate"
	// FieldSettingCodec holds the string denoting the setting_codec field in the database.
	FieldSettingCodec = "setting_codec"
	// FieldLastSeenAt holds the string denoting the last_seen_at field in the database.
	FieldLastSeenAt = "last_seen_at"
	// Table holds the table name of the useraccount in the database.
	Table = "user_accounts"
)

// Columns holds all SQL columns for useraccount fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldDisplayname,
	FieldUsername,
	FieldEmail,
	FieldPassword,
	FieldSex,
	FieldRole,
	FieldAPIKey,
	FieldCurrentStatus,
	FieldSettingTheme,
	FieldSettingEnabled,
	FieldSettingLanguage,
	FieldSettingResolution,
	FieldSettingBitrate,
	FieldSettingCodec,
	FieldLastSeenAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DisplaynameValidator is a validator for the "displayname" field. It is called by the builders before save.
	DisplaynameValidator func(string) error
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// SexValidator is a validator for the "sex" field. It is called by the builders before save.
	SexValidator func(string) error
	// RoleValidator is a validator for the "role" field. It is called by the builders before save.
	RoleValidator func(string) error
	// APIKeyValidator is a validator for the "api_key" field. It is called by the builders before save.
	APIKeyValidator func(string) error
	// DefaultCurrentStatus holds the default value on creation for the "current_status" field.
	DefaultCurrentStatus string
	// CurrentStatusValidator is a validator for the "current_status" field. It is called by the builders before save.
	CurrentStatusValidator func(string) error
	// DefaultSettingTheme holds the default value on creation for the "setting_theme" field.
	DefaultSettingTheme string
	// SettingThemeValidator is a validator for the "setting_theme" field. It is called by the builders before save.
	SettingThemeValidator func(string) error
	// DefaultSettingEnabled holds the default value on creation for the "setting_enabled" field.
	DefaultSettingEnabled bool
	// DefaultSettingLanguage holds the default value on creation for the "setting_language" field.
	DefaultSettingLanguage string
	// SettingLanguageValidator is a validator for the "setting_language" field. It is called by the builders before save.
	SettingLanguageValidator func(string) error
	// DefaultSettingResolution holds the default value on creation for the "setting_resolution" field.
	DefaultSettingResolution string
	// SettingResolutionValidator is a validator for the "setting_resolution" field. It is called by the builders before save.
	SettingResolutionValidator func(string) error
	// DefaultSettingBitrate holds the default value on creation for the "setting_bitrate" field.
	DefaultSettingBitrate int
	// DefaultSettingCodec holds the default value on creation for the "setting_codec" field.
	DefaultSettingCodec string
	// SettingCodecValidator is a validator for the "setting_codec" field. It is called by the builders before save.
	SettingCodecValidator func(string) error
)

// OrderOption defines the ordering options for the UserAccount queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByDisplayname orders the results by the displayname field.
func ByDisplayname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayname, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// BySex orders the results by the sex field.
func BySex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSex, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByAPIKey orders the results by the api_key field.
func ByAPIKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKey, opts...).ToFunc()
}

// ByCurrentStatus orders the results by the current_status field.
func ByCurrentStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentStatus, opts...).ToFunc()
}

// BySettingTheme orders the results by the setting_theme field.
func BySettingTheme(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettingTheme, opts...).ToFunc()
}

// BySettingEnabled orders the results by the setting_enabled field.
func BySettingEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettingEnabled, opts...).ToFunc()
}

// BySettingLanguage orders the results by the setting_language field.
func BySettingLanguage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettingLanguage, opts...).ToFunc()
}

// BySettingResolution orders the results by the setting_resolution field.
func BySettingResolution(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettingResolution, opts...).ToFunc()
}

// BySettingBitrate orders the results by the setting_bitrate field.
func BySettingBitrate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettingBitrate, opts...).ToFunc()
}

// BySettingCodec orders the results by the setting_codec field.
func BySettingCodec(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettingCodec, opts...).ToFunc()
}

// ByLastSeenAt orders the results by the last_seen_at field.
func ByLastSeenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSeenAt, opts...).ToFunc()
}
