// Code generated by ent, DO NOT EDIT.

package useraccount

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/lunarr-app/lunarr-go/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldDeletedAt, v))
}

// Displayname applies equality check predicate on the "displayname" field. It's identical to DisplaynameEQ.
func Displayname(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldDisplayname, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldUsername, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldEmail, v))
}

// Password applies equality check predicate on the "password" field. It's identical to PasswordEQ.
func Password(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldPassword, v))
}

// Sex applies equality check predicate on the "sex" field. It's identical to SexEQ.
func Sex(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldSex, v))
}

// Role applies equality check predicate on the "role" field. It's identical to RoleEQ.
func Role(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldRole, v))
}

// APIKey applies equality check predicate on the "api_key" field. It's identical to APIKeyEQ.
func APIKey(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldAPIKey, v))
}

// CurrentStatus applies equality check predicate on the "current_status" field. It's identical to CurrentStatusEQ.
func CurrentStatus(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldCurrentStatus, v))
}

// SettingTheme applies equality check predicate on the "setting_theme" field. It's identical to SettingThemeEQ.
func SettingTheme(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldSettingTheme, v))
}

// SettingEnabled applies equality check predicate on the "setting_enabled" field. It's identical to SettingEnabledEQ.
func SettingEnabled(v bool) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldSettingEnabled, v))
}

// SettingLanguage applies equality check predicate on the "setting_language" field. It's identical to SettingLanguageEQ.
func SettingLanguage(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldSettingLanguage, v))
}

// SettingResolution applies equality check predicate on the "setting_resolution" field. It's identical to SettingResolutionEQ.
func SettingResolution(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldSettingResolution, v))
}

// SettingBitrate applies equality check predicate on the "setting_bitrate" field. It's identical to SettingBitrateEQ.
func SettingBitrate(v int) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldSettingBitrate, v))
}

// SettingCodec applies equality check predicate on the "setting_codec" field. It's identical to SettingCodecEQ.
func SettingCodec(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldSettingCodec, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldLastSeenAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.UserAccount {
	return predicate.UserAccount(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNotNull(FieldDeletedAt))
}

// DisplaynameEQ applies the EQ predicate on the "displayname" field.
func DisplaynameEQ(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldDisplayname, v))
}

// DisplaynameNEQ applies the NEQ predicate on the "displayname" field.
func DisplaynameNEQ(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNEQ(FieldDisplayname, v))
}

// DisplaynameIn applies the In predicate on the "displayname" field.
func DisplaynameIn(vs ...string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldIn(FieldDisplayname, vs...))
}

// DisplaynameNotIn applies the NotIn predicate on the "displayname" field.
func DisplaynameNotIn(vs ...string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNotIn(FieldDisplayname, vs...))
}

// DisplaynameGT applies the GT predicate on the "displayname" field.
func DisplaynameGT(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGT(FieldDisplayname, v))
}

// DisplaynameGTE applies the GTE predicate on the "displayname" field.
func DisplaynameGTE(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGTE(FieldDisplayname, v))
}

// DisplaynameLT applies the LT predicate on the "displayname" field.
func DisplaynameLT(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLT(FieldDisplayname, v))
}

// DisplaynameLTE applies the LTE predicate on the "displayname" field.
func DisplaynameLTE(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLTE(FieldDisplayname, v))
}

// DisplaynameContains applies the Contains predicate on the "displayname" field.
func DisplaynameContains(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldContains(FieldDisplayname, v))
}

// DisplaynameHasPrefix applies the HasPrefix predicate on the "displayname" field.
func DisplaynameHasPrefix(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldHasPrefix(FieldDisplayname, v))
}

// DisplaynameHasSuffix applies the HasSuffix predicate on the "displayname" field.
func DisplaynameHasSuffix(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldHasSuffix(FieldDisplayname, v))
}

// DisplaynameEqualFold applies the EqualFold predicate on the "displayname" field.
func DisplaynameEqualFold(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEqualFold(FieldDisplayname, v))
}

// DisplaynameContainsFold applies the ContainsFold predicate on the "displayname" field.
func DisplaynameContainsFold(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldContainsFold(FieldDisplayname, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldContainsFold(FieldUsername, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldContainsFold(FieldEmail, v))
}

// PasswordEQ applies the EQ predicate on the "password" field.
func PasswordEQ(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldPassword, v))
}

// PasswordNEQ applies the NEQ predicate on the "password" field.
func PasswordNEQ(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNEQ(FieldPassword, v))
}

// PasswordIn applies the In predicate on the "password" field.
func PasswordIn(vs ...string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldIn(FieldPassword, vs...))
}

// PasswordNotIn applies the NotIn predicate on the "password" field.
func PasswordNotIn(vs ...string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNotIn(FieldPassword, vs...))
}

// PasswordGT applies the GT predicate on the "password" field.
func PasswordGT(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGT(FieldPassword, v))
}

// PasswordGTE applies the GTE predicate on the "password" field.
func PasswordGTE(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGTE(FieldPassword, v))
}

// PasswordLT applies the LT predicate on the "password" field.
func PasswordLT(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLT(FieldPassword, v))
}

// PasswordLTE applies the LTE predicate on the "password" field.
func PasswordLTE(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLTE(FieldPassword, v))
}

// PasswordContains applies the Contains predicate on the "password" field.
func PasswordContains(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldContains(FieldPassword, v))
}

// PasswordHasPrefix applies the HasPrefix predicate on the "password" field.
func PasswordHasPrefix(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldHasPrefix(FieldPassword, v))
}

// PasswordHasSuffix applies the HasSuffix predicate on the "password" field.
func PasswordHasSuffix(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldHasSuffix(FieldPassword, v))
}

// PasswordEqualFold applies the EqualFold predicate on the "password" field.
func PasswordEqualFold(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEqualFold(FieldPassword, v))
}

// PasswordContainsFold applies the ContainsFold predicate on the "password" field.
func PasswordContainsFold(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldContainsFold(FieldPassword, v))
}

// SexEQ applies the EQ predicate on the "sex" field.
func SexEQ(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldSex, v))
}

// SexNEQ applies the NEQ predicate on the "sex" field.
func SexNEQ(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNEQ(FieldSex, v))
}

// SexIn applies the In predicate on the "sex" field.
func SexIn(vs ...string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldIn(FieldSex, vs...))
}

// SexNotIn applies the NotIn predicate on the "sex" field.
func SexNotIn(vs ...string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNotIn(FieldSex, vs...))
}

// SexGT applies the GT predicate on the "sex" field.
func SexGT(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGT(FieldSex, v))
}

// SexGTE applies the GTE predicate on the "sex" field.
func SexGTE(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGTE(FieldSex, v))
}

// SexLT applies the LT predicate on the "sex" field.
func SexLT(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLT(FieldSex, v))
}

// SexLTE applies the LTE predicate on the "sex" field.
func SexLTE(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLTE(FieldSex, v))
}

// SexContains applies the Contains predicate on the "sex" field.
func SexContains(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldContains(FieldSex, v))
}

// SexHasPrefix applies the HasPrefix predicate on the "sex" field.
func SexHasPrefix(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldHasPrefix(FieldSex, v))
}

// SexHasSuffix applies the HasSuffix predicate on the "sex" field.
func SexHasSuffix(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldHasSuffix(FieldSex, v))
}

// SexEqualFold applies the EqualFold predicate on the "sex" field.
func SexEqualFold(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEqualFold(FieldSex, v))
}

// SexContainsFold applies the ContainsFold predicate on the "sex" field.
func SexContainsFold(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldContainsFold(FieldSex, v))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNotIn(FieldRole, vs...))
}

// RoleGT applies the GT predicate on the "role" field.
func RoleGT(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGT(FieldRole, v))
}

// RoleGTE applies the GTE predicate on the "role" field.
func RoleGTE(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGTE(FieldRole, v))
}

// RoleLT applies the LT predicate on the "role" field.
func RoleLT(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLT(FieldRole, v))
}

// RoleLTE applies the LTE predicate on the "role" field.
func RoleLTE(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLTE(FieldRole, v))
}

// RoleContains applies the Contains predicate on the "role" field.
func RoleContains(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldContains(FieldRole, v))
}

// RoleHasPrefix applies the HasPrefix predicate on the "role" field.
func RoleHasPrefix(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldHasPrefix(FieldRole, v))
}

// RoleHasSuffix applies the HasSuffix predicate on the "role" field.
func RoleHasSuffix(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldHasSuffix(FieldRole, v))
}

// RoleEqualFold applies the EqualFold predicate on the "role" field.
func RoleEqualFold(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEqualFold(FieldRole, v))
}

// RoleContainsFold applies the ContainsFold predicate on the "role" field.
func RoleContainsFold(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldContainsFold(FieldRole, v))
}

// APIKeyEQ applies the EQ predicate on the "api_key" field.
func APIKeyEQ(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldAPIKey, v))
}

// APIKeyNEQ applies the NEQ predicate on the "api_key" field.
func APIKeyNEQ(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNEQ(FieldAPIKey, v))
}

// APIKeyIn applies the In predicate on the "api_key" field.
func APIKeyIn(vs ...string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldIn(FieldAPIKey, vs...))
}

// APIKeyNotIn applies the NotIn predicate on the "api_key" field.
func APIKeyNotIn(vs ...string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNotIn(FieldAPIKey, vs...))
}

// APIKeyGT applies the GT predicate on the "api_key" field.
func APIKeyGT(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGT(FieldAPIKey, v))
}

// APIKeyGTE applies the GTE predicate on the "api_key" field.
func APIKeyGTE(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGTE(FieldAPIKey, v))
}

// APIKeyLT applies the LT predicate on the "api_key" field.
func APIKeyLT(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLT(FieldAPIKey, v))
}

// APIKeyLTE applies the LTE predicate on the "api_key" field.
func APIKeyLTE(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLTE(FieldAPIKey, v))
}

// APIKeyContains applies the Contains predicate on the "api_key" field.
func APIKeyContains(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldContains(FieldAPIKey, v))
}

// APIKeyHasPrefix applies the HasPrefix predicate on the "api_key" field.
func APIKeyHasPrefix(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldHasPrefix(FieldAPIKey, v))
}

// APIKeyHasSuffix applies the HasSuffix predicate on the "api_key" field.
func APIKeyHasSuffix(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldHasSuffix(FieldAPIKey, v))
}

// APIKeyEqualFold applies the EqualFold predicate on the "api_key" field.
func APIKeyEqualFold(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEqualFold(FieldAPIKey, v))
}

// APIKeyContainsFold applies the ContainsFold predicate on the "api_key" field.
func APIKeyContainsFold(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldContainsFold(FieldAPIKey, v))
}

// CurrentStatusEQ applies the EQ predicate on the "current_status" field.
func CurrentStatusEQ(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldCurrentStatus, v))
}

// CurrentStatusNEQ applies the NEQ predicate on the "current_status" field.
func CurrentStatusNEQ(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNEQ(FieldCurrentStatus, v))
}

// CurrentStatusIn applies the In predicate on the "current_status" field.
func CurrentStatusIn(vs ...string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldIn(FieldCurrentStatus, vs...))
}

// CurrentStatusNotIn applies the NotIn predicate on the "current_status" field.
func CurrentStatusNotIn(vs ...string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNotIn(FieldCurrentStatus, vs...))
}

// CurrentStatusGT applies the GT predicate on the "current_status" field.
func CurrentStatusGT(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGT(FieldCurrentStatus, v))
}

// CurrentStatusGTE applies the GTE predicate on the "current_status" field.
func CurrentStatusGTE(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGTE(FieldCurrentStatus, v))
}

// CurrentStatusLT applies the LT predicate on the "current_status" field.
func CurrentStatusLT(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLT(FieldCurrentStatus, v))
}

// CurrentStatusLTE applies the LTE predicate on the "current_status" field.
func CurrentStatusLTE(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLTE(FieldCurrentStatus, v))
}

// CurrentStatusContains applies the Contains predicate on the "current_status" field.
func CurrentStatusContains(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldContains(FieldCurrentStatus, v))
}

// CurrentStatusHasPrefix applies the HasPrefix predicate on the "current_status" field.
func CurrentStatusHasPrefix(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldHasPrefix(FieldCurrentStatus, v))
}

// CurrentStatusHasSuffix applies the HasSuffix predicate on the "current_status" field.
func CurrentStatusHasSuffix(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldHasSuffix(FieldCurrentStatus, v))
}

// CurrentStatusEqualFold applies the EqualFold predicate on the "current_status" field.
func CurrentStatusEqualFold(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEqualFold(FieldCurrentStatus, v))
}

// CurrentStatusContainsFold applies the ContainsFold predicate on the "current_status" field.
func CurrentStatusContainsFold(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldContainsFold(FieldCurrentStatus, v))
}

// SettingThemeEQ applies the EQ predicate on the "setting_theme" field.
func SettingThemeEQ(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldSettingTheme, v))
}

// SettingThemeNEQ applies the NEQ predicate on the "setting_theme" field.
func SettingThemeNEQ(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNEQ(FieldSettingTheme, v))
}

// SettingThemeIn applies the In predicate on the "setting_theme" field.
func SettingThemeIn(vs ...string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldIn(FieldSettingTheme, vs...))
}

// SettingThemeNotIn applies the NotIn predicate on the "setting_theme" field.
func SettingThemeNotIn(vs ...string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNotIn(FieldSettingTheme, vs...))
}

// SettingThemeGT applies the GT predicate on the "setting_theme" field.
func SettingThemeGT(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGT(FieldSettingTheme, v))
}

// SettingThemeGTE applies the GTE predicate on the "setting_theme" field.
func SettingThemeGTE(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGTE(FieldSettingTheme, v))
}

// SettingThemeLT applies the LT predicate on the "setting_theme" field.
func SettingThemeLT(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLT(FieldSettingTheme, v))
}

// SettingThemeLTE applies the LTE predicate on the "setting_theme" field.
func SettingThemeLTE(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLTE(FieldSettingTheme, v))
}

// SettingThemeContains applies the Contains predicate on the "setting_theme" field.
func SettingThemeContains(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldContains(FieldSettingTheme, v))
}

// SettingThemeHasPrefix applies the HasPrefix predicate on the "setting_theme" field.
func SettingThemeHasPrefix(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldHasPrefix(FieldSettingTheme, v))
}

// SettingThemeHasSuffix applies the HasSuffix predicate on the "setting_theme" field.
func SettingThemeHasSuffix(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldHasSuffix(FieldSettingTheme, v))
}

// SettingThemeEqualFold applies the EqualFold predicate on the "setting_theme" field.
func SettingThemeEqualFold(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEqualFold(FieldSettingTheme, v))
}

// SettingThemeContainsFold applies the ContainsFold predicate on the "setting_theme" field.
func SettingThemeContainsFold(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldContainsFold(FieldSettingTheme, v))
}

// SettingEnabledEQ applies the EQ predicate on the "setting_enabled" field.
func SettingEnabledEQ(v bool) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldSettingEnabled, v))
}

// SettingEnabledNEQ applies the NEQ predicate on the "setting_enabled" field.
func SettingEnabledNEQ(v bool) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNEQ(FieldSettingEnabled, v))
}

// SettingLanguageEQ applies the EQ predicate on the "setting_language" field.
func SettingLanguageEQ(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldSettingLanguage, v))
}

// SettingLanguageNEQ applies the NEQ predicate on the "setting_language" field.
func SettingLanguageNEQ(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNEQ(FieldSettingLanguage, v))
}

// SettingLanguageIn applies the In predicate on the "setting_language" field.
func SettingLanguageIn(vs ...string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldIn(FieldSettingLanguage, vs...))
}

// SettingLanguageNotIn applies the NotIn predicate on the "setting_language" field.
func SettingLanguageNotIn(vs ...string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNotIn(FieldSettingLanguage, vs...))
}

// SettingLanguageGT applies the GT predicate on the "setting_language" field.
func SettingLanguageGT(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGT(FieldSettingLanguage, v))
}

// SettingLanguageGTE applies the GTE predicate on the "setting_language" field.
func SettingLanguageGTE(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGTE(FieldSettingLanguage, v))
}

// SettingLanguageLT applies the LT predicate on the "setting_language" field.
func SettingLanguageLT(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLT(FieldSettingLanguage, v))
}

// SettingLanguageLTE applies the LTE predicate on the "setting_language" field.
func SettingLanguageLTE(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLTE(FieldSettingLanguage, v))
}

// SettingLanguageContains applies the Contains predicate on the "setting_language" field.
func SettingLanguageContains(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldContains(FieldSettingLanguage, v))
}

// SettingLanguageHasPrefix applies the HasPrefix predicate on the "setting_language" field.
func SettingLanguageHasPrefix(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldHasPrefix(FieldSettingLanguage, v))
}

// SettingLanguageHasSuffix applies the HasSuffix predicate on the "setting_language" field.
func SettingLanguageHasSuffix(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldHasSuffix(FieldSettingLanguage, v))
}

// SettingLanguageEqualFold applies the EqualFold predicate on the "setting_language" field.
func SettingLanguageEqualFold(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEqualFold(FieldSettingLanguage, v))
}

// SettingLanguageContainsFold applies the ContainsFold predicate on the "setting_language" field.
func SettingLanguageContainsFold(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldContainsFold(FieldSettingLanguage, v))
}

// SettingResolutionEQ applies the EQ predicate on the "setting_resolution" field.
func SettingResolutionEQ(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldSettingResolution, v))
}

// SettingResolutionNEQ applies the NEQ predicate on the "setting_resolution" field.
func SettingResolutionNEQ(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNEQ(FieldSettingResolution, v))
}

// SettingResolutionIn applies the In predicate on the "setting_resolution" field.
func SettingResolutionIn(vs ...string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldIn(FieldSettingResolution, vs...))
}

// SettingResolutionNotIn applies the NotIn predicate on the "setting_resolution" field.
func SettingResolutionNotIn(vs ...string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNotIn(FieldSettingResolution, vs...))
}

// SettingResolutionGT applies the GT predicate on the "setting_resolution" field.
func SettingResolutionGT(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGT(FieldSettingResolution, v))
}

// SettingResolutionGTE applies the GTE predicate on the "setting_resolution" field.
func SettingResolutionGTE(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGTE(FieldSettingResolution, v))
}

// SettingResolutionLT applies the LT predicate on the "setting_resolution" field.
func SettingResolutionLT(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLT(FieldSettingResolution, v))
}

// SettingResolutionLTE applies the LTE predicate on the "setting_resolution" field.
func SettingResolutionLTE(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLTE(FieldSettingResolution, v))
}

// SettingResolutionContains applies the Contains predicate on the "setting_resolution" field.
func SettingResolutionContains(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldContains(FieldSettingResolution, v))
}

// SettingResolutionHasPrefix applies the HasPrefix predicate on the "setting_resolution" field.
func SettingResolutionHasPrefix(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldHasPrefix(FieldSettingResolution, v))
}

// SettingResolutionHasSuffix applies the HasSuffix predicate on the "setting_resolution" field.
func SettingResolutionHasSuffix(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldHasSuffix(FieldSettingResolution, v))
}

// SettingResolutionEqualFold applies the EqualFold predicate on the "setting_resolution" field.
func SettingResolutionEqualFold(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEqualFold(FieldSettingResolution, v))
}

// SettingResolutionContainsFold applies the ContainsFold predicate on the "setting_resolution" field.
func SettingResolutionContainsFold(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldContainsFold(FieldSettingResolution, v))
}

// SettingBitrateEQ applies the EQ predicate on the "setting_bitrate" field.
func SettingBitrateEQ(v int) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldSettingBitrate, v))
}

// SettingBitrateNEQ applies the NEQ predicate on the "setting_bitrate" field.
func SettingBitrateNEQ(v int) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNEQ(FieldSettingBitrate, v))
}

// SettingBitrateIn applies the In predicate on the "setting_bitrate" field.
func SettingBitrateIn(vs ...int) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldIn(FieldSettingBitrate, vs...))
}

// SettingBitrateNotIn applies the NotIn predicate on the "setting_bitrate" field.
func SettingBitrateNotIn(vs ...int) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNotIn(FieldSettingBitrate, vs...))
}

// SettingBitrateGT applies the GT predicate on the "setting_bitrate" field.
func SettingBitrateGT(v int) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGT(FieldSettingBitrate, v))
}

// SettingBitrateGTE applies the GTE predicate on the "setting_bitrate" field.
func SettingBitrateGTE(v int) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGTE(FieldSettingBitrate, v))
}

// SettingBitrateLT applies the LT predicate on the "setting_bitrate" field.
func SettingBitrateLT(v int) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLT(FieldSettingBitrate, v))
}

// SettingBitrateLTE applies the LTE predicate on the "setting_bitrate" field.
func SettingBitrateLTE(v int) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLTE(FieldSettingBitrate, v))
}

// SettingCodecEQ applies the EQ predicate on the "setting_codec" field.
func SettingCodecEQ(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldSettingCodec, v))
}

// SettingCodecNEQ applies the NEQ predicate on the "setting_codec" field.
func SettingCodecNEQ(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNEQ(FieldSettingCodec, v))
}

// SettingCodecIn applies the In predicate on the "setting_codec" field.
func SettingCodecIn(vs ...string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldIn(FieldSettingCodec, vs...))
}

// SettingCodecNotIn applies the NotIn predicate on the "setting_codec" field.
func SettingCodecNotIn(vs ...string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNotIn(FieldSettingCodec, vs...))
}

// SettingCodecGT applies the GT predicate on the "setting_codec" field.
func SettingCodecGT(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGT(FieldSettingCodec, v))
}

// SettingCodecGTE applies the GTE predicate on the "setting_codec" field.
func SettingCodecGTE(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGTE(FieldSettingCodec, v))
}

// SettingCodecLT applies the LT predicate on the "setting_codec" field.
func SettingCodecLT(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLT(FieldSettingCodec, v))
}

// SettingCodecLTE applies the LTE predicate on the "setting_codec" field.
func SettingCodecLTE(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLTE(FieldSettingCodec, v))
}

// SettingCodecContains applies the Contains predicate on the "setting_codec" field.
func SettingCodecContains(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldContains(FieldSettingCodec, v))
}

// SettingCodecHasPrefix applies the HasPrefix predicate on the "setting_codec" field.
func SettingCodecHasPrefix(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldHasPrefix(FieldSettingCodec, v))
}

// SettingCodecHasSuffix applies the HasSuffix predicate on the "setting_codec" field.
func SettingCodecHasSuffix(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldHasSuffix(FieldSettingCodec, v))
}

// SettingCodecEqualFold applies the EqualFold predicate on the "setting_codec" field.
func SettingCodecEqualFold(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEqualFold(FieldSettingCodec, v))
}

// SettingCodecContainsFold applies the ContainsFold predicate on the "setting_codec" field.
func SettingCodecContainsFold(v string) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldContainsFold(FieldSettingCodec, v))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.UserAccount {
	return predicate.UserAccount(sql.FieldLTE(FieldLastSeenAt, v))
}

// LastSeenAtIsNil applies the IsNil predicate on the "last_seen_at" field.
func LastSeenAtIsNil() predicate.UserAccount {
	return predicate.UserAccount(sql.FieldIsNull(FieldLastSeenAt))
}

// LastSeenAtNotNil applies the NotNil predicate on the "last_seen_at" field.
func LastSeenAtNotNil() predicate.UserAccount {
	return predicate.UserAccount(sql.FieldNotNull(FieldLastSeenAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserAccount) predicate.UserAccount {
	return predicate.UserAccount(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserAccount) predicate.UserAccount {
	return predicate.UserAccount(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserAccount) predicate.UserAccount {
	return predicate.UserAccount(sql.NotPredicates(p))
}
