basePath: /
definitions:
  handlers.ResponseHello:
    properties:
      hello:
        type: string
    type: object
  models.BelongsToCollection:
    properties:
      backdrop_path:
        type: string
      id:
        type: integer
      name:
        type: string
      poster_path:
        type: string
    type: object
  models.MovieMetadata:
    properties:
      adult:
        type: boolean
      backdrop_path:
        type: string
      genres:
        items:
          $ref: '#/definitions/models.TMDbGenre'
        type: array
      homepage:
        type: string
      imdb_id:
        type: string
      original_language:
        type: string
      original_title:
        type: string
      overview:
        type: string
      popularity:
        type: number
      poster_path:
        type: string
      release_date:
        type: string
      revenue:
        type: integer
      runtime:
        type: integer
      spoken_languages:
        items:
          $ref: '#/definitions/models.TMDbSpokenLanguage'
        type: array
      status:
        type: string
      tagline:
        type: string
      title:
        type: string
      video:
        type: boolean
      vote_average:
        type: number
      vote_count:
        type: integer
    type: object
  models.MovieWithFiles:
    properties:
      belongs_to_collection:
        $ref: '#/definitions/models.BelongsToCollection'
      location:
        type: string
      metadata:
        $ref: '#/definitions/models.MovieMetadata'
      tmdb_id:
        type: integer
    type: object
  models.SubtitleSettings:
    properties:
      enabled:
        type: boolean
      language:
        type: string
    type: object
  models.TMDbGenre:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  models.TMDbSpokenLanguage:
    properties:
      iso_639_1:
        type: string
      name:
        type: string
    type: object
  models.TranscodingSettings:
    properties:
      bitrate:
        type: integer
      codec:
        type: string
      resolution:
        type: string
    type: object
  models.UserAccounts:
    properties:
      api_key:
        type: string
      current_status:
        type: string
      displayname:
        type: string
      email:
        type: string
      last_seen_at:
        type: string
      password:
        type: string
      role:
        $ref: '#/definitions/models.UserRole'
      settings:
        $ref: '#/definitions/models.UserSettings'
      sex:
        type: string
      username:
        type: string
    type: object
  models.UserRole:
    enum:
    - admin
    - superuser
    - subscriber
    type: string
    x-enum-varnames:
    - UserRoleAdmin
    - UserRoleSuperuser
    - UserRoleSubscriber
  models.UserSettings:
    properties:
      subtitle:
        $ref: '#/definitions/models.SubtitleSettings'
      theme:
        type: string
      transcoding:
        $ref: '#/definitions/models.TranscodingSettings'
    type: object
  schema.ErrorResponse:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  schema.ListsResponse:
    properties:
      limit:
        type: integer
      page_current:
        type: integer
      page_total:
        type: integer
      results:
        items:
          $ref: '#/definitions/models.MovieWithFiles'
        type: array
    type: object
  schema.UserLogin:
    properties:
      password:
        maxLength: 32
        minLength: 6
        type: string
      username:
        maxLength: 16
        minLength: 2
        type: string
    required:
    - password
    - username
    type: object
  schema.UserLoginResponse:
    properties:
      api_key:
        type: string
      status:
        type: string
    type: object
  schema.UserSignup:
    properties:
      displayname:
        maxLength: 48
        minLength: 1
        type: string
      email:
        type: string
      password:
        maxLength: 32
        minLength: 6
        type: string
      sex:
        enum:
        - male
        - female
        - unknown
        type: string
      username:
        maxLength: 16
        minLength: 2
        type: string
    required:
    - displayname
    - email
    - password
    - username
    type: object
  schema.UserSignupResponse:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
host: 127.0.0.1:3000
info:
  contact: {}
  description: Swagger for Lunarr API endpoints
  title: Lunarr API
  version: "1.0"
paths:
  /api/movies:
    get:
      consumes:
      - application/json
      description: Get a list of movies based on the search query and pagination parameters.
      parameters:
      - description: API Key
        in: header
        name: x-api-key
        required: true
        type: string
      - default: 1
        description: Page number
        in: query
        name: page
        required: true
        type: integer
      - default: 20
        description: Number of movies per page
        in: query
        name: limit
        required: true
        type: integer
      - description: Search by movie title
        in: query
        name: title
        type: string
      - description: Search by movie release year
        in: query
        name: year
        type: string
      - default: '"recent"'
        description: 'Sort by: recent, latest, popular'
        in: query
        name: sortBy
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.ListsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
      summary: Get Movie Lists
      tags:
      - movies
  /api/movies/{id}:
    get:
      consumes:
      - application/json
      description: Get movie details by ID.
      parameters:
      - description: API Key
        in: header
        name: x-api-key
        required: true
        type: string
      - description: Movie ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.MovieWithFiles'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
      summary: Get Movie Details by ID
      tags:
      - movies
  /api/movies/{tmdb_id}/stream:
    get:
      consumes:
      - application/json
      description: Stream a movie based on the TMDb ID.
      parameters:
      - description: API Key
        in: header
        name: x-api-key
        required: true
        type: string
      - description: TMDb ID
        in: path
        name: tmdb_id
        required: true
        type: integer
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            type: file
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
      summary: Stream a movie
      tags:
      - movies
  /api/users:
    get:
      consumes:
      - application/json
      description: Retrieve all users.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.UserAccounts'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
      summary: Get All Users
      tags:
      - users
  /api/users/me:
    get:
      consumes:
      - application/json
      description: Retrieve the user data for the authenticated user.
      parameters:
      - description: API Key
        in: header
        name: x-api-key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserAccounts'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
      summary: Get User Data
      tags:
      - users
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: Login Request
        in: body
        name: loginReq
        required: true
        schema:
          $ref: '#/definitions/schema.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.UserLoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
      summary: Login
      tags:
      - auth
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Creates a new user account.
      parameters:
      - description: User Signup Request
        in: body
        name: userReq
        required: true
        schema:
          $ref: '#/definitions/schema.UserSignup'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/schema.UserSignupResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schema.ErrorResponse'
      summary: User Signup
      tags:
      - auth
  /hello:
    get:
      consumes:
      - application/json
      description: Hello
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.ResponseHello'
      summary: Hello
      tags:
      - root
swagger: "2.0"
